### ISSUE TITLE
[feature request] Verify provenance files (before installation)

### ISSUE THREAD

**Issue by lindhe** [vmware-tanzu/kubeapps#1101]
Helm makes use of [provenance files](https://helm.sh/docs/developing_charts/#helm-provenance-and-integrity) to ensure authenticity and integrity of charts. It would be a really nice feature if Kubeapps could verify the signature included in the .prov file (if it exists).

I'm thinking a nice badge somewhere at the chart page (e.g., ✔️/❌), or at least the option to verify when deploying. Using the helm CLI, it would be `helm install --verify`.

**Comment by andresmgot** [comment]
That's interesting indeed. Do you know if that is a common approach? I mean signing charts. Are charts under the `stable` repository signed?

**Comment by lindhe** [comment]
No, I don't know how common it is in Helm. It is a very common practice in other package managers to sign packages (like in apt and pacman). It is also common with signed Docker images. So would I assume that it *should* be reasonably common in Helm too. But perhaps it is not widely adopted in Helm yet?

I cannot find any examples of .prov files in the stable repo. But there is a fair chunk of [documentation available](https://github.com/helm/helm/blob/44782e19b6f11e64e9aa5dce4b70ff38ac7a1942/docs/provenance.md), so it does not seem like a small obscure feature. Perhaps it's simply a case of people being afraid GPG... ;)

**Comment by andresmgot** [comment]
Yes, it's a good feature though. I have asked about that to Bitnami chart maintainers and they have replied that they will investigate it. Hopefully we can see some signed charts soon :)

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps. Could be re-opened if more demand on this issue.
