### ISSUE TITLE
Add support for running helm chart tests on a deployed release in dashboard

### ISSUE THREAD

**Issue by latiif** [vmware-tanzu/kubeapps#1106]
### Adding support for running helm chart tests on a deployed release in dashboard
Using `helm`, one can run a set of pre-defined tests for a given release. [See doc on Chart Tests](https://helm.sh/docs/chart_tests/).

After deploying a release from a chart, one should be able to run the tests defined in the Helm Chart. 

### The How
+ Release is deployed and ready.
+ Clicking on *Run Tests* should run the tests against the release, something similar to `helm test <RELEASE_NAME>`.
+ The output from that command is shown in a meaningful way (styled messages).
+ Labels describing the outcome of the test process, can be permanently displayed on the release's page.

### The Why 
Although testing can be done via `helm` manually, having the possibility to do it from within the dashboard will make it easier to check the quality of one's release.<br/>
Visualizing the results of the tests will give more information to the people maintaining the Kubernetes cluster at a glance.

*P.S.* I am eager to try and start working on this feature, so if this gets approved I might need some help setting up the development environment.

**Comment by andresmgot** [comment]
Hi @llusx,

That could be an interesting feature, I agree :)

We would need to add support to that in `tiller-proxy` that is the service we use to communicate with Tiller.

This feature is not trivial to implement though. If you want to give it a try we can help with any question you may have, reading the developer documentation can be a good start.

Thank you for the proposal!

**Comment by llusx** [comment]
Thanks for your response and for the tip.
I'll see how far I can get with this feature.

**Comment by llusx** [comment]
Hi again, @andresmgot!

What's your take on a suitable endpoint for the tiller-proxy API?

During dev, I tried to mimic your style and used 
*GET* /v1/namespaces/{namespace}/releases/{release}/test
Any suggestions?

Concerning the result of the endpoint, currently it returns something similar to this (example run against the release *kubeapps* in the namespace *kubeapps*)
```json
{
  "data": {
    "run": [
      "kubeapps-chartsvc-test",
      "kubeapps-dashboard-test",
      "kubeapps-tiller-proxy-test"
    ],
    "passed": [
      "kubeapps-chartsvc-test",
      "kubeapps-dashboard-test",
      "kubeapps-tiller-proxy-test"
    ]
  }
}
```

Any failed tests will be populated inside an array called `failed`.

Thanks for your time.

**Comment by andresmgot** [comment]
That sounds good to me! Let me know if you want me to start reviewing something.

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps.
