### ISSUE TITLE
Feature Request - Compare changes of Installation Values before doing a rollback

### ISSUE THREAD

**Issue by lucasoares** [vmware-tanzu/kubeapps#1166]
Would be great if we could see the modifications of the installation values before doing any rollback on kubeapps.

For this we will need the feature #614.

**Comment by absoludity** [comment]
Thanks Lucas. Also related to discussions on #1144 about parsing `values.yaml` to compare differences.

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps. Could be re-opened if more demand on this issue.
