### ISSUE TITLE
Move app repo sync to run in repo namespace (and cluster)

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#1647]
Currently, when creating an AppRepository, if the app repo namespace isn't kubeapps (ie. this is a per-namespace AppRepository), for a private repo we save a copy of the repository secret in kubeapps own namespace using the service account clientset. This enables the existing assetsync service to be able to sync private AppRepositories in other namespaces.

It is not ideal and is a temporary work-around until the asset-sync is updated to run cronjobs in other namespaces with the assetsvc receiving the data. See the [relevant section of the design doc for details](https://docs.google.com/document/d/1YEeKC6nPLoq4oaxs9v8_UsmxrRfWxB6KCyqrh2-Q8x0/edit?ts=5e2adf87#heading=h.kilvd2vii0w).

This issue is a placeholder to refer to in code, to ensure that we move the sync job to the user namespace (and send data from there to the assetsvc) and remove the code creating the copy.

**Comment by ppbaena** [comment]
To be closed as it is not considered in the current roadmap for Kubeapps, and it's a long time since it was requested.
