### ISSUE TITLE
Enable AppRepositories to be available in multiple namespaces (backend)

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#1701]
Continuing on from the recent per-namespace AppRepository support, ensure an AppRepository can be made available in multiple namespaces:

- [ ] Update the AppRepository resource to support the additional field availableNamespaces (string list)
- [ ] [API] Update the create AppRepository handler to save the AppRepository in the available namespaces (users credentials, verify first and fail if already present or user does not have access in all namespaces?)
- [ ] [API] Update the create AppRepository handler to ensure referenced secrets are made available in all available namespaces (explicit user action).
- [ ] [API] Update the update AppRepository handler to ensure the app repo is added/removed from relevant namespaces (using users credentials)
- [ ] [API] Update the update AppRepository handler to ensure the associated imagePullSecrets are added (but not removed, runtime data) from relevant namespaces (using users credentials). No need to handle editing of secrets (currently). If a secret by the name exists already, don't overwrite (this will be handled if UI later enables editing of the image pull secret for a repo).

**Comment by andresmgot** [comment]
IMO, I would just make changes in the UI and make it clear that we are creating copies in multiple namespaces and that further edits won't be propagated. At least for the first version, the complexity would be much less. Also we are not sure about two points: We don't know if people are interested on having a private app repository in multiple namespaces neither if they are interested on updating them once it's already working.

**Comment by absoludity** [comment]
> IMO, I would just make changes in the UI and make it clear that we are creating copies in multiple namespaces

Note that would also mean the UI copying any selected secrets from one namespace to another. As I mentioned the other day (the trigger for #1686), I am really keen for us to *stop* accessing actual secrets in the frontend (ie. not having the actual `secret.data` go over the wire to the client browser) except where explicitly requested by the user (ie. viewing a secret's data explicitly).

>  and that further edits won't be propagated.

This would also, IMO, be quite confusing. To create something representing an AppRepository available in multiple namespaces while enabling a UI to edit each one separately to different states afterward. I actually thought the solution I'd proposed - creating and editing them as one unit - was already a short-cut (instead of having a higher-level abstraction). But yes, it would quick and easy.

> At least for the first version, the complexity would be much less.

The short-term work required would be less, not sure about the rest.
 
> Also we are not sure about two points: We don't know if people are interested on having a private app repository in multiple namespaces

I agree that it's hard to balance waiting for people to let us know they need something vs us anticipating what people will need (we had to do the same thing with the private registry support). I cannot see how, as a user in a multi-tenant environment with a private repository (say, team-a-private-charts), how I would not want to have that available in the namespaces my team uses. But yes, I agree it's a completely hypothetical use-case. I'm happy for us to wait and see what people request.

The work involved isn't so great (as the private rego support) to warrant needing to do this before hearing it requested. Let's move it to the backlog for now? WDYT?

> neither if they are interested on updating them once it's already working.

Might not be working: I might create it, try it and find I'd used the wrong secret, edit, add the secret and expect it to work in all namespaces, but in reality I'd have to either go through all N namespaces and manually add the secret to update the app repo, or go through all N namespaces and delete the app repo before creating a new one. I do think we can put some weight on our ability to think of use-cases :)

**Comment by ygqygq2** [comment]
In 1.10.0, the error ‘Charts not found’. Check it and confirm, please. I had rollback to use 1.9.2.

**Comment by absoludity** [comment]
> In 1.10.0, the error ‘Charts not found’. Check it and confirm, please. I had rollback to use 1.9.2.

Can you please create a separate issue and describe what you did? In particular, you mention that you're upgrading from 1.9.2, but is that with helm3 enabled or helm 2 etc. Thanks for the info!

**Comment by ygqygq2** [comment]
In 1.10.0, the error ‘Charts not found’. Check it and confirm, please. I had rollback to use 1.9.2. 

> > In 1.10.0, the error ‘Charts not found’. Check it and confirm, please. I had rollback to use 1.9.2.
> 
> Can you please create a separate issue and describe what you did? In particular, you mention that you're upgrading from 1.9.2, but is that with helm3 enabled or helm 2 etc. Thanks for the info! EDIT: also the output of `kubectl get po -n <kubeapps-namespace>` would be useful.

I've reinstalled it, then clear browser cache, it's working. :)

**Comment by andresmgot** [comment]
hey @ygqygq2, when upgrading from 1.9 to 1.10, the schema of the databases changes so the data related to charts is deleted and re-created with the new schema. That may take a few minutes depending on the connectivity, it should be fine after that.

**Comment by andresmgot** [comment]
RE: This issue. I am not arguing that just having UI changes is better, it's just simpler if we want to implement this in an easy way. In any case, it's true that the management of secrets won't be ideal.

I'll let you decide if the effort to implement this in the backend is worth the effort.

**Comment by absoludity** [comment]
Thanks, though I am keen to know what you think about the other points. Perhaps we can chat later.

**Comment by absoludity** [comment]
FTR: We discussed this and decided to leave it in the backlog for the moment, since it's not yet required (and people can explicitly add the same repo to multiple namespaces). When we do it, we should do it as per the description so it works the same for other api users (ie. perhaps harbor).

**Comment by Maellooou** [comment]
Hi,

If we have 200 namespaces it is a little bit restrictive and difficult to duplicate the code each time...

How can we facilitate that ?

Thanks

**Comment by andresmgot** [comment]
Hi @Maellooou, just to double check, do you want to have the repositories available in _all_ the namespaces? Because in that case you only need to deploy it in the namespace in which Kubeapps is deployed.

If you are talking about adding a namespace to 200 namespaces while the cluster has 400 then that's not supported through the UI at the moment, you would need some script that creates the `apprepositories` in the desired namespaces.

BTW, note for ourselves, we need to properly document the difference between namespaced and global apprepositories (I believe that's not documented), right @absoludity ?

**Comment by absoludity** [comment]
> If you are talking about adding a namespace to 200 namespaces while the cluster has 400 then that's not supported through the UI at the moment, you would need some script that creates the `apprepositories` in the desired namespaces.

I'd go a bit further and say the 200 for 400 case is not supported (as if you scripted this, you'd be creating 200 cron jobs all indexing the same repo, currently - which is why this issue exists). But as Andres said, if it is just that you want it to be available to all 200 namespaces then a single app repository for "All Namespaces" will work as it always has.


> BTW, note for ourselves, we need to properly document the difference between namespaced and global apprepositories (I believe that's not documented), right @absoludity ?

It's currently only documented in the docs for [private repositories](https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#per-namespace-app-repositories).  We could extract this to its own doc, when we decide how we'll approach app repositories support for OCIDist charts may be a good time (as we'll know how much it will change).

**Comment by andresmgot** [comment]
> It's currently only documented in the docs for private repositories.

Well, even there, we don't specify that app repositories created in the `kubeapps` namespace are available for everyone.

**Comment by absoludity** [comment]
> > It's currently only documented in the docs for private repositories.
> 
> Well, even there, we don't specify that app repositories created in the `kubeapps` namespace are available for everyone.

Right, it only says that the alias of "All Namespaces" will do that: "If you have cluster-wide RBAC for creating AppRepositories, you can still create an App Repository whose charts will be available to users in all namespaces by selecting "All Namespaces" when creating the repository."

**Comment by bsctl** [comment]
@andresmgot thanks for pointing me to this discussion. This is an amazing project. Thanks for sharing.

Quoting from this comment [comment](https://github.com/kubeapps/kubeapps/issues/2108#issuecomment-707580918)
> That's expected for namespaced resources. Namespaced app repositories are only available in the namespace they are installed in. This works the same way if alice creates a Kubernetes service in the namespace oil-development, it won't be available in oil-production even if the user has permissions to access both. You will need to either copy the app repository to the other namespace or make it global if you want to have it available for all namespaces.

Global app repositories from the namespace where `kubeapp` is installed, eg. `kubeapp-system`, are visible in UI for alice user, so alice can deploy apps in any of her namespaces even if she's not able to get. According to your statement above, global repositories in `kubeapp-system` namespace should not be visible to `alice` user because they are deployed in a namespace which alice does not own.

As cluster admin:

```
$ kubectl get apprepositories -A
NAMESPACE         NAME        AGE
kubeapp-system bitnami     36m.  <-- gloabal app repo is still a kubernetes namespaced resource but it is visible everywhere
foo-production    prova      16h
gas-development   fastcloud   16h
oil-production    esempio     16h
```

As alice user:

```
$ kubectl auth -n kubeapp-system can-i get apprepositories
no
```

Our use case is the following:

- we have multitenancy environment where a set of namespaces are assigned to a single user, eg. alice
- alice user has access to global app repo to deploy apps in any of her namespaces
- alice user reserves one of her namespaces, eg. `oil-kubeapp`, to deploy her own personal repo not accessible from other tenants
- alice wants to deploy an app in her namespace `oil-marketing` from her personal repo installed into `oil-kubeapp` namespace. So alice open the UI and set the namespace selector to `oil-marketing` namespace. She can see her personal repo installed into `oil-kubeapp` namespace since she has read/write permissions in that namespace.

**Comment by andresmgot** [comment]
> Global app repositories from the namespace where `kubeapp` is installed, eg. `kubeapp-system`, are visible in UI for alice user, so alice can deploy apps in any of her namespaces even if she's not able to get. According to your statement above, global repositories in `kubeapp-system` namespace should not be visible to `alice` user because they are deployed in a namespace which alice does not own.

Yes, in this case, apprepositories can be either global or namespaced (the same way that you can have Kubernetes `Roles` in a namespace and `ClusterRoles` globally, even though that's implemented in a slightly different way, you can find more info about this topic in this issue https://github.com/kubeapps/kubeapps/issues/2098).

> * alice wants to deploy an app in her namespace `oil-marketing` from her personal repo installed into `oil-kubeapp` namespace. So alice open the UI and set the namespace selector to `oil-marketing` namespace. She can see her personal repo installed into `oil-kubeapp` namespace since she has read/write permissions in that namespace.

This is a different use case. For the moment, any user with write access to a namespace will be able deploy apps from the repositories of that namespace, the only thing that can be limited with RBAC is the hability to create/modify/delete those apprepositories. This is something to evaluate for https://github.com/kubeapps/kubeapps/issues/2078

**Comment by bsctl** [comment]
Definitively this is a multi-tenant friendly approach. Forcing a tenant user to install the private app repo in each namespace she owns is not something we can propose. The same for asking the tenant user to install her own instance of Kubeapps. 

Please, consider to implement this use case. We're available to help and support. You can find more details on how we're implementing multi-tenancy in the [Capsule](https://github.com/clastix/capsule) project.

**Comment by absoludity** [comment]
>     * alice wants to deploy an app in her namespace `oil-marketing` from her personal repo installed into `oil-kubeapp` namespace. So alice open the UI and set the namespace selector to `oil-marketing` namespace. She can see her personal repo installed into `oil-kubeapp` namespace since she has read/write permissions in that namespace.

The main issue here that constrains us, is that the `AppRepository` is in the `oil-kubeapp` namespace *together with any secrets required to deploy apps in that repository* (such as image pull secrets required for images used in the apps of the repo). So yes, we could enable Alice to see apps from this repo, but when she goes to deploy an app, Kubeapps itself would need to make those secrets from the `oil-kubeapp` namespace available in the targeted namespace `oil-marketing`, which is a significant security issue, IMO (ie. Kubeapps overstepping it's boundary). You're solving this very issue with Capsule, it seems, providing a `tenant` with resources available in all namespaces for that tenant. OpenShift solves it with `Projects`, but Kubeapps doesn't know about either (and shouldn't by default).

I've not looked closely at Capsule so this is just a wild stab in the dark, but is it possible for you to define an `AppRepository` for the tenant that is automatically created in each namespace for that tenant?

**Comment by bsctl** [comment]
@absoludity any update on this?

**Comment by absoludity** [comment]
> @absoludity any update on this?

Sorry, not yet. It's still not clear to me how you're proposing to avoid leaking secrets required for a private-but-shared app repository. If Kubeapps allowed enabling an AppRepo for multiple other namespaces, the required image pull secrets need to be copied/duplicated/managed in those namespaces and that is not something Kubeapps can or should manage (copying secrets from one namespace to another).

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps.
