### ISSUE TITLE
Enhancement: Support for yaml/json object in Basic Form

### ISSUE THREAD

**Issue by zahid0** [vmware-tanzu/kubeapps#2007]
### Description:

Currently it is not possible to convert an object of values.yaml in the form if the names of the keys are not fixed. An easier workaround could be to render the object as yaml or json object in a text field inside the basic form. Suggestions and comments are welcome.

**Comment by andresmgot** [comment]
Hi @zahid0,

I am not sure I fully understand what you are proposing, can you put an example of input and what should be shown in the form?

**Comment by zahid0** [comment]
e.g.
The `values.yaml` file has
```
...
deployment:
  livenessProbe: {}
...
```

In the basic form I am trying to have a text area where user can provide yaml/json object for `deployment.livenessProbe` field. It is tricky to define all the possible keys of `livenessProbe` as form fields.

**Comment by andresmgot** [comment]
Have you tried setting the parameter in the schema as a textarea? Not sure if that would solve the issue but it's worth a try: https://github.com/kubeapps/kubeapps/pull/1488

**Comment by zahid0** [comment]
> Have you tried setting the parameter in the schema as a textarea? Not sure if that would solve the issue but it's worth a try: #1488

I did not work. With textarea, I'm getting the field value as string.

**Comment by andresmgot** [comment]
mmh, I see, so yes, we may need to support the `type: object, render: textarea` and handle it properly. Setting this up for grabs in case someone wants to contribute.

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps. Could be re-opened if more demand on this issue.
