### ISSUE TITLE
Investigate app repositories post 2.0 with hub support etc.

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#2078]
Currently AppRepositories are not only helm-centric but also helm2 centric, where an index.yaml indexed a collection of charts.

With Helm 3, there has been a push towards 'hubs' which can be searched (rather than an index.yaml) without providing a static list of available charts. Furthermore, charts are now installable with a direct URL, which is more inline with charts in an OCI repository.

Finally, if Kubeapps moves to generalise packaging formats (enabling plugins for different formats #2023) we want to plan how an "AppRepository" in the future can model "repositories" of different packaging formats, if at all (it may be more reason to follow helm and move towards searchable hubs generally).

As part of this investigation, we may want to pursue #1178 since we may not need a controller running necessarily anyway.

**Comment by ppbaena** [comment]
To be closed as there is a new approach for app repositories described in #4764
