### ISSUE TITLE
Use a simple form for creating an operator-managed custom resource

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#2100]
### Description:

CustomResources now [require an OpenAPI v3.0 validation schema (based on JSON Schema)](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) so that the API server can validate the resource. This should also enable us to present a simple form like we do for charts, when deploying an operator managed custom resource.

It would expose all the options on the custom resource's schema by default, but we may be able to enable indicating important fields or similar via the schema (we looked at this once before) if there's some agreement in the operator community.

**Comment by antgamdia** [comment]
Related to #2169

**Comment by ppbaena** [comment]
To be closed as it is not included in the current roadmap for Kubeapps.
