### ISSUE TITLE
Enable the internal pinniped-proxy to run with TLS certs 

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#2268]
### Description:

For the future case of Kubeapps running via pinniped-proxy, the internal requests proxied from our backend via the pinniped-proxy service should be on a secure channel. Currently requests from our backend to the pinniped-proxy service are without TLS (as we've not yet added TLS support to pinniped-proxy)

**Comment by antgamdia** [comment]
Have a look at the changelog, now kube-rs and its related projects have updated the HTTP client to make it more configurable. Perhaps useful for this issue: 
https://github.com/clux/kube-rs/blob/master/CHANGELOG.md#tls-enhancements

**Comment by antgamdia** [comment]
I've just come across this TODO in the code that perhaps is relevant for this issue:

https://github.com/vmware-tanzu/kubeapps/blob/85f72b22af7b29332a896a257f907caf88f2ab39/pkg/agent/httpConfigForCluster.go#L28-L31

**Comment by absoludity** [comment]
Yeah, it actually references this issue :P (usually create an issue when adding the todo). Thanks!

**Comment by antgamdia** [comment]
> Yeah, it actually references this issue :P (usually create an issue when adding the todo). Thanks!

@absoludity , did you have a chance to look at this //TODO when working on this issue and you left it unchanged for a reason? Or is it still something to do ? 
I just came across it now that I'm working on #5014 , but there's no rush.
