### ISSUE TITLE
Support proxying websocket connections in pinniped-proxy

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#2615]
This is a follow-up issue of the #2328 one.

Pinniped proxy is not proxying the ws connections; as a result, calls to the k8s API with `?watch=true` will fail. Once the _101 switching protocols_ HTTP status code is received, no more messages are routed by the pinniped-proxy.

The current solution has been just to force the trigger of the existing fallback mechanism in the front-end, that is, explicitly send a >400 status code when a 101 response is received from the server.

Whereas Kubeapps is working as is, the pinniped-proxy is still not able to handle ws connections.

**Comment by absoludity** [comment]
Interestingly, we can close this one now since we no longer use web sockets to poll for changes, but rather server-side events (via grpc streaming).
