### ISSUE TITLE
Evaluate code linters/formaters at server-side

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#2750]
Currently, we are relying on Husky to set git hooks (easily bypassable) to ensure our code follows certain style guidelines.
If we really want to enforce the usage of these tools, they should be at "server-side", for instance, using GitHub Actions: https://github.com/marketplace/actions/prettier-action

_Originally posted by @antgamdia in https://github.com/kubeapps/kubeapps/issues/2746#issuecomment-831299921_

**Comment by absoludity** [comment]
Currently we do this in other cases by checking it when building the image and failing the image build if there is lint. This allows blocking the PR from landing until it is fixed. GH actions could be used for the same, and as long as we're careful to ensure any failure in the GH action can be reproduced trivially locally, I'm fine with it.

**Comment by lopezator** [comment]
Have you considered using [golangci-lint](https://github.com/golangci/golangci-lint)? Along with actions as the op suggested.
