### ISSUE TITLE
pinniped-proxy should cache credentials for lifetime of credential request

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#2875]
### Description:

When initially creating the pinniped-proxy service, we had planned to cache the response of the token credential request and re-use it for subsequent requests.

As it is, it worked OK without this initially, but it is still overkill to be doing so for every request, and may be too slow in the future when pinniped tries to use the [certificate signing requests API](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/).

**Comment by viktor-haag** [comment]
Continuing the discussion we had in #2363, I have one more observation which might help. From what I could see, it seem that requests to **/api/clusters/default/api/v1** and **/api/clusters/default/api/v1/namespaces/<mynamespace>** always run into the 60s timeout. Aside from that, the response time of the other api calls is pretty inconsistant. If I directly hit one of the apis via the browser I get in extreme cases an instant response but am also as likely to run into the 60s timeout.

Aside from that, is there a combination of Kubeapps and Pinniped versions which you could recommend? I'd try a fresh install and check if the problem still persists there.

**Comment by antgamdia** [comment]
Thanks for your comments. It is something we have to investigate.

wrt your question: 
Kubeapps 2.3.2 is compatible with Pinniped >= v6.0.0 (latest is now 0.9.2)
Kubeapps 2.3.3 is compatuble with any Pinniped version (including < v6.0.0)

Apart from that, there are no extra requirements on the versions.
