### ISSUE TITLE
Implement pagination in the aggregated core APIs

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#3399]
It will require some changes in the Helm plugin, the core API and the UI.

From https://github.com/kubeapps/kubeapps/pull/3376#discussion_r706959608
> I think we already have one in mind, we just need to update the existing pagination (throughout) to use the number of items as the offset, rather than the number of pages, to then be able to update the next page tokens in the plugins.

**Comment by absoludity** [comment]
And the current asset svc helpers used by the core api, I think. In the sense that the current `GetPaginatedChartListWithFilters()` takes the `pageNumber` for an offset, even though it's converted to an item offset in the SQL. We just need to update the arg to be an item offset itself (should be trivial) and update the call-sites (or even delete the old call-sites if we don't need them :) ).

**Comment by absoludity** [comment]
The actual change (after the prep work) for this is done in #4694 and is working nicely, other than one issue with the UX creating multiple requests with different pagination options. I'll work on that next, which should be simple. Once done, the only other remaining work will be to apply the same change to the `GetInstalledPackageSummaries`.

**Comment by ppbaena** [comment]
This issue can be closed then.

**Comment by absoludity** [comment]
Hah - indeed. With these issues with many PR's, I avoid adding a `fixes #` to the PRs so they don't automatically close after each PR lands and need re-opening... but need to remember to close at the end :P
