### ISSUE TITLE
Kubeapps Helm AppRepository should support configurable sync interval

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#3661]
### Description:

Currently the interval with which the helm repositories referenced by an `AppRepository` are synced to the cache is configurable only for the apprepository controller itself (`Values.apprepository.crontab`), defaulting to 10minute intervals.

This should be exposed as an option on the AppRepository itself so that the crontab can be specified per repository, given that different repositories have different needs.

### Additional information you deem important (e.g. issue happens only occasionally):

This has come up because the new API will support an interval when creating an app repository (as supported by flux (and carvel?)). The Helm plugin/support can initially just not expose this in the UI and fail validation if specified to the API, so it's not urgent, but would be nice to have.

**Comment by antgamdia** [comment]
As of today, the new Repos API implementation for Helm does not support it:

https://github.com/vmware-tanzu/kubeapps/blob/3e3be06f24b865280fdf33c5381b3d1101dcfc75/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go#L54-L57

**Comment by ppbaena** [comment]
@antgamdia take a look at #5128 as it is related.
