### ISSUE TITLE
Select CronJob API group version dynamically

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#3846]
### Description:

As per #3832, we had to revert back some changes in the k8s API group we were using for creating the CronJobs and Jobs. 
Kubernetes 1.20 does not have the v1 version available yet... so it made some CI tests fail.

A solution could be to automatically discover the API group resource we use in the k8s client. This way, we would query "CronJobs" and we got back either "v1beta1" or "v1" depending on the target cluster we use.

Note that other k8s resources that are created in installation-time via Helm are already aware of the API changes (by means of helpers maintained by Bitnami).

**Comment by antgamdia** [comment]
Just a quick update: on April 2022, v1.22 [becomes `stable` in GKE](https://cloud.google.com/kubernetes-engine/docs/release-notes), meaning that we'll default our tests to match this version.

We can either hardcode it to `v1` or use the discovery client like in https://github.com/kubeapps/kubeapps/blob/main/cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go#L76, to discover which version (grv) should be using for talking to the API server.

**Comment by antgamdia** [comment]
Perhaps it is also relevant for #4695 ?

**Comment by antgamdia** [comment]
Whereas other Kubeapps components are actively using the Discovery API client, the AppRepository controller is not. However, currently, this is not that important anymore given two reasons:

- The CronJob API just was promoted to `v1`, so it is supposed to be stable from now on.
- This APIversion is nowadays widespread and, more importantly, Kubeapps is explicitly requiring a Kubernetes version > 1.21, where the `v1` version is available.

https://github.com/vmware-tanzu/kubeapps/blob/838df9102dd3c542a512a3587d767e1c6c807575/chart/kubeapps/Chart.yaml#L27

Therefore, I think the effort in dynamically selecting the API group is not worth it. Let's reopen it in case it becomes an issue for someone.

**Comment by mecampbellsoup** [comment]
Ah sorry @antgamdia I just saw this (coming from my comment [here](https://github.com/vmware-tanzu/kubeapps/pull/4775#issuecomment-1430448870))... how much work is it to copy the pattern of "dynamic versioning" like other parts of kubeapps does?

cc @aanthonyrizzo

**Comment by mecampbellsoup** [comment]
> 

By the way, was ` kubeVersion: ">=1.21.0-0"` set solely because of this change? Just curious.

**Comment by antgamdia** [comment]
> how much work is it to copy the pattern of "dynamic versioning" like other parts of kubeapps does?

Since we were investing more efforts in the backend refactor and developing other plugins (Flux, Carvel, etc), we couldn't address this issue. I guess it shouldn't be a huge deal: setting up a discovery client and querying the API group of the cronjob.

An alternative idea is what you mentioned in another issue: accept a new param in the binary to customize the API group `--cronjobApiGroup=v1beta1` or sth like that. Then it could be easily passed via chart values.yaml.

With one of these options I think we could remove the `kubeversion` limitation, because we set it to this value just for that reason :S

If you can jump in and send a PR, we'll be happy to assist you. Anyway, let's cc @absoludity to see what he also thinks.

**Comment by absoludity** [comment]
Yep, I'd be +1  for a simple param over the dynamic discovery. PR's welcome. I take it you weren't able to upgrade your cluster? Or are you just investigating both options?

**Comment by mecampbellsoup** [comment]
> Yep, I'd be +1 for a simple param over the dynamic discovery. PR's welcome. I take it you weren't able to upgrade your cluster? Or are you just investigating both options?

Sorry I missed this for a spell. Our upgrade to 1.21 is scheduled for March 15 or so. We have a 5,000 node cluster and thousands of tenants so upgrading is a very, very carefully planned process, so we always tend to lag behind significantly... 😞
