### ISSUE TITLE
Improvement: Upgrade Yaml module in Dashboard to major version 2.x

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#3913]
### Description:

Kubeapps is using v1 of the [JS module for Yaml](https://www.npmjs.com/package/yaml) at the moment of serializing the chart values yaml (e.g. [for the upgrade form](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/schema.ts#L123)).

Upgrading to major version 2 would allow us to set double quotes to modified Helm chart yaml values only, and not on keys. [See this related PR](https://github.com/kubeapps/kubeapps/pull/3898).

Serialization setting would go from the global (v1):
`YAML.scalarOptions.str.defaultType = Type.QUOTE_DOUBLE;`
to the serialization specific (allowed in v2):
```
defaultKeyType: 'PLAIN',
defaultStringType: 'QUOTE_DOUBLE'
```

[See Yaml module options](https://github.com/eemeli/yaml/blob/master/docs/03_options.md#tostring-options)

After a quick test: just upgrading the major version broke the compilation. So not a dependabot task.

### Steps to reproduce the issue:

[See this PR.](https://github.com/kubeapps/kubeapps/pull/3898)

### Describe the results you received:

Modified Helm chart values are currently shown between double quotes, both keys and values.

### Describe the results you expected:

Modified Helm chart values showing double quotes only on values and not keys.

**Comment by antgamdia** [comment]
Great, I agree, we should move to yaml v2 instead. Just wondering (given that you already 'had fun' with our yaml modules): do you think we should be using `js-yaml`? Perhaps we could replace everything with yaml v2

**Comment by castelblanque** [comment]
If I remember correctly, it seems that `js-yaml` has more features and is more generally spread in OSS, but e.g. doesn't keep comments when parsing Yaml files.
Therefore, by now I would suggest to continue getting the best out of both, and we can schedule for the future analyzing which one to use.
What do you think?

**Comment by antgamdia** [comment]
https://github.com/vmware-tanzu/kubeapps/pull/4605 will close this issue, I think?

**Comment by castelblanque** [comment]
@antgamdia Definetely yes, thanks!
I added a comment regarding `defaultKeyType` in #4605.
