### ISSUE TITLE
Make polling interval and timeout for Carvel new installations configurable

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#3975]
### Description:

#3970 adds a mechanism that waits for the CR to be created when installing a package.
It uses an interval and a timeout in seconds, hardcoded by now.
Make those two values configurable for the Carvel plugin specifically.

Related to #3852

### Describe the results you expected:

Being able to have default values for interval and timeout in seconds, but also being able to configure them through `values` when installing Kubeapps.

**Comment by antgamdia** [comment]
Closing as it is already using a plugin-level configurable timeout:

https://github.com/vmware-tanzu/kubeapps/blob/e6b54ce4bc2c4360c1434d4736b371e1cb499be1/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go#L637
