### ISSUE TITLE
Combination of repository name and namespace greater than 52 characters makes Cronjobs silently fail

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4061]
### Description:

When creating a repository which combination of name and namespace is > 52 characters, sync cronjob fails to be created.
Apprepository controller fails to create the cronjob due to K8s limitation to names of 52 chars, but error is not shown in Dashboard, only logs similar to:

```
E0111 14:41:46.734567       1 controller.go:253] error syncing 'test-long-namespace-name/my-long-named-repository-for-test': CronJob.batch "apprepo-test-long-namespace-name-sync-my-long-named-repository-for-test" is invalid: metadata.name: Invalid value: "apprepo-test-long-namespace-name-sync-my-long-named-repository-for-test": must be no more than 52 characters
```

User sees repo successfully created in Dashboard, but packages are never synced.

Problem can only be worked around by removing the repo and creating it again with a shorter name or in a shorter named namespace.

### Steps to reproduce the issue:

1. Log into Kubeapps
2. Create a new namespace with a long name (e.g. `test-long-namespace-name`)
3. Add a new repo with a long name (e.g. `my-long-named-repository-for-test`)
4. Check cronjobs created in K8s with `kubectl -n kubeapps get cronjobs`

### Describe the results you received:

Sync cronjob is never created. Packages from repo are never shown in catalog.

### Describe the results you expected:

Sync cronjob being created, or at least a message to the user preventing the creation of the repo.

Different options:

1. Limit the length of repository names. Given that K8s namespaces can be up to 63 characters, even with this limitation we could have the issue.
2. Limit the length of both namespaces and repositories names. This at least would reduce the probability of the issue happening.
3. Truncate the combined string of namespace+repo name. Due to the mentioned rule of 63 chars for ns, not adviced. 

### Additional information you deem important (e.g. issue happens only occasionally):

From [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/):
> The name must be no longer than 52 characters.

**Comment by absoludity** [comment]
> Different options:
> 
>     1. Limit the length of repository names. Given that K8s namespaces can be up to 63 characters, even with this limitation we could have the issue.
> 
>     2. Limit the length of both namespaces and repositories names. This at least would reduce the probability of the issue happening.
> 
>     3. Truncate the combined string of namespace+repo name. Due to the mentioned rule of 63 chars for ns, not adviced.

I don't think we can limit the length of any namespaces or repository names, since they can be created via `kubectl` outside of kubeapps anyway, so I believe something similar to (3) is the only option. We'd probably want to do something like concatenating the truncated names of both namespace and repo (perhaps with some hash suffix, not sure).

**Comment by absoludity** [comment]
I just spent 0.5 day debugging a CI failure that came down to this. Finally realised Cron Jobs weren't created when test ran, but were when I created the same app repo (with my own test name), until realised it was the length. *sigh*. I'm raising the priority :)

**Comment by castelblanque** [comment]
Yeah, agree. It is not a very common issue, but when it happens, it is difficult pinpoint the reason.

**Comment by antgamdia** [comment]
Perhaps it is also relevant for #4695 ?

**Comment by absoludity** [comment]
> Perhaps it is also relevant for #4695 ?

Well, I think we'll no longer need to worry about this issue once #4695 is implemented, since it will no longer be spinning up cron jobs etc.

**Comment by antgamdia** [comment]
> Well, I think we'll no longer need to worry about this issue once https://github.com/vmware-tanzu/kubeapps/issues/4695 is implemented, since it will no longer be spinning up cron jobs etc.

Ooops, I started looking into this issue before reading your comment 😅 . Well, given that it's gonna take some time to fully migrate to the new apprepo ctrl, I still think solving this issue is relevant.
I mean, even in our test cases we were using bad (>52 chars) names!
