### ISSUE TITLE
flux plugin: clean up old charts from chart cache after repo update

### ISSUE THREAD

**Issue by gfichtenholt** [vmware-tanzu/kubeapps#4115]
Documenting leftover items for flux plugin per Pepe's request so we can prioritize it against other work

This is a leftover item from #3899
@antgamdia said: 
"Think about an already cached repo, if the repo authors eventually sunset a given version and it gets removed from the index (case 1), what would happen then? What if a whole chart got removed (case 2)?
Let's suppose:

    (case 1): my-chart: v1, v2 --> then my-chart:v2
    (case 2): my-chart: v1, foo-chart: v1 --> then foo-chart: v1
"
case 1 is no problem but case 2 is an issue today. In both cases there will be an event 'repo XYZ' was modified. In handling this event, I will call SyncCharts(repo XYZ). Currently I just go through the most recent versions for every chart and add that. I don't delete any charts prior to that. So in case 1: you'll end up with my-chart:v2, same as before the update. In case 2, you'll end up with my-chart: v1, foo-chart: v1. The problem is my-chart: v1 does not belong in the cache anymore: it takes up precious space and the user might get details on a package which no longer exists. 

There is another thing that kind of complicates case 2: my-chart: v1 might have been added explictly to to chart cache by the user in a scenario where the entry was first evicted due to lack of space and then added due to user actually performing getAvailableChartDetail(my-chart: v1). So in that case, assuming my-chart: v1 is still a valid chart, do I delete it or leave it alone because its in the cache due to user's request?

**Comment by antgamdia** [comment]
FWIW, we have had this (case 2) problem for quite a long time. In fact, we had this old issue tracking it: https://github.com/kubeapps/kubeapps/issues/164

I'd personally opt for clearing this cache entry in case of doubt. If we do so, the worst-case scenario is a user waiting some seconds. Otherwise, a user would see an item that does no longer exists, which is a worse UX, IMHO.
