### ISSUE TITLE
Clean up integration container image

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4206]
### Description:

Integration [container image](https://github.com/kubeapps/kubeapps/blob/main/integration/Dockerfile) is still tailored to Puppeteer needs. Now that Kubeapps will be using Playwright, this image should get a review, mainly for checking dependencies used.

### Describe the results you expect:

Simple and lightweight image to run Playwright tests.

### Additional information:

See [this comment](https://github.com/kubeapps/kubeapps/pull/4185#discussion_r796665253) from #4185

**Comment by antgamdia** [comment]
I've been playing around with the deps as part of the usual process of upgrading deps before releasing and I have some comments:

- Playwright only officially supports Ubuntu-based images, meaning that running on debian (as we are doing) is unsupported.
- Bitnami images have recently transitioned to debian-11, so any (active) rolling tag is now pointing to debian-11 and new versions are only built for debian-11 and not debian-10
- Our current working Dockerfile is based on bitnami/node (debian-10)
  - We are installing several dependencies from the Puppeteer times, but, weirdly enough, it fails if we remove them. Well, it kinda makes sense given that some of them are required for a headless browser and rendering the video preview.
- Playwright offers an official image with everything installed: https://playwright.dev/docs/docker
- We can't move to debian-11 [as some dependencies are no longer available](https://github.com/puppeteer/puppeteer/issues/7822). Removing them also results in a building failure (related to webkit).
- I have tried running: https://github.com/microsoft/playwright/tree/main/utils/linux-browser-dependencies, but with no success. The script fails in a debian-based image.

As a result of all of this, we are stuck in the `bitnami/node:16.15.0-debian-10-r5` and we won't be able to upgrade anymore.

Given this image is just used internally for testing, I'd rather move to the official one provided by Playwright.

**Comment by absoludity** [comment]
> Given this image is just used internally for testing, I'd rather move to the official one provided by Playwright.

+1

**Comment by castelblanque** [comment]
> Playwright offers an official image with everything installed

Awesome, let's use that image!
