### ISSUE TITLE
dashboard to use RepositoriesService and implement API in helm and carvel plugins

### ISSUE THREAD

**Issue by gfichtenholt** [vmware-tanzu/kubeapps#4361]
This issue is a by-product of #3496
The core apis server now has support for RepositoriesService, which currently only has one API [AddPackageRepository](https://docs.google.com/document/d/1z03msZRGsRvcRaom-yrvEwIWcEfNy6fSA5Zg28gjYvA/edit#heading=h.u3lj7whdof7t)(). Only flux plugin currently implements the API. There will soon be more APIs defined for Reading, Updaing and Deleting of repositories
So:
1) The dashboard needs to be refactored to start to use the new Repositories Service. We should start with 'Add...' and move on to other operations as they become available
2) the Helm plugin and carvel plugins need to implement the AddPackageRepository() API (including the custom field handling the plugin specific stuff)

**Comment by ppbaena** [comment]
It is duplicated with issue #4764

**Comment by antgamdia** [comment]
+1 to close this one. I wrongly opened a new one, but given that all the conversation happened there, I'd close this one.

**Comment by absoludity** [comment]
Duplicate of #4764
