### ISSUE TITLE
Extra newlines in install notes Markdown rendering

### ISSUE THREAD

**Issue by dud225** [vmware-tanzu/kubeapps#4395]
### Description:

I'm noticing extra newlines in the Markdown rendering of the installation notes.

### Describe the results you received:

Here is the raw installation notes:
```
You can reach the REDACTED cluster *test* from the following URLs:
- REDACTED master node:
    - admin endpoint: REDACTED/test/vip
    - HTTP endpoints:
        - REDACTED/test/vip/check
        - REDACTED/test/vip/process
    - log files: REDACTED/test/vip/logs
```

but when rendered by Kubeapps there are additional line breaks:
![mardown](https://user-images.githubusercontent.com/17550475/157208439-912009b7-aefe-49b2-975d-e0089722df31.png)

Here is the raw HTML code:
![Capture d’écran de 2022-03-08 09-19-42](https://user-images.githubusercontent.com/17550475/157208475-737f0186-95d1-4714-9447-08698af83f4c.png)

**Comment by absoludity** [comment]
Should just be a style change (though we need to check why it's there and whether it affects other renderings, like the readme).

**Comment by antgamdia** [comment]
Hi,
this is an (undesired) side effect of what we did at https://github.com/vmware-tanzu/kubeapps/pull/4143:

> Non-markdown files might have some weird spacing as a result of an improper md parsing output. However, I've tried to keep a format as similar as possible.

If we wanted to change it, we would have to tweak a little bit the markdown renderer or its generated styles. However, I personally think we can leave it as is. If you want to give it a try, we are always open to contributions!

**Comment by antgamdia** [comment]
> However I'm not quite sure to understand what you mean by "non-markdown files"? The file here is in markdown format even though it's named NOTES.txt

I meant that the text in the `NOTES.txt` is not meant to be markdown even if it takes after an md document, especially when it comes to breaking lines. For instance, the `bitnami/apache` chart [NOTES.txt](https://github.com/bitnami/charts/blob/master/bitnami/apache/templates/NOTES.txt)

Once rendered using `ReactMarkdown`, the output (having removed any fancy CSS) is:

![image](https://user-images.githubusercontent.com/11535726/169848925-767f5b21-3d2d-45f9-bd9f-2c1c812453cd.png)

Note how the new lines are not being properly added.

So, as an initial approach, I just tweaked this behavior using the `withe-spaces: pre-wrap` ([read more](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)) property, but it can lead to undesired side effects as you described.

For instance, these extra break-lines:

![image](https://user-images.githubusercontent.com/11535726/169848303-a60f22ad-dd66-4e73-a323-57012dd6c6df.png)


However, I didn't want to give up so quickly, so after reading a while about the issue, it seems there is a `ReactMarkdown` plugin for dealing with break-lines 🎉 

After adding it, this is how it looks like:

![image](https://user-images.githubusercontent.com/11535726/169850819-fdc66a8e-f0dd-4a80-bec3-663a48622d67.png)
****

Also, the compatibility with other markdown installation notes remains the same:

![image](https://user-images.githubusercontent.com/11535726/169851179-ab9d4b31-c6a2-4033-9d9c-4e70af9767bc.png)


I'll send a PR soon. Anyway, if it doesn't really fit your needs, I highly encourage you to contribute and send a PR; we can work together until we find a solution looking nice!

**Comment by dud225** [comment]
Hello @antgamdia 
sorry for the delay I've just tested your commit and I confirm that it properly fixes the extra spaces I was getting, thanks a lot the output is now quite more tidy.
If you don't mind being picky there is a still a leading blank line on the first line as your screenshot shows that could be removed to be absolutely perfect :smile: (not a big deal I just wanted to report it)

**Comment by antgamdia** [comment]
Thanks for the feedback! Well... I couldn't resist and I fixed that extra line you mentioned https://github.com/vmware-tanzu/kubeapps/pull/4893 hahahaha
Next time, please feel free to deep dive into the Kubeapps code and send us a PR 😄

**Comment by dud225** [comment]
I've just tested your changed and I confirm that the output perfectly starts at the beginning of the box, thanks a lot.
> Next time, please feel free to deep dive into the Kubeapps code and send us a PR smile

OK OK I'll try, but that web area is definitely not my cup of tea :disappointed:
