### ISSUE TITLE
Add E2E tests for Flux

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4432]
### Description:

Add E2E test cases for Flux.

- CI event: Always

Same task for Carvel is covered in #4093 

Related to #4096

**Comment by antgamdia** [comment]
Related (or maybe even duplicated) to https://github.com/vmware-tanzu/kubeapps/issues/2881

**Comment by antgamdia** [comment]
We should at least add some very basic tests to prevent regressions like the one fixed at https://github.com/vmware-tanzu/kubeapps/pull/5218 😅

**Comment by ppbaena** [comment]
To be closed as duplicated in #2881
