### ISSUE TITLE
Generate protoc generated code automatically

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4434]
### Description:

Generate protoc generated code automatically as part of build process, and remove files from Git repo.

- Benefit: Getting rid of many files to maintain in the repo
- CI event: Always

Related to #4096

**Comment by antgamdia** [comment]
Maybe duplicated of #3908?

**Comment by castelblanque** [comment]
> Maybe duplicated of https://github.com/vmware-tanzu/kubeapps/issues/3908?

Closing in favor of #3908
