### ISSUE TITLE
[carvel] Package name or description not displayed on install details page

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#4448]
### Description:

While writing a CI test, I noticed that when viewing the package details, we're not currently displaying the name of the (available) package anywhere, only the name given to the installed package (eg. test-carvel here):

![gatekeeper-install-after-refresh](https://user-images.githubusercontent.com/497518/158535572-f7cf0db3-f52e-41c7-8f5a-e7876d1e0c60.png)

I don't see anything there identifying that `test-carvel` is an installation of the gatekeeper package. 

### Describe the results you received:

See screenshot

### Describe the results you expected:

I expected to see the package name "Gatekeeper" as well as its tagline "policy management".

**Comment by castelblanque** [comment]
You are right. Also with Helm, package name is not a "first class citizen" of the view. It might appear in the left hand side description (or not), and in the "Installation notes".

Maybe the view needs some restyling to include the available package info? As additional feature, clicking on it and the package icon might redirect to the available package details?

![image](https://user-images.githubusercontent.com/67455978/158543653-d5da0941-648f-4c80-9f19-43f867363786.png)

**Comment by antgamdia** [comment]
What about something like (using pkg id, but using the display name is another option) ?

![image](https://user-images.githubusercontent.com/11535726/169508390-1ceaa130-c915-4392-8881-54dbc9402eba.png)
![image](https://user-images.githubusercontent.com/11535726/169508700-14ab6448-b998-4021-99c7-bf7ad825c4ff.png)

**Comment by absoludity** [comment]
Haha - I'd just asked on the PR why you're not considering displayName - I see here that you are... still not sure why you decided against it though? Either way, I like the change :)
