### ISSUE TITLE
AppRepo sync jobs do not receive required imagePullSecrets

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#4470]
### Description:

This is a re-hash of #2144 which was fixed with #2156 but then, afaict, broken again with #3449 .

Similar to #2144, when deploying a helm chart from a private repo, with the global image pull secrets set correctly, the sync jobs sit in ImagePullBackoff due to an unauthorized error while pulling the image.

The issue appears to be that as part of the refactor in #3449 , `conf.ImagePullSecretsRefs` went from being set in the `main.go` after the command-line args had been parsed, to being moved to the `init()` function of the `root.go` command, which is executed when the module loads... *before* the command-line args are parsed. Since it relies on the value of one command-line arg in particular, `RepoSyncImagePullSecrets`, it is now empty always, even when the arg is set on the command-line.

This can be seen in the initial log of the command (formatted) where the resulting config has `RepoSyncImagePullSecrets` set from the cmd-line but `ImagePullSecretsRefs` is nil:
```
I0320 19:08:03.558376       1 root.go:48] apprepository-controller has been configured with: server.Config{
  ...
  RepoSyncImage:"registry.pivotal.io/tac-for-tanzu-advanced/containers/kubeapps-asset-syncer@sha256:3b21158f689cc8c297d44e5debb13a7e3661acc9ff3f773e648e80ce03917bd0",
  RepoSyncImagePullSecrets:[]string{"my-secret"},
  ImagePullSecretsRefs:[]v1.LocalObjectReference(nil),
  RepoSyncCommand:"/asset-syncer",
  ...
}

```

Since we don't have any unit-tests for this functionality currently (nor integration - we test private repos in integration, but not private images in private repos), we didn't notice the regression. We should ensure unit tests are added to avoid future regression.

### Steps to reproduce the issue:

See #2144

### Describe the results you received:

See #2144

### Describe the results you expected:

See #2144

### Additional information you deem important (e.g. issue happens only occasionally):

I haven't checked, but suspect the other values set in the same place will be the same, ie #3400.

**Comment by antgamdia** [comment]
Ooops, sorry :S , such a pity we didn't notice.
Thanks for the investigation and the detailed explanation. 100% agree, we should have had unit-tests there preventing us from this regression.

**Comment by absoludity** [comment]
Sorry - not linking to PRs to imply it's someone's fault - just for context. We need to improve our unit tests so making changes like that are safer. Let's do it with the fix :)
