### ISSUE TITLE
Migrate Kubeapps repo to vmware-tanzu org

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#4532]
### Description:

We need to move [kubeapps/kubeapps](https://github.com/kubeapps/kubeapps) under [vmware-tanzu](https://github.com/vmware-tanzu) org in github. 

### Acceptance criteria:

- [x] Kubeapps repo is migrated to [vmware-tanzu](https://github.com/vmware-tanzu)
- [x] CI is updated and passing again (Note: works with the GH redirects without issue https://github.com/vmware-tanzu/kubeapps/pull/4537 )
- [x] Kubeapps docs and links are updated with no reference to kubeapps organization (Changes in the kubeapps repo in #4532, changes for the upstream chart which will get merged to a repo too at https://github.com/bitnami/charts/pull/9634)
- [x] Kubeapps project is available
- [x] Release process for bitnami charts is updated pointing to the migrated repo in [vmware-tanzu](https://github.com/vmware-tanzu)
- [ ] Announce migration in Kubeapps slack channel

### Additional information:
N/A

**Comment by absoludity** [comment]
Regarding the docs, note that GitHub manages the redirects for us, which is nice. ie. [https://github.com/kubeapps/kubeapps/blob/main/docs/tutorials/getting-started.md](https://github.com/kubeapps/kubeapps/blob/main/docs/tutorials/getting-started.md) goes through just fine.

**Comment by absoludity** [comment]
Also, people in the community are are going to be redirected already, so I'll just do a pre-announcement in our slack and Pepe or someone can follow-up with more details when ready.

**Comment by absoludity** [comment]
@ppbaena Everything is done here except the announcement in the kubeapps channel. I'll leave that to you since you did all the hard work for this :)

**Comment by ppbaena** [comment]
Announced [here](https://kubernetes.slack.com/archives/C9D3TSUG4/p1649427760764779 ), so this issue can be closed.
