### ISSUE TITLE
kubeappsapi internal configmap is missing the namespace

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/kubeapps#4571]
### Description:
When deploying what helm renders for kubeapps, `deployment/kubeapps-internal-kubeappsapis` remains on ContainerCreating state. Looking at the loog it's because it can not mount one of the volumes for `kubeapps-internal-kubeappsapis-configmap` and it's because it does not have the namespace set as can be seen in the template sources:
https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/templates/kubeappsapis/configmap.yaml#L3-L4

### Steps to reproduce the issue:

1. Render the yaml that helm would generate:
```
helm template -n kubeapps --create-namespace \                                                                                                ─╯
    --set packaging.helm.enabled=true \
    --set packaging.carvel.enabled=true \
    --set kubeops.enabled=false \
    --set postgresql.architecture=standalone \
    --set postgresql.persistence.size=1Gi \
    --set frontend.replicaCount=1 \
    --set dashboard.replicaCount=1 \
    --set kubeappsapis.replicaCount=1 \
    --set apprepository.globalReposNamespaceSuffix=-globalrepos \
    --set apprepository.crontab="* */2 * * *" \
    --set ingress.enabled=true \
    --set ingress.hostname=kubeapps.127.0.0.1.sslip.io \
    --set frontend.service.type=ClusterIP \
    --atomic --dry-run --debug \
    --version 8.0.7 kubeapps bitnami/kubeapps
```
2. Add the CRD
3. Deploy
4. See the status for the `deployment/kubeapps-internal-kubeappsapis`

### Describe the results you received:
It stays on ContainerCreating

### Describe the results you expected:
It should deploy

### Version of Helm, Kubeapps and Kubernetes:
Chart 8.0.7

**Comment by absoludity** [comment]
Thanks @jorgemoralespou . Yeah, our current e2e tests are for the helm installation of Kubeapps only. I'll fix this in the upstream bitnami chart so it gets released quickly.
