### ISSUE TITLE
Kubeapps-Sync failing during Getting Started with `dial tcp 127.0.0.1:443: connect: connection refused`

### ISSUE THREAD

**Issue by browser-bug** [vmware-tanzu/kubeapps#4595]
### Description:

Doing a basic deployment on a Minikube environment I'm getting the following error on the `apprepo-kubeapps-sync-bitnami` pod creation:
```
Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp 127.0.0.1:443: connect: connection refused
```

### Steps to reproduce the issue:
Deploying a single node cluster with minikube `minikube version: v1.24.0`:
```
minikube start
```

Following the exact steps described in the Getting Started section:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
kubectl create namespace kubeapps
helm install kubeapps --namespace kubeapps bitnami/kubeapps
```

### Describe the results you received:

`apprepo-kubeapps-sync-bitnami` going in `CrashLoopBackOff` with error:
```
kubectl -n kubeapps logs apprepo-kubeapps-sync-bitnami-27500250--1-pgnl7
Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp 127.0.0.1:443: connect: connection refused
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
kubeapps	kubeapps 	1       	2022-04-15 11:02:39.603810736 +0200 CEST	deployed	kubeapps-8.0.10	2.4.4
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Charlie17Li** [comment]
@browser-bug 
I also get this problem with KindD now, have you solved this?

**Comment by Charlie17Li** [comment]
> @browser-bug I also get this problem with KindD now, have you solved this?

But I waited for 10 minutes, it works now

```
E0418 05:55:52.983219       1 utils.go:801] failed to import icon, name=kubeapps: Get "https://raw.githubusercontent.com/kubeapps/kubeapps/main/docs/img/logo.png": dial tcp 0.0.0.0:443: connect: connection refused
I0418 06:05:35.734554       1 sync.go:102] Repository synced, shallow=false
I0418 06:05:35.738236       1 sync.go:111] Stored repository update in cache, repo.URL= https://charts.bitnami.com/bitnami
I0418 06:05:35.738287       1 sync.go:112] Successfully added the package repository bitnami to database
```

**Comment by absoludity** [comment]
Hi there @browser-bug .

```
Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp 127.0.0.1:443: connect: connection refused
```

It's not clear to me why the sync is trying to access charts.bitnami.com on the loop-back address 127.0.0.1? Does it resolve eventually for you the way @Charlie17Li describes?

**Comment by browser-bug** [comment]
> Hi there @browser-bug .
> 
> ```
> Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp 127.0.0.1:443: connect: connection refused
> ```
> 
> It's not clear to me why the sync is trying to access charts.bitnami.com on the loop-back address 127.0.0.1? Does it resolve eventually for you the way @Charlie17Li describes?

Unfortunately it does not. I think it's terminating eventually but accessing the catalog from the UI shows the following (probably because the package repository couldn't be added to database?):
```
An error occurred while fetching the catalog: Invalid GetAvailablePackageSummaries response from the plugin helm.packages: rpc error: code = Internal desc = Unable to fetch chart categories: pq: relation "charts" does not exist. 
```

**Comment by absoludity** [comment]
Yes, that the error we would expect if a sync job hasn't yet been able to run. I haven't yet setup a 1.24 kind/minikube cluster (hmm, though later in your description the output of kubectl shows 1.22 for the server?), but before one of us tries to reproduce something specific, is it possible that your cluster egress does not allow network traffic externally? You could check from another pod, such as a frontend one, with:

```
kubectl -n kubeapps exec deployment/kubeapps -c nginx -- curl -sI https://charts.bitnami.com/bitnami/index.yaml
HTTP/2 200 
content-type: text/plain
content-length: 13504716
...
```

**Comment by browser-bug** [comment]
> Yes, that the error we would expect if a sync job hasn't yet been able to run. I haven't yet setup a 1.24 kind/minikube cluster (hmm, though later in your description the output of kubectl shows 1.22 for the server?), but before one of us tries to reproduce something specific, is it possible that your cluster egress does not allow network traffic externally? You could check from another pod, such as a frontend one, with:
> 
> ```
> kubectl -n kubeapps exec deployment/kubeapps -c nginx -- curl -sI https://charts.bitnami.com/bitnami/index.yaml
> HTTP/2 200 
> content-type: text/plain
> content-length: 13504716
> ...
> ```

Yes I can confirm that the minikube cluster is running on a `1.22` version. Should I upgrade/downgrade it and test again? And probably the issue is related to the ogress as you suspected since this is the output I get:
```
 ❯ kubectl -n kubeapps exec deployment/kubeapps -c nginx -- curl -sI https://charts.bitnami.com/bitnami/index.yaml                                                                     09:40:14 
command terminated with exit code 7
```

**Comment by absoludity** [comment]
> Yes I can confirm that the minikube cluster is running on a `1.22` version. Should I upgrade/downgrade it and test again?

No, that's fine, I was just confused between version of minikube (1.24) and the cluster (1.22).

> And probably the issue is related to the ogress as you suspected since this is the output I get:
> 
> ```
>  ❯ kubectl -n kubeapps exec deployment/kubeapps -c nginx -- curl -sI https://charts.bitnami.com/bitnami/index.yaml                                                                     09:40:14 
> command terminated with exit code 7
> ```

OK, so yes, that'll be the cause of the sync failing as well then.

> 
> Although I cannot really find how to investigate what causes that exit code nor how to handle the outgoing traffic on minikube (which actually should be open by default).

If it were me, I'd debug by starting with a fresh minikube, checking if it has egress, if not, debug there (without any kubeapps) until it's working. Maybe https://minikube.sigs.k8s.io/docs/handbook/network_policy/ has more info (I'm not currently using minikube, so not sure I can help more than that).

Let us know how you go!

**Comment by browser-bug** [comment]
Sorry for the delayed response, I've recently come across a similar issue again and I found out I could just inject a custom nameserver (e.g. `8.8.8.8`) for DNS resolution inside the minikube cluster (I've posted the answer here aswell https://stackoverflow.com/posts/72156457

So basically no egress rules on network policies are needed, just start the minikube cluster with a custom `resolv.conf`:

```
```
mkdir -p ~/.minikube/files/etc
echo nameserver 8.8.8.8 > ~/.minikube/files/etc/resolv.conf
minikube stop
minikube start
```

I've verfied that kubeapps deploys instantly as expected and everything works.

**Comment by absoludity** [comment]
Excellent, thanks for circling back and updating here for anyone else who hits a similar issue @browser-bug
