### ISSUE TITLE
How to use Kubeapps in an air gapped environment

### ISSUE THREAD

**Issue by Ramshield** [vmware-tanzu/kubeapps#4631]
Hi,

We use Kubeapps in an air gapped environment. We'd love to use the Bitnami repository, or any other repository.
This is ideal for our customers who have no/very limited experience with YAML files. 

However since we are in an air gapped environment all the Helm charts use an image from the internet which gets pulled. 
So the user has to edit this in Kubeapps when deploying an application. 

Is there any way to automatically give a default different repository?
It would be wonderful to automate step 4 (https://tanzu.vmware.com/developer/guides/kubeapps-private-repo/#step-4-customize-your-helm-chart-and-push-it-to-your-private-harbor-registry) for our customers so they don't have to edit anything, and we can keep the public repositories as default as possible. 

Thank you!

**Comment by absoludity** [comment]
Hi there.

So it sounds like you've already got [Kubeapps running in your offline environment](https://github.com/vmware-tanzu/kubeapps/blob/main/docs/howto/offline-installation.md) and have already mirrored images and made the charts available on an internal helm repository, right?

If so, I think the closest thing to help you is the global settings for a chart. Most/all charts in the Bitnami catalog do have a single place to update the repository. For example, if I take a look at the postgresql chart, it has a [Global section where you can set the registry](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L1-L12) (but same repository names will be used). For charts with dependencies, this will automatically be used for the dependent charts too.

But we don't have a way for that to be set automatically in Kubeapps itself. You'd need to change the content of the charts when you mirror them, or subscribe for a private [VMware Application Catalog](https://tanzu.vmware.com/application-catalog).

It would be possible to have a setting in Kubeapps which tried to update some configured default values for all charts during install. If that would interest you, we can update this issue to target that feature.

**Comment by Ramshield** [comment]
Hi @absoludity thank you very much for your quick reply. 

The global settings for a chart is what our users currently use. But this is sometimes still too difficult for some users, and have to be applied every time. It would be very useful for us to have an overwrite on that setting for ALL charts.

I'm not sure if this is within the scope of Kubeapps, or if you are aware of a solution outside of Kubeapps?
If we are an edge case I'm not sure if it is worth the time of developers to implement this or if we need to find a solution on our own. But if someone is willing to add this feature, it would be really useful!

**Comment by absoludity** [comment]
> 
> I'm not sure if this is within the scope of Kubeapps,

Not really, no - in that this info is part of the published Helm chart. What I'd suggest is:

> or if you are aware of a solution outside of Kubeapps?

If you are already mirroring all the charts into your air gapped environment, whatever automation you have to do that could be *updating* the charts as it mirrors them, setting the global setting to your default (if that's allowed by the license, haven't checked).

> If we are an edge case I'm not sure if it is worth the time of developers to implement this or if we need to find a solution on our own. But if someone is willing to add this feature, it would be really useful!

I believe that [VMware App Catalog](https://tanzu.vmware.com/application-catalog) is a for-pay tool for doing this kind of thing - providing people with a custom Helm (or other) app repository customised to their needs.
