### ISSUE TITLE
There is a problem with this package: this package has missing information, some actions might not be available.

### ISSUE THREAD

**Issue by DanPhonovation** [vmware-tanzu/kubeapps#4636]
I haven't looked at my kubeapps deployment in awhile. Needed to deploy a few things with ease but noticed no matter what repo I go to or what helm chart I deploy I get the error

```
There is a problem with this package: this package has missing information, some actions might not be available.
```

Could anyone kindly point me to a possible cause?

 - Kubernetes version 1.19

Kubeapps Version:
App Version: 2.4.3
Package Version: 7.8.9

**Comment by antgamdia** [comment]
I'd have to look into it, but from memory, this error message is yielded when the package was installed from a repository that no longer exists. As a result, Kubeapps can't fetch any package metadata and you only can delete the package.

Have you removed/edited the repository from which you installed the package? If so, try to add it again. If not, let's see if we can repro the error.
In the meanwhile, here's the code returning that message, in case you want to skim it: https://github.com/vmware-tanzu/kubeapps/blob/main/dashboard/src/actions/installedpackages.ts#L134

**Comment by DanPhonovation** [comment]
Followed upgrade troubleshooting instructions. (Wipe and reload). Seemed to go away. *shrug*
