### ISSUE TITLE
kubeapps not working with postgres on a 2nd install

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#4689]
Kubeapps does not work reliably when re-installing.

perform the following steps:
    1 - helm install kubeapps bitnami/kubeapps --create-namespace --namespace=kubeapps
    2 - check that kubeapps can display apps (kubeapps should be listed)
    3 - helm uninstall kubeapps -n kubeapps
    4 - helm install kubeapps bitnami/kubeapps --create-namespace --namespace=kubeapps
    5 - check whether kubeapps can display apps
    6 - helm uninstall kubeapps -n kubeapps
    7 - kubectl delete ns kubeapps
    8 - helm install kubeapps bitnami/kubeapps --create-namespace --namespace=kubeapps
    9 - check whether kubeapps can display apps

On the first install (step 2), kubeapps will display the kubeapps app as expected.
On the second install (step 5), kubeapps will report an error when viewing application about not being able to connect to postgres
On the third install (step 9), kubeapps will display the kubeapps app as expected.

From what i could understand/observe from testing, when uninstalling kubeapps, there are PVCs that are not deleted and left in the namespace. When installing a second time, the PVCs will be reused (i.e. the underlying PVs).

Installations on steps 1 and 4 are using the default values and thus the password will be automatically generated each time. The Persistent Volumes seem to be somehow bound to the password, making the PV non-reusable.
If the installations on step 1 and 4 are made by providing a password, the issue does not manifest.

because of the stateful nature of postgres, it makes sense for the PVCs to not be deleted by default. on the other hand, kubeapps is using postgres only as a cache, so deleting the PVCs should not be an issue.

at a minimum, this should be documented in an "uninstall" section of the chart's readme.

**Comment by absoludity** [comment]
Thanks @dlaloue-vmware , yes, this is not restricted to Kubeapps but any Helm chart that stores a password in a stateful set. You can read more about it in the bitnam charts FAQ at:

https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases

I've been thinking about this recently after it's affected a couple of people. My preference would be that our Kubeapps chart override the default postgres options with the following (given that it is only used as a cache, as you mentioned):

```
postgresql:
  architecture: standalone
  primary:
    persistence:
      enabled: false
```

This would:
1. Ensure Kubeapps' postgres only uses a single instance (no replication), and
2. Ensure Kubeapps' postgres does not use persistence (unless explicitly configured by the user)

What do you think?

**Comment by dlaloue-vmware** [comment]
i think that would be a good change.

btw, regarding item 1, the postgres chart is using standalone as the default, so i am not sure why kubeapps was overriding it to replication. but i agree that standalone should be the default for kubeapps.

**Comment by absoludity** [comment]
> i think that would be a good change.

Great. We should do that upstream at the bitnami/charts .

> btw, regarding item 1, the postgres chart is using standalone as the default, so i am not sure why kubeapps was overriding it to replication. but i agree that standalone should be the default for kubeapps.

Yeah, I don't either - I'd assumed it was the postgres default. Checking the history of the upstream chart, there's a comment (now removed) for the older replication option (pre postgres 11 chart) which said:

>    @param postgresql.replication.enabled Enable replication for high availability

Not sure if that high availability for the cache is worth the extra resources in this instance. So yes, let's switch that to use the default and update the persistence to false.

**Comment by antgamdia** [comment]
> What do you think?

Big +1 to that proposal. Related (somehow) to #4695. I'm always deploying with `architecture: standalone` as we don't really have those exigent requirements on the DB performance. Users can later opt-in to this feature and override the value.
Also, disabling the persistence to PVC would erase plenty of upgrading issues... and re-fetching a repo (even if it is a big one like BAC) is not that big deal.

Notwithstanding, moving away from PostgreSQL towards a unified cache layer as in #4695 seems a better long-term option to me.

**Comment by absoludity** [comment]
Great, since we have agreement, I've fixed it in https://github.com/bitnami/charts/pull/10228

As it turns out, our chart still intended to disable persistence, but that setting was still using the pre-postgresql 11 chart location (validation of values.yaml would help here?)

**Comment by castelblanque** [comment]
> validation of values.yaml would help here?

That would be awesome!
Is it possible with Helm to validate values for a dependency or is it something done by Bitnami?

**Comment by antgamdia** [comment]
> That would be awesome!
> Is it possible with Helm to validate values for a dependency or is it something done by Bitnami?

AFAIK, it is not possible (yet). Once the json schemas become generated for every chart, we would be able to analyze the conformity to the schemas. I'm sure it would be a great addition for the bitnami/charts repo.

**Comment by antgamdia** [comment]
> Great, since we have agreement, I've fixed it in [bitnami/charts#10228](https://github.com/bitnami/charts/pull/10228)

Thanks for the fix! Closing as it got merged upstream.

**Comment by absoludity** [comment]
Hmm, closing issues remove them from the board before we review. That's fine if we don't want to review them during our iteration meetings, but otherwise I think we should leave them open for now (close them when we review), or, update the github project so closed issues are not removed until archived. Thoughts?

**Comment by ppbaena** [comment]
As we have checked in the standup, this issue is still in the Done column.

**Comment by absoludity** [comment]
Yeah sorry - I thought I'd seen a similar issue disappear from Done when I closed it the other week, but hadn't rechecked very well with this one. Sorry for the noise :)
