### ISSUE TITLE
Use redis for caching repo and chart data in helm instead of postgresql

### ISSUE THREAD

**Issue by gfichtenholt** [vmware-tanzu/kubeapps#4695]
Per team meeting Tuesday May 10 2022, I was asked to look into replacing postgresql as a mechanism for helm plug-in with redis. That way it will be consistent with flux support in kubeapps which already uses redis as a caching mechanism.  This is going to be a **long running task**, while I make small incremental changes that hopefully in the end will obsolete the need for postgresql. For the short term I plan not to remove any existing postgresql code, but rather introduce a global bool flag and guard the new redis-related changes by this flag. That way we have some time where both approaches are available, so we can compare, benchmark, look for consistency of results, etc.

**Comment by gfichtenholt** [comment]
...interesting. I created a Redis flavor of assetManager, instrumented all the calls from asset-syncer and I am noticing this pattern for bitnami repo (see attached log
[foo.txt](https://github.com/vmware-tanzu/kubeapps/files/8685562/foo.txt)
) This is pretty crazy! Every version of every chart ever some dating back 10 years is loaded into cache. That's more than 14K charts, and I can only guess many hundreds MB of data, which sits mostly unused. It's not too bad when cache is a disk, but IMO not acceptable when cache is in-memory. The point being that this work will likely involve not just replacing postgresql util code with redis equivalent, but a bit of redesign of the way things work at a higher level.

**Comment by gfichtenholt** [comment]
Guys, 
as I was racking my brain thinking of how to safely refactor asset-syncer, assetsvc and helm plugin 
to switch away from the model of "dump everything in the universe we know about this repo into cache" to more
of a "dump just enough state to be able to load other things as needed/on demand" (this is how flux plugin works) without breaking any existing code, @dlaloue-vmware gave me an idea which I really like:
Rather than trying to shoe-horn a different paradigm into existing code, create a new kind of 
apprepository-controller. It would manage AppRepository CRDs differently than our existing apprepository-controller does, but similarly to the way flux's source-controller works. In one sentence its job would be to download the index yaml to some local virtual storage, update the status field on AppRepository CR accordingly (something Dimitri brought up a long time ago) and that's it. (i.e. NOT launch any jobs for asset-syncer to process). I don't really know whether it's possible/kosher to have 2 concurrent controllers running and managing the same CR, so I propose we would have a install-time flag to decide which controller to deploy, something like "use-redis-cache-in-helm" By default, until this work is completed, the flag would be false, so one should not see any of my changes. They would have to explictly set the flag to true when doing helm install to get the new code to run. 
Benefits:
 1) I think this is the least diruptive model. While I do this I leave existing code alone, to work exactly as it does today, obviously except the helm plugin at the very end and even those changes would be guarded by a flag. 
 2) this is a more declarative model, advocated by k8s authors, rather than the imperative model implemented by current apprepository-controller, so some may argue it's more k8s-native
 3) At the end asset-syncer and assetsvc become obsolete and can be removed (along with postgres)
 4) I get to write a CR controller from scratch using the latest frameworks created and actively maintained for people writing controllers (https://github.com/kubernetes-sigs/controller-runtime). Much more pleasant than refactoring old code 
 5) I can always refer to https://github.com/fluxcd/source-controller/blob/main/controllers/helmrepository_controller.go to see how flux does something
 6) Once the new controller is ready, in helm plugin I should be able to reuse NamespacedResourceWatcherCache and ChartCache I wrote for flux plugin pretty much AS IS - it'll just be watching for changes on a different kind of CR

Thanks
Greg

**Comment by absoludity** [comment]
> ...interesting. I created a Redis flavor of assetManager, instrumented all the calls from asset-syncer and I am noticing this pattern for bitnami repo (see attached log ) This is pretty crazy! Every version of every chart ever and their corresponding files (think of >100K of data/version) some dating back 10 years is loaded into cache. That's more than 14K charts, and I can only guess many hundreds MB of data, which sits mostly unused.

Yeah, from the start of the project I think it's just done what `helm update` (now `helm repo update`) did, since it was on disk. Since I joined the project, I do remember one update someone did so that the initial scan didn't include all the history - enabling the catalog to be displayed quickly, before a second complete scan begins (which takes a lot longer).

> It's not too bad when cache is a disk, but IMO not acceptable when cache is in-memory.

+1

>  The point being that this work will likely involve not just replacing postgresql util code with redis equivalent, but a bit of redesign of the way things work at a higher level [foo2.txt.gz](https://github.com/vmware-tanzu/kubeapps/files/8685715/foo2.txt.gz).

Yep, makes sense.

**Comment by absoludity** [comment]
> Guys, as I was racking my brain thinking of how to safely refactor asset-syncer, assetsvc and helm plugin to switch away from the model of _"dump everything in the universe we know about this repo right now into cache"_ to more of a _"dump just enough state to be able to load other things later as needed/on demand"_ (this is how flux plugin works) without breaking any existing code,

Sounds great.

> @dlaloue-vmware gave me an idea which I really like:
> 
> Rather than trying to shoe-horn a different paradigm into existing code, create a new kind of apprepository-controller. It would manage AppRepository CRDs differently than our existing apprepository-controller does, but similarly to the way flux's source-controller works. In one sentence its job would be to download the index yaml to some local virtual storage, update the status field on AppRepository CR accordingly (something Dimitri brought up a long time ago) and that's it. (i.e. NOT launch any jobs for asset-syncer to process).

As long as that means we can return a cached catalog - great. I assume it'd then pull out the readme and values when the details are requested, as you do for flux now. Sounds good (and I think the slight performance penalty on fetching the details the first time is a good trade-off for being able to do it sensibly and not for every chart etc.) 

> I don't really know whether it's possible/kosher to have 2 concurrent controllers running and managing the same CR,

Nope.

> so I propose we would have a install-time flag to decide which controller to deploy, something like "use-redis-cache-in-helm" By default, until this work is completed, the flag would be false, so noone should see any of my changes. They would have to explictly set the flag to true when doing helm install to get the new code to run.

+1 - yes that sounds great, so we can switch to it when ready without impacting the current setup. It may get tricky if you need to change the custom resource itself, but perhaps not.

> Benefits:
> 
>     1. I think this is the least disruptive model. While I do this I leave existing code alone, to work exactly as it does today, obviously except the helm plugin at the very end and even those changes would be guarded by a flag.
> 
>     2. this is a more declarative model (updating CR's Status field with the latest developments, like indexation succeeded or indexation failed, etc), advocated by k8s authors, rather than the imperative model implemented by current apprepository-controller. Some may argue it's more k8s-native

+100 - it's been one of the weird things about the app repository controller from the start - it doesn't control app repositories and their status, rather starts sync jobs etc.

> 
>     3. At the end, asset-syncer and (non UX-related parts of) assetsvc become obsolete and can be removed (along with postgres)

\o/

> 
>     4. I get to write a CR controller from scratch (yay!) using the latest frameworks created and actively maintained for people writing controllers (https://github.com/kubernetes-sigs/controller-runtime). Much more pleasant than refactoring old code

Haha - yes, that'll be both worthwhile for you and the project imo.

> 
>     5. I can always refer to https://github.com/fluxcd/source-controller/blob/main/controllers/helmrepository_controller.go to see how flux does something
> 
>     6. Once the new controller is ready, in helm plugin I should be able to reuse NamespacedResourceWatcherCache and ChartCache I wrote for flux plugin pretty much AS IS - it'll just be watching for changes on a different kind of CR

Excellent!

> 
>     7. The use case of redis evicting cache entries to make room for new ones is automatically handled by (6). With the current design, the problem of having to load entries into cache at any time is diffucult to solve
> 
> 
> Drawbacks:
> 
>     1. it does introduce some backward incompatibility, e.g. `AppRepository.Spec.SyncJobPodTemplate` would no longer be supported. It actually smells like a leaky abstraction in the first place. Maybe that's a reason to bump version v1alpha1 to v1alpha2.

I'd bump it either way in your version?

> Don't know enough about kubeapps customer base to tell how much this is actually used

It is used by users (before my time, but I'd guess it was a user request initially), you can search closed issues to see the few requests that have come in over the past couple of years, but it's purpose is to ensure that any pod that is created for a new sync job has certain properties (taints to run on a particular node, labels, or even environment variables such as `http_proxy` etc.).

So we could check the use-cases that have come up in issues, but I'd think this wouldn't be necessary in your solution since the actual controller is doing the work (rather than creating k8s jobs with new pods etc.), so these extra labels, taints and/or env vars details would be add the controller itself, I'd think? Worth checking, but I think it should be OK.

One other downside would be the introduced delay to display details, but as above, I totally think that's acceptable given the alternative.

Thanks Greg!

**Comment by gfichtenholt** [comment]
Thanks, Michael

**Comment by castelblanque** [comment]
Great idea @gfichtenholt and @dlaloue-vmware !

> it does introduce some backward incompatibility, e.g. `AppRepository.Spec.SyncJobPodTemplate`

Is it the same case for `ResyncRequests`?

And does it mean I no longer need to implement that `SyncJobPodTemplate` in the Helm repository API WIP in #4662 ?
Not a big deal, but it would be wasted time? Although it would mean that such repository API wouldn't be available until Greg's work is done :confused:

**Comment by gfichtenholt** [comment]
> And does it mean I no longer need to implement that `SyncJobPodTemplate` in the Helm repository API WIP in #4662 ? Not a big deal, but it would be wasted time? Although it would mean that such repository API wouldn't be available until Greg's work is done 😕

I don't have the definitive answer to that. Probably, yes. Let me just point out this is the CURRENT proposal. It doesn't mean it won't change, unexpected thing always show up. Also, let me point out that solution, as proposed, has very large scope (think 2-3 months of work).
