### ISSUE TITLE
kubeappsapis readme doc uses wrong rest api path

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#4700]
the readme file kubeapps-apis.md uses the wrong apis path in its curl example.

for example is shows 
    curl -s http://localhost:8080/core/plugins/v1alpha1/configured-plugins 
instead of 
    curl -s http://localhost:8080/apis/core/plugins/v1alpha1/configured-plugins

**Comment by antgamdia** [comment]
Thanks for noticing it; let's fix it in #3953 , where we are moving the docs files. Otherwise, we are gonna get conflicts near soon😅
