### ISSUE TITLE
OSM onboarding for Kubeapps

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#4757]
**Summary**
Perform all defined steps to include Kubeapps as a product in OSM tool and register new releases.

**Background and rationale**
To improve security and comply with VMware open source standards in Kubeapps, both the open source and third party software packages must be reviewed for use by OSPO.

**Description**
To comply with OSPO the following steps must be performed:

- [x] Register Kubeapps as a product in OSM tool
- [x] Create a new release for Kubeapps (2.4.6)
- [x] Report all dependencies and packages in the release
- [x] Include files (licensing and open_source text) in Kubeapps repo

**Acceptance criteria**

- [x] Kubeapps product registered in OSPO.
- [ ] Next release approved in OSPO tool.

**Additional context**
Up to now, it was only registered in OSPO our official chart released by Bitnami Application Catalog.

**Comment by ppbaena** [comment]
Requested to register Kubeapps as a product in OSM: [kubeapps 2.4.6](https://osm.eng.vmware.com/oss/#/product-requests/3312)

**Comment by ppbaena** [comment]
On premise offering created in [Release Hub](https://releasehub.eng.vmware.com/products/2601)

**Comment by ppbaena** [comment]
Waiting for release hub to sync with OSM tool so we can start reporting package dependencies to OSM associated to the release. Weekly sync in Release Hub is requested.

**Comment by ppbaena** [comment]
Kubeapps product and release have been created in OSM. Next step to report all dependencies.

**Comment by ppbaena** [comment]
osspi scan bom launched to run BOM scan against Kubeapps. Reported dependencies to OSM.

**Comment by antgamdia** [comment]
As discussed offline, we need to re-trigger the reporting process once we run the "release-process" workflow (which updates several dependencies throughout our code)
