### ISSUE TITLE
Remove/migrate UI calls to Kubeops

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#4785]
**Summary**

As part of the analysis performed for #4764, I noticed we still have several calls to the kubeops endpoints that should be properly migrated to the Resources plugin or the PackageRepositories plugin.

**Background and rationale**

Once we get rid of the Kubeops calls for managing repositories, there is no reason for us to maintain Kubeops. Therefore, any remaining call should be migrated.

**Description**

First, further analysis of what we have to delete or migrate has to be carried out.

**Acceptance criteria**

- [x] We have identified which are the calls to the Kubeops service.
  - Done at https://github.com/vmware-tanzu/kubeapps/pull/5023
- [ ] The current calls to Kubeops have been properly migrated to the corresponding services.
- [ ] Kubeapps continues to work after scaling Kubeops's deployment down to 0 replicas.

**Additional context**

Note that, first, we have to finish the implementation of the Helm-plugin Repositories API.

**Comment by absoludity** [comment]
Kubeops currently has the `kubeops-ns-discovery` `ClusterRole` which gives access to list the namespaces of a cluster (before they are filtered by user RBAC). We'll need to move this cluster role and apply it to the kubeapps-apis service account so that we can use it from the resources plugin for similar functionality.

**Comment by antgamdia** [comment]
For now, I have indentified: 

- https://github.com/vmware-tanzu/kubeapps/blob/main/dashboard/src/shared/Kube.ts
  - [ ] getResource
  - [ ] getAPIGroups
  - [ ] getResourceKinds
  - [ ] canI
- https://github.com/vmware-tanzu/kubeapps/blob/main/dashboard/src/shared/Namespace.ts
  - [ ] list
- https://github.com/vmware-tanzu/kubeapps/blob/main/dashboard/src/shared/Operators.ts
  - All of them, but it should be carried out at #4920

**Comment by castelblanque** [comment]
> For now, I have indentified

After some investigation:
- `getResource` is not used and thus has been removed (pending PR)
- `getAPIGroups`/`getResourceKinds` are direct K8s APIs calls unrelated to Kubeops. They are only used when operators are enabled.
- `canI` will be moved into resources plugin (pending PR)

The only remaining endpoint in Kubeops will be a simple “give me this operator logo” ([this line](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeops/internal/httphandler/http-handler.go#L216)). Kubeops only makes a subsequent K8s API call, so no added value. Given that the call is related to operators, it will be moved to be done directly from the frontend (k8s api calls are allowed when using operators).
