### ISSUE TITLE
[Repository] add credential info to repository summary

### ISSUE THREAD

**Issue by dlaloue-vmware** [vmware-tanzu/kubeapps#4866]
It would be useful to show in the summary page whether a repository is public or private.

The PackageRepositorySummary structure should be updated to indicate whether the repository is public/private.

**Comment by absoludity** [comment]
Does private here mean that the repository uses a secret to access the repository content, or that the repository contains packages that use image pull secrets for their related images? Just keen to capture exactly what should be understood by a client here.

**Comment by dlaloue-vmware** [comment]
This is in relation to whether Auth information were provided as part of configuring the repository.
It does not provides details as to how those credentials are used by the plugin / packaging controller - it might be plugin specific.
