### ISSUE TITLE
Build E2E tests for the new package repository API UI

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#4876]
**Summary**
Build E2E tests for the new package repository API UI when work in #4764 is finished.

**Description**
Build tests in Playwright that test each feature offered by the new UI built for the package repository API that makes use of all three plugins existing.

**Acceptance criteria**
E2E tests that cover the new UI for the package repository UI.

**Comment by antgamdia** [comment]
Done at https://github.com/vmware-tanzu/kubeapps/pull/5115 as there are _E2E tests that cover the new UI for the package repository UI._
The rest of the plugin-oriented e2e tests will be tracked independently
