### ISSUE TITLE
Netlify reporting "failed" status main's pushes when hitting a cached version

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#4878]
_Converting into an issue since I haven't found yet a quick way to do it._

Currently, the Netlify builds often fail because there is no new content added to the website. Since it has a cache, it compares the cached version with the PR's (to main) content and given there are no changes, no deploy action is performed.
That is a great feature since we save some building cycles (in the free plan they are limited), but, as a result, it reports a failed status.
The only real downside of it is that we have the "failed" badge on top of our readme.

Alternatives:

1. Find a solution to force builds without cache (+ no failed status; - more building time consumed)
2. Remove the badge and ignore the building status (+ non-visible failed status; - no badge)
3. Stay happy with the failed badge as is
4. Release website changes in a separate branch (I wouldn't go with this option)

Personally, I'd go with 2, but see what you think.

**Comment by absoludity** [comment]
Can we use the https://docs.netlify.com/configure-builds/ignore-builds/ option to avoid even starting a build if nothing has changed in that directory? (not sure why that wouldn't be happening by default).

Seems like the "Cancelled \ne Failed" is a known issue - https://answers.netlify.com/t/no-content-change-deploy-failed-notification/64345/7
