### ISSUE TITLE
Getting an error on the Catalog Page: Invalid GetAvailablePackageSummaries Unable to fetch chart categories: pq: relation "charts" does not exist.

### ISSUE THREAD

**Issue by EvanCarroll** [vmware-tanzu/kubeapps#4882]
**Describe the bug**
I'm getting error on the catalog page of KubeApps on a fresh install,

> An error occurred while fetching the catalog: Invalid GetAvailablePackageSummaries response from the plugin helm.packages: rpc error: code = Internal desc = Unable to fetch chart categories: pq: relation "charts" does not exist.

I wrote this problem up here: https://devops.stackexchange.com/q/16107/18965

**To Reproduce**

I wrote every instruction down verbatim. Each block was just copied and pasted into the terminal.

The instructions can be found here https://devops.stackexchange.com/a/16109/18965

**Expected behavior**

Previously, I'm sure I followed these instructions and everything just worked.

**Screenshots**

Screenshots can be found here https://devops.stackexchange.com/q/16107/18965
**Desktop (please complete the following information):**

All of this is brand new. The instructions assume a fresh install and install the latest versions of everything.

**Comment by antgamdia** [comment]
Hi @EvanCarroll ,

thanks for reporting it. This is an error yielded when the database is not ready yet, so the cache hasn't get populated.
We'd need more information about the Kubeapps version you're running (we introduced a couple of changes in the chart related to the PostgreSQL database). Also

**Comment by EvanCarroll** [comment]
```
$ kubectl -n kubeapps logs deploy/kubeapps-internal-kubeappsapis                                                          
Found 2 pods, using pod/kubeapps-internal-kubeappsapis-8476cc6d6c-vhrj7
I0608 20:59:30.570994       1 root.go:37] kubeapps-apis has been configured with: core.ServeOptions{Port:50051, PluginDirs:[]string{"/plugins/helm-packages", "/plugins/resources"}, ClustersConfigPath:"/config/clusters.conf", PluginConfigPath:"/config/kubeapps-apis/plugins.conf", PinnipedProxyURL:"http://kubeapps-internal-pinniped-proxy.kubeapps:3333", GlobalReposNamespace:"kubeapps", UnsafeLocalDevKubeconfig:false, QPS:50, Burst:100}
I0608 20:59:30.913734       1 server.go:139] +helm using custom packages config with {3 3 3} and timeout 300
I0608 20:59:30.914981       1 plugins.go:151] Successfully registered plugin "/plugins/helm-packages/helm-packages-v1alpha1-plugin.so"
I0608 20:59:31.262460       1 plugins.go:151] Successfully registered plugin "/plugins/resources/resources-v1alpha1-plugin.so"
I0608 20:59:31.262641       1 packages.go:49] Registered name:"helm.packages"  version:"v1alpha1" for core.packaging.v1alpha1 aggregation.
I0608 20:59:31.263938       1 server.go:158] Starting server on :50051
```

And, 

```
kubectl -n kubeapps get pods
NAME                                                          READY   STATUS    RESTARTS   AGE
kubeapps-internal-apprepository-controller-86864b5cd5-ztzmr   1/1     Running   0          9m24s
kubeapps-internal-kubeops-7cb44885d8-7692b                    1/1     Running   0          9m24s
kubeapps-internal-kubeops-7cb44885d8-5rmgp                    1/1     Running   0          9m24s
kubeapps-internal-kubeappsapis-8476cc6d6c-vhrj7               1/1     Running   0          9m24s
kubeapps-internal-kubeappsapis-8476cc6d6c-h725f               1/1     Running   0          9m24s
kubeapps-internal-dashboard-85f66744dd-jw6k2                  1/1     Running   0          9m24s
kubeapps-internal-dashboard-85f66744dd-r2pjq                  1/1     Running   0          9m24s
kubeapps-9f7f58d48-g89hz                                      1/1     Running   0          9m24s
kubeapps-9f7f58d48-zr2f4                                      1/1     Running   0          9m24s
kubeapps-postgresql-0                                         1/1     Running   0          9m24s
```

**Comment by EvanCarroll** [comment]
@antgamdia also, just to be clear this happens on a fresh install, for me. I delete everything as documented at https://devops.stackexchange.com/a/16109/18965

I'm assuming that is sufficient to be a fresh install?

**Comment by EvanCarroll** [comment]
@antgamdia nothing different, would you like to partner on it with a Discord screenshare?

https://discord.gg/QMkbUsUrmR

**Comment by absoludity** [comment]
Can you paste the output of:

```
kubectl -n kubeapps exec deployment/kubeapps -- curl -sI https://charts.bitnami.com/bitnami/index.yaml
```

This will show if there are (still?) any issues reaching the bitnami repository from a pod in your cluster. If there are, then the networking issue needs to be investigated. If there are no issues but the sync is still failing, we need to investigate why.

**Comment by EvanCarroll** [comment]
@absoludity this is all I get,

```sh
command terminated with exit code 6
```

So I guess it's a networking issue, any pointers on trouble shooting it?

**Comment by absoludity** [comment]
Best source IMO is to work through the relevant parts of https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/
