### ISSUE TITLE
Move kubeapps' cache of expiry-aware values upstream

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#4934]
**Summary**

During the last iteration, part of the work for #2875 involved creating a cache implementation for values which know themselves when they expire (see #4899). This code could exist in the upstream library that we used, and given that the [author of the library agrees it would be valuable for others there](https://github.com/jaemk/cached/issues/115), we should move it there instead.

**Background and rationale**

We benefited from the upstream library and can give some benefit back.

**Acceptance criteria**

- Kubeapps does not contain its own cache implementation but rather uses the upstream one.

**Comment by absoludity** [comment]
I've done the implementation in a local branch of the upstream project. Waiting now on approval from the VMware Open Source Project Office to contribute. Remaining steps:

1. Once I have approval, submit the change upstream and work with reviewer to land
2. Find out when a new release of the library can be made
3. Once released, update our Kubeapps code to use it, removing the implementation in Kubeapps.

**Comment by absoludity** [comment]
Upstream change PR https://github.com/jaemk/cached/pull/118

**Comment by absoludity** [comment]
Released in upstream in https://crates.io/crates/cached/0.35.0

**Comment by ppbaena** [comment]
Thanks! Are you updating our codebase to use the upstream code?

**Comment by absoludity** [comment]
Yep, will do.

**Comment by ppbaena** [comment]
Hi Michael, let me know if you can add this to the code so we can include it in next release for July. No problem if not possible, just to plan it.

Thanks.

**Comment by absoludity** [comment]
Sorry Pepe. Yes, happy to commit to do this in the next iteration.
