### ISSUE TITLE
Document onboarding in Kubeapps through TCE

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#4935]
**Summary**
Write some documentation to guide the usage on Kubeapps in TCE.

**Background and rationale**
Kubeapps has recently been added to TCE addons repo, so it is necessary to improve the onboarding process for Tanzu users and guide them through Kubeapps.

**Description**
Update Kubeapps documentation by adding a new tutorial / how-to about Kubeapps on TCE.

**Acceptance criteria**
Documentation to reduce the adoption curve for Tanzu Community Edition users available at Kubeapps github repo (and website).

**Additional context**
Revisit how other addons in TCE provide documentation for the onboarding through TCE.

**Comment by antgamdia** [comment]
As @vrabbi mentioned, we need to document several use cases:

- Unmanaged clusters (using LoadBalancer somehow) 
- Managed clusters
  - Public clouds (using LoadBalancer) 
  - Private clouds (we can't use LoadBalancer, check NSX networking)

Any help here is extremely welcomed :P
