### ISSUE TITLE
Document release process in Package for Kubeapps repo

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#4937]
**Summary**
Share knowledge and document the release process for Kubeapps as a Carvel package.

**Background and rationale**
Nowadays, knowledge is concentrated in one person and need to be documented and shared with rest of the team

**Description**
Schedule transfer knowledge sessions with @absoludity to understand the release process for Kubeapps as a Carvel package and the distribution into TCE. Document this process so anyone in the maintainers team could perform a release. Define the criteria to release Carvel packages to be consistent/complimentary with Helm chart strategy in Kubeapps.

**Acceptance criteria**

- [x] Release for Kubeapps as a Carvel package is shared with Kubeapps maintainers team
- [x] Release for Kubeapps as a Carvel package is documented

**Comment by absoludity** [comment]
I have put some documentation for the release process in the CONTRIBUTING.md of the repo:

https://github.com/vmware-tanzu/package-for-kubeapps/blob/c93797d5084b84a77cd52fb9069ca5f3dfc3f586/CONTRIBUTING.md?plain=1#L5-L48

but let me move it to a separate doc and fill it out more with more detail and Rafa and I will verify and update until it works fine for him as well.

**Comment by absoludity** [comment]
I've extended the existing documentation, filling in any gaps I could see, in https://github.com/vmware-tanzu/package-for-kubeapps/pull/22 . @castelblanque and I can then work together to run through the process on his machine and see if anything is missing.
