### ISSUE TITLE
oidc Google oauth2

### ISSUE THREAD

**Issue by TaiKamilla** [vmware-tanzu/kubeapps#4938]
When trying to set the Google oauth2 you end with this error
<img width="598" alt="image" src="https://user-images.githubusercontent.com/15035750/174633682-a19a3193-952b-45b4-9ef6-6986dfef2096.png">

**Comment by antgamdia** [comment]
It seems you're using a wrong value for the field `authProxy.scope` as Google does not support `groups`. The default value the chart sets is `scope: "openid email groups"`. You have to override it and remove it by doing something like : `helm install [...] --set authProxy.scope="openid email"`

**Comment by TaiKamilla** [comment]
Thanks for the tip!
But I still have a second error
After login with google, it sends me back to the login page and wants me to login again so it becomes an infinite loop

This is the code I am using
```
helm install kubeapps bitnami/kubeapps \
  --namespace kubeapps \
  --set authProxy.enabled=true \
  --set authProxy.provider=oidc \
  --set authProxy.scope="openid email" \
  --set authProxy.clientID=mykey.apps.googleusercontent.com \
  --set authProxy.clientSecret=mysecret \
  --set authProxy.cookieSecret=$(echo "not-good-secret" | base64) \
  --set authProxy.extraFlags="{--cookie-secure=false,--oidc-issuer-url=https://accounts.google.com}"



kubectl create --namespace default serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
kubectl port-forward -n kubeapps svc/kubeapps 3000:80
```

**Comment by smerschjohann** [comment]
@TaiKamilla you must be able to authenticate with that google auth token against your Kubernetes Cluster. Did you configure the apiserver accordingly? (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

**Comment by antgamdia** [comment]
I'd recommend having a look at the [OIDC debug guide](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-debugging/). It seems the token is properly retrieved, but it is not authorized by your API server.

Also, as a side comment, @smerschjohann, [Pinniped](https://pinniped.dev/) is a great project for avoiding configuring the API server's OIDC flags. Just install the Pinniped CRDs, configure an authenticator and that's all.

More info at https://kubeapps.dev/docs/latest/tutorials/kubeapps-on-tkg/step-1/ and https://kubeapps.dev/docs/latest/howto/oidc/using-an-oidc-provider-with-pinniped/
