### ISSUE TITLE
helm direct plugin returns incorrect response for GetAvailablePackageVersions

### ISSUE THREAD

**Issue by gfichtenholt** [vmware-tanzu/kubeapps#4950]
Reproduction steps:
1) install kubeapps in your kind cluster with helm direct plugin. I did it via
```
helm upgrade kubeapps ./chart/kubeapps --install --namespace kubeapps --create-namespace \
         --set "packaging.helm.enabled=true" \
         --set "packaging.flux.enabled=false" \
          --wait
```
after a pull yesterday (6/23/22)
2. from https://stefanprodan.github.io/podinfo wget these files
podinfo-6.0.0.tgz podinfo-6.0.3.tgz podinfo-5.2.1.tgz podinfo-6.1.6.tgz podinfo-6.1.5.tgz podinfo-6.1.4.tgz podinfo-6.1.3.tgz (total of 7)
3. with a web browser login to demo.goharbor.io [admin/Harbor12345]
4. create a public project 'test-oci-1'
5. in terminal window `helm registry login -u admin -p Harbor12345 demo.goharbor.io`
6. for each file in (2) 
`helm push $file oci://demo.goharbor.io/test-oci-1`
7. 
`kubectl port-forward --namespace kubeapps service/kubeapps 8080:80`
create helm-direct OCI registry:
`curl -i 'http://localhost:8080/api/v1/clusters/default/namespaces/default/apprepositories' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Authorization: Bearer $token' -H 'Origin: http://localhost:8080' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8080/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw '{"appRepository":{"name":"podinfo","repoURL":"https://demo.goharbor.io/test-oci-1","authHeader":"Basic YWRtaW46SGFyYm9yMTIzNDU=","authRegCreds":"","type":"oci","description":"","customCA":"","syncJobPodTemplate":{},"registrySecrets":[],"ociRepositories":["podinfo"],"tlsInsecureSkipVerify":false,"passCredentials":false}}'
`
8. 
```
kubectl -n kubeapps port-forward svc/kubeapps-internal-kubeappsapis 8080:8080
grpcurl -plaintext -d '{"available_package_ref": {"context": {"cluster": "default", "namespace": "default"}, "plugin": {"name": "helm.packages", "version": "v1alpha1"}, "identifier": "podinfo/podinfo"}}' -H "Authorization: $token" localhost:8080 kubeappsapis.core.packages.v1alpha1.PackagesService.GetAvailablePackageVersions

{
  "packageAppVersions": [
    {
      "pkgVersion": "6.1.4",
      "appVersion": "6.1.4"
    },
    {
      "pkgVersion": "6.1.6",
      "appVersion": "6.1.6"
    },
    {
      "pkgVersion": "6.1.3",
      "appVersion": "6.1.3"
    },
    {
      "pkgVersion": "5.2.1",
      "appVersion": "5.2.1"
    },
    {
      "pkgVersion": "6.0.3",
      "appVersion": "6.0.3"
    },
    {
      "pkgVersion": "6.0.0",
      "appVersion": "6.0.0"
    }
  ]
}

```
this list is not correct. 6.1.5 is missing and 6.1.3 should not be in the response

**Comment by castelblanque** [comment]
Good catch!
That seems an issue in the ordering of versions?
We have all our tests providing values correctly sorted, which might not be the case on runtime.
[See here.](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go#L31)

A solution could be to sort versions first in [PackageAppVersionsSummary](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go#L57).
The `semver` module we are using has a sorting method.

**Comment by castelblanque** [comment]
Couldn't resist to find out why the issue was happening 😄 
#4952

**Comment by ppbaena** [comment]
Thanks both! Great catch from @gfichtenholt and nice to see @castelblanque jumping into it. Nice work team!
