### ISSUE TITLE
Changing Context in AppView leads to unlimited retries

### ISSUE THREAD

**Issue by smerschjohann** [vmware-tanzu/kubeapps#4960]
**Describe the bug**
If one is inside an AppView e.g. https://kubeapps.localhost/#/c/default/ns/dev/apps/helm.packages/v1alpha1/redis and selects another namespace or cluster using the context menu, the URL is rewritten to e.g. https://kubeapps.localhost/#/c/default/ns/default/apps/helm.packages/v1alpha1/redis. If that chart is not available, Kubeapps retries to retrieve that info without stopping.

**To Reproduce**
See above

**Expected behavior**
Either fail after a few retries or switch to AppListView on cluster/context change. The latter would be better I think.

**Desktop (please complete the following information):**

- Version: 2.4.5
- Kubernetes version [e.g. 1.21.10]: 1.23.6
- Package version [e.g. Helm 3.2, carvel-imgpkg 0.28.0] irrelevant

**Comment by absoludity** [comment]
Thanks @smerschjohann 

> **Expected behavior**
> Either fail after a few retries or switch to AppListView on cluster/context change. The latter would be better I think.

+1 for the latter (specifically, on cluster/context change from certain views - in other cases, such as viewing an installed package we'd want to go back to the installed app list)
