### ISSUE TITLE
Specify imgPullSecrets in Helm's Repos API by its values, not only by secret name

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5015]
_Extracted from https://github.com/vmware-tanzu/kubeapps/issues/4764_

**Summary**
 Add a way to specify img pull secrets in the helm plugin for kubeapps-managed secrets. 

**Background and rationale**
Currently, the former UI supports both approaches, but the API only allows setting the secret manually. This has led to disabling the e2e test nº 03/10.

**Description**
Add a way to set the imgPullSecret (a Helm plugin's custom detail) by its value, not only by secret name.

**Acceptance criteria**

- The Helm repos API is able to be passed imgPullSecret values and it creates the secret under the hood.
- The UI has enabled back the functionality to pass the values (a toggle button has been disabled to prevent users from using it)

**Additional context**

N/A

**Comment by antgamdia** [comment]
>  Are you aware of any reason why old UI only allows to select one secret while the old API allowed to pass an array of secrets?

Unfortunately, I'm not. As far as I am concerned, one was only able to specify a single pullsecret name. This was pretty misleading as the frontend code also allowed passing an array under the hood, but the user only could select a single one, which is odd.

At this point, given that it has been implemented that way for a long time (with no incoming issue) I'd say it is safe to assume that the pullsecrets field is just a string and not an array (and change it back in the API and proto file), no?

**Comment by castelblanque** [comment]
> I'd say it is safe to assume that the pullsecrets field is just a string and not an array

Totally agree. Although in Kubernetes the `imagePullSecrets`, we can always extend to an array in the future if needed.
