### ISSUE TITLE
Review and adapt existing Kubeapps documentation to comply with new guidelines

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5024]
**Summary**
Review and adapt existing Kubeapps documentation to comply with new guidelines defined in #5019.

**Background and rationale**
New guidelines for documentation have been added to Kubeapps in #5019 and PR #5020.
This newly required way of writing may differ from the existing documentation.

**Description**
This tasks consists in adapting/rewriting existing Kubeapps documentation to the new standard, for example:
from `Under the hood, kapp-controller will create...` in [this document about Carvel packages](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/tutorials/managing-carvel-packages.md?plain=1#L145), to `Internally, ``kapp-controller`` will create...`.

**Acceptance criteria**
Documentation is rewritten meeting the new guidelines, where needed.

**Comment by ppbaena** [comment]
**Summary:**

- [X] General documentation
- [ ] Tutorials (WIP)
- [ ] How-to guides
- [ ] Background
- [ ] Reference

**Comment by ppbaena** [comment]
Working on How-to guides:

- [ ] [Access Control](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/access-control.md)
- [ ] [Basic Form Support](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/basic-form-support.md)
- [ ] [Custom App View Support](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/custom-app-view-support.md)
- [ ] [Custom Form Component Support](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/custom-form-component-support.md)
- [ ] [Dashboard](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/dashboard.md)
- [ ] [Multi-cluster Support](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/deploying-to-multiple-clusters.md)
- [ ] [Offline Installation](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/offline-installation.md)
- [ ] [Private Package Repository](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/private-app-repository.md)
- [ ] [Syncing Package Repositories](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/syncing-apprepository-webhook.md)
- [ ] [Using an OIDC provider with Pinniped](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/howto/OIDC/using-an-OIDC-provider-with-pinniped.md)

**Comment by ppbaena** [comment]
I've created specific issues for updating pending documentation to be updated and aligned to work in progress in different components (forms, multi-cluster, architecture, etc.).
