### ISSUE TITLE
Dashboard/React: "restore defaults" button does not reset BasicDeploymentForm input fields

### ISSUE THREAD

**Issue by dionysius** [vmware-tanzu/kubeapps#5025]
**Describe the bug**
When using the "restore defaults" button in a helm chart deployment page the input fields don't get reset. The sliders and checkboxes (at least those who hide other fields) do get reset. The Changes Tab are getting correctly reset though, unsure about the YAML tab - needs checking as well. Same behavior in Brave and Firefox.

**To Reproduce**

1. Go to Catalog
2. Select any Helm Chart to deploy (which offers the BasicForm, e.g. Joomla!)
3. Click Deploy
4. Fill out some form fields including sliders and checkboxes
5. See that in the Changes Tab the changes are listed
6. Go back to the Form Tab
7. Click "Reset defaults" button

**Expected behavior**
The form is reset as if I would refresh the page with Ctrl+R.

**Actual behavior**
The form is only partly reset. Sliders and checkboxes seem to correctly reset, but all text or password fields keep the input data, while the Changes tab doesn't list any.

**Screenshots**

Preparation:
![Screenshot_20220705_153621](https://user-images.githubusercontent.com/1341084/177343083-93071e8f-a62b-4265-ac6a-527804adb17d.png)

After Pressing "Reset defaults":
![Screenshot_20220705_153648](https://user-images.githubusercontent.com/1341084/177343114-7f2a9195-1b90-4ff8-b0fa-a9331ad2e26d.png)
![Screenshot_20220705_153655](https://user-images.githubusercontent.com/1341084/177343160-a6780fd3-b68f-4538-9231-d339a39b2399.png)

**Desktop (please complete the following information):**

- Kubeapps version:
```
$ helm list -A
NAME    	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2022-07-05 15:21:49.695211917 +0200 CEST	deployed	kubeapps-9.0.3	2.4.6      
```
- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s1", GitCommit:"53f2d4e7d80c09a7db1858e3f4e7ddfa13256c45", GitTreeState:"clean", BuildDate:"2022-06-27T21:48:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Browser versions:
```
$ dpkg -l | grep -E "(brave-browser|firefox-esr)"
ii  brave-browser                                               1.40.107                           amd64        The web browser from Brave
ii  firefox-esr                                                 91.11.0esr-1~deb11u1               amd64        Mozilla Firefox web browser - Extended Support Release (ESR)
```

**Additional context**
This problem persists already for a while (6+ months or so), before opening the issue I upgraded kubeapps to latest chart version and I don't know my previous version anymore.

**Comment by dionysius** [comment]
The PR for this feature https://github.com/vmware-tanzu/kubeapps/pull/1277 does show that a "Hostname" field gets reset (We don't see the full form though)

**Comment by dionysius** [comment]
Would be a good start if someone could confirm this behavior or if it is an issue of my browser or kubeapps installation

**Comment by antgamdia** [comment]
@dionysius, I've got some time to have a look at it. I can confirm what you discovered, something is wrong with the update of the input fields. Thanks for reporting it.

I have dug into the code and found a workaround, but I haven't checked whether there are unexpected side effects yet.

In 
https://github.com/vmware-tanzu/kubeapps/blob/082be2fb012ce7f9d1733cca3515aaa381180c24/dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.tsx#L49

if you replace this `onChange` with `handleBasicFormParamChange(param)` the param gets reset on each "reset default" action.

It'd be great if you could give it a try, test it and send a PR!  Thanks!!
