### ISSUE TITLE
[Package repositories] Review and fix backend and frontend handling of auth headers

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5028]
**Summary**
Review and fix combined backend and frontend handling of package repositories auth headers.

**Background and rationale**
While reviewing PR #4954, I noticed that the handling of auth header values is different by plugin.

For bearer authentication, Helm plugin assumes that the content of the header in the repo request is only the token itself without `Bearer`, whereas implementation for Kapp assumes that it contains both. 
See this [LOC in the backend of Helm plugin](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go#L89) and this [LOC in the backend of Kapp plugin](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go#L1063). Flux does not implement this auth type.

UI must send the right data to the backend in order to avoid repeating the `Bearer` string many times when storing the repo. This is: if the Helm plugin only expects the token itself (without `Bearer`), but UI is sending the whole header, then the final header value stored might be `Bearer Bearer <token>`.

It might happen with other types of authentications.

**Description**
This task is for reviewing that all three plugins handle the repo authentication values in the same way.

Also make sure that vocabulary used is consistent. Avoid referring to token when using a header, e.g.:

```go
token := auth.GetHeader()
```

**Acceptance criteria**
Repositories authentication data is correctly handled for all plugins between backend and frontend.
Objects/Structs are correctly named when referring to headers and tokens.

**Comment by antgamdia** [comment]
Just my two cents here: I have mixed opinions on this problem: on the one hand, I don't see why the API should care about something else than an "HTTP header authentication" with two alternatives: either an RFC-compliant Authorization header or a custom header.
On the other hand, we would be delegating that logic to the clients, but... why not?

For instance, what I'm suggesting is moving from: 

```
PACKAGE_REPOSITORY_AUTH_TYPE_AUTHORIZATION_HEADER
PACKAGE_REPOSITORY_AUTH_TYPE_BASIC_AUTH
PACKAGE_REPOSITORY_AUTH_TYPE_BEARER
```

to 
```
PACKAGE_REPOSITORY_AUTH_TYPE_HTTP_AUTHORIZATION_HEADER // following the semantics of the header, as in the RFC (Bearer, Basic, etc...)
PACKAGE_REPOSITORY_AUTH_TYPE_HTTP_CUSTOM_HEADER // a struct receiving header_name and header_value
```

this way, the implementation wouldn't be so free and error-prone. WDYT?

**Comment by antgamdia** [comment]
> I was thinking about the same solution 😄
> (...)
> We could leave this task to make sure that backend and frontend make use of the whole header value, and we can create an additional issue to make the change for reducing the types enum. Does it sound good?

Yep, +1 to this, sounds great. Let's fix first the implementation problem, and, later on, let's discuss how to do it. 
Perhaps also @dlaloue-vmware is interested in this new issue.
