### ISSUE TITLE
Release new Kubeapps version (2.5.0)

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#5082]
**Summary**
Release a new version of Kubeapps

**Background and rationale**
Kubeapps monthly release including [Use the new Repositories API in the UI](https://github.com/vmware-tanzu/kubeapps/issues/4764).

**Description**
Release a new version of Kubeapps including all features, enhancements and bug fixing merged once the phase 1 for [Use the new Repositories API in the UI](https://github.com/vmware-tanzu/kubeapps/issues/4764) is ready.

This new version must comply [semver](https://semver.org/), though it means change a little bit Kubeapps versioning, but to be adapted to standards.

**Acceptance criteria**
 - New release is tagged and available in github
 - New release is available in Bitnami Application Catalog
 - New release is available in Tanzu Package for Kubeapps

**Additional context**
In the past Kubeapps versioning rules did not follow any criteria, so to help our community users Kubeapps maintainers team will start using [semver](https://semver.org/) for Kubeapps releases.

**Comment by antgamdia** [comment]
Dependencies have been bumped up (https://github.com/vmware-tanzu/kubeapps/pull/5123). The next step is to start reporting scanning and reporting the licenses internally, as well as to declare a dependency-freeze period.

**Comment by ppbaena** [comment]
Release 2.5.0 reported in BOSS Director

**Comment by antgamdia** [comment]
Starting a manual review of the release candidate, some bugs were found, but we are working to send a fix ASAP. Once this step is done, we will be able to trigger a release soon.

**Comment by antgamdia** [comment]
Tests are failing on GKE somehow:

![Image](https://user-images.githubusercontent.com/11535726/184234236-547e2c5c-6f24-473a-ad04-cc528b008fc1.png)

**Comment by antgamdia** [comment]
The release is finally out: https://github.com/vmware-tanzu/kubeapps/releases/tag/v2.5.0
