### ISSUE TITLE
Update Kubeapps logo

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#5120]
**Summary**
Update the new Kubeapps logo everywhere.

**Background and rationale**
Kubeapps logo has been revamped to be consistent with corporate branding and other OSS in VMware. 

**Description**
It is necessary to update the Kubeapps logo for the revamped one on both the Kubeapps dashboard and the Kubeapps website.

**Acceptance criteria**

- [x] New logo is updated in Kubeapps: https://github.com/vmware-tanzu/kubeapps/pull/5130
- [x] New logo is updated in https://kubeapps.dev: https://github.com/vmware-tanzu/kubeapps/pull/5131
- New logo is updated in the GitHub repo, namely:
  - [x] README.md and other markdown files, if any: https://github.com/vmware-tanzu/kubeapps/pull/5132
  - [x] Repository settings
  - [x] Former @Kubeapps organization
- [x] New logo is updated in the @kubeapps-bot account
- [x] New logo is updated in internal tools
- [x] New logo is updated in Gravatar

**Comment by castelblanque** [comment]
As a second phase, we could notify external sites/projects that reference Kubeapps, for example Tanzu Community Edition:
![image](https://user-images.githubusercontent.com/67455978/180980881-c63bc2c4-3799-4408-b081-4c657a3d70b8.png)

**Comment by antgamdia** [comment]
Also, we should update the @kubeapps-bot logo and other internal accounts' logo (gitlab, etc)
