### ISSUE TITLE
Cookie translation in kubeapps.dev

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#5149]
**Describe the bug**
Link to Cookie configuration is not translated and displayed in browser language configuration 

**To Reproduce**

1. Go to [https://kubeapps.dev](https://kubeapps.dev)
2. Scroll down to '....'
3. See 'Cookie configuration' text when your browser is configured to another language different from English

**Expected behavior**
Link should be displayed in English as the other links in the footer

**Screenshots**
<img width="1436" alt="Screen Shot 2022-08-01 at 11 08 32" src="https://user-images.githubusercontent.com/2997110/182114619-0edf6f9f-b0b6-4696-ad75-1dff5aae58f5.png">

**Desktop (please complete the following information):**

- Website

**Comment by beni0888** [comment]
After reviewing the documentation provided by @ppbaena via email, I think there's nothing we can do on our own to fix this issue, as we are using a `One Trust` profile shared by all (or at least several) VMware's microsites, so we would need the One Trust account's admin to tune the behavior and that would affect all the sites sharing this profile. In the provided instructions they refer to [https://tanzucommunityedition.io/](https://tanzucommunityedition.io/) as an example, where we can see that they're facing the same issue. That being said, I think that the best we can do is to warn the One Trust account's owner about the issue and let them decide if they want to fix the behavior so the notification is always shown in English (what we would like to happen), or if they prefer to leave it as is and show the text in the language configured in the client's browser.

**Comment by ppbaena** [comment]
Kubeapps maintainers team reached out to the team in charge of `OneTrust` script for cookies at VMware and the reply was:

> The cookie banner gets set to the default language that the user’s browser is set to. 

So there isn't an issue with cookie banner and footer link.
