### ISSUE TITLE
Evaluate GoReleaser

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5156]
**Summary**
GoReleaser is a widely used tool for finding out problems prior to releasing Go projects. It could be helpful for Kubeapps.

**Background and rationale**
It is a tool used by other projects like SealedSecrets.

**Description**
Projects like ENS and [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets) are using [GoReleaser](https://goreleaser.com/).
Kubeapps could evaluate its usage and eventual adoption, e.g. for cross compilation or nightly builds.
There needs to be a work of analyzing the benefits/drawbacks having into account that official release of chart and images is done by the Bitnami team.

Contact SealedSecrets team for more insights.

**Acceptance criteria**
- GoReleaser features to be used in Kubeapps

**Additional context**
- [GoReleaser GitHub action](https://github.com/goreleaser/goreleaser-action)
- [GitHub action setup used by SealedSecrets](https://github.com/bitnami-labs/sealed-secrets/blob/main/.github/workflows/release.yaml#L57)
- [SealedSecret's `.goreleaser.yml`](https://github.com/bitnami-labs/sealed-secrets/blob/main/.goreleaser.yml)

**Comment by absoludity** [comment]
Hey @castelblanque , `goreleaser` itself looks great for releasing binaries and images, but I'm not sure how it can benefit us with Kubeapps, given that we don't have binary artifacts (so the binary cross-compilation is not so useful), we *do* have image artifacts for our latest builds - but these are not part of any release (no semver tag, no release with artifacts). So I think we *could* maybe use it for building those latest images during CI (replacing the `build_docker_images` and `build_*_image` actions using some -dev fake release tag), but given we don't release those, I'm not (yet) seeing a benefit over the github actions that we have.

We do tag a semver release when triggering a Kubeapps release, but as you know this is just to trigger the Bitnami pipeline which handles all the image building (including binaries) currently (and not sure that's worth changing right now, though maybe).

Let me know if there are other aspects you were thinking of. Thanks either way!

**Comment by castelblanque** [comment]
I was asked to evaluate if we could use `goreleaser` for Kubeapps. That is why this issue was created to keep it in mind and evaluate it at some point.
Now we have new CI in place, and the whole releasing process seems to be fine. At first sight I don't see the added value of using `goreleaser`, so I agree with your analysis.
