### ISSUE TITLE
Explore adding Acorn packaging to Kubeapps

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5164]
**Summary**
Explore the technical feasibility of adding support for [Acorn](https://acorn.io/).

**Background and rationale**
Acorn is self defined as "_an application packaging and deployment framework that simplifies running apps on Kubernetes_".
It has its own way of packaging applications for Kubernetes, which makes it a candidate to be supported by Kubeapps.
It has been released recently and it is at an early stage of development.

**Description**
Acorn adds its own packaging definition, aka Acornfile in a Docker fashion. The file defines all the containers, ports, etc.
It also contains input arguments, as values for a Helm chart do.
The outcome package "_in its binary form is an OCI image that can be pushed to any OCI (Docker) registry. The OCI image includes all the referenced Docker images plus the application definition metadata needed to run the application._".
Kubeapps community should decide if it is interesting, and possible, to add the support.

**Acceptance criteria**
Decision if Acorn support should be added to Kubeapps from both the technical point of view and the roadmap point of view.

**Comment by ppbaena** [comment]
Close as there is no plan to develop a new plugin for acorn. To be reviewed if requested in the future.
