### ISSUE TITLE
Delete the git submodule 

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5184]
**Summary**
From time to time, we got some mismatches between the local/upstream commit HEAD pointer to the `codegen` submodule. It was added 5 years ago (see https://github.com/vmware-tanzu/kubeapps/pull/181/files)... but it is seldom used. I don't see any reason for us to keep having it.

**Background and rationale**
Since we are not using the checkout code, it is an unnecessary extra element to maintain., IMO.

**Description**
Remove the git submodule and the unnecessary code.

**Acceptance criteria**
- Remove the git submodule 
- Remove the unnecessary related code.
- Inform the team members to sync locally this change as well

**Additional context**
N/A

**Comment by castelblanque** [comment]
Totally +1 for the removal.
Let's get rid of unnecessary stuff 😃

**Comment by beni0888** [comment]
Also agree, let's kill it with 🔥
