### ISSUE TITLE
🐛 Kubeapps Catalog is outdated with Bitnami Helm Chart metadata

### ISSUE THREAD

**Issue by pcgeek86** [vmware-tanzu/kubeapps#5198]
**Describe the bug**

- Kubeapps is missing newer versions of Bitnami Helm Charts.
- For example, the [Pinniped Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/pinniped) is up to version 0.17.
- **However**, Kubeapps web UI is only showing 0.1.5 as the newest version.

<img width="1680" alt="Screen Shot 2022-08-11 at 2 19 38 AM" src="https://user-images.githubusercontent.com/466713/184092458-48feef58-9df4-4662-b05c-c012211a8d6e.png">

<img width="1664" alt="Screen Shot 2022-08-11 at 2 20 44 AM" src="https://user-images.githubusercontent.com/466713/184092628-94a2c643-293a-402b-a8de-5b85c09b7699.png">

**To Reproduce**

1. Install Kubeapps via Helm
2. Open Kubeapps web UI
3. Search for `pinniped` under the **Catalog**
4. Notice that the latest version of Pinniped is 0.1.5 in the Kubeapps web UI

How do I force Kubeapps to update the Catalog metadata, with the Bitnami GitHub repository?

**Expected behavior**

Kubeapps should be displaying the latest Bitnami Helm Charts that are available to install.

**Screenshots**

See above.

**Desktop (please complete the following information):**

- Version [e.g. 2.4.4]
- Kubernetes version [e.g. 1.21.10] Linode LKE 1.23
- Package version [e.g. Helm 3.2, carvel-imgpkg 0.28.0] 

**Additional context**

**Comment by castelblanque** [comment]
hi @pcgeek86,
Thanks for your message.

It does not seem a problem of Kubeapps. If you get the chart from pure Helm CLI:
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm search repo pinniped
```
or if you already have the Bitnami repo added:
```
helm repo update bitnami
helm search repo pinniped
```

You can see that the latest available version for chart is 0.1.5.
```
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/pinniped	0.1.5        	0.18.0     	Pinniped is an identity service provider for Ku...
```
Kubeapps just relies on Helm to get the data.
It could be a problem on Bitnami chart. Please open an issue in [their repo here](https://github.com/bitnami/charts/issues).

**Comment by antgamdia** [comment]
The github action is failing during the publishing stage for this asset: https://github.com/bitnami/charts/runs/7675440816?check_suite_focus=true
As far as I know, they are aware of the issue and will try to fix it soon. Anyway, thanks for reporting it.

Closing for now, but please feel free to reopen it if you have further questions.

**Comment by pcgeek86** [comment]
Thank you so much! @antgamdia
