### ISSUE TITLE
Global repositories handling is inconsistent - Carvel issue

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5200]
**Describe the bug**
Creating global repositories is not correctly handled now that plugins came into the picture.

- Helm direct plugin assumes that the global namespace is made up of whatever comes from the chart values in `apprepository.globalReposNamespaceSuffix` as a suffix. E.g. `kubeapps-repos-global`
- Carvel plugin assumes `kapp-controller-packaging-global`. See [the backend definition](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go#L34).
- Flux plugin does not have global namespaces

This bug report focuses on Carvel.

**To Reproduce**

For the Carvel problem:

1. Enable Carvel plugin
2. Switch context in Kubeapps to the global namespace, e.g. `kubeapps-repos-global`
3. Add a Carvel package repository
4. Get error `Namespace Scope is inconsistent with the provided Namespace`

Furthermore, if the repository is instead added to the namespace `kapp-controller-packaging-global`, it fails with the same error.
For the rest of namespaces it works.

**Expected behavior**
Package repo is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/67455978/184123693-c3be4fb6-2318-42e5-9b65-51d5cc53e1fb.png)

**Comment by castelblanque** [comment]
This bug happens due to the frontend assuming that the global namespace is the Helm one ( e.g. kubeapps-repos-global) for all plugins.

**Comment by antgamdia** [comment]
There are some additional occurrences of `namespace === globalReposNamespace`  we may want to have a look at:

1. dashboard/src/actions/repos.ts
2. dashboard/src/components/Catalog/Catalog.tsx
3. dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx
4. dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
