### ISSUE TITLE
Carvel repositories are not visible in Helm global namespace

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5201]
**Describe the bug**
When creating a Carvel repository in the global namespace, repository is not shown. It is successfully created, but not rendered in the repositories summary.

**To Reproduce**

1. Set the global namespace to `kubeapps-global-repos` by setting the suffix '-global-repos' to the chart value `apprepository.globalReposNamespaceSuffix`.
2. Switch context to that namespace in Kubeapps. Remember that this is not the global namespace for Carvel.
3. Create a Carvel package repository
4. Repository does not appear

**Expected behavior**
Namespaced repository is seen in the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/67455978/184141319-d39da4d9-7dd5-4b30-b05b-1c77757ad8ba.png)

**Comment by antgamdia** [comment]
I'd say the latest v2.5.0 release (after your fix handling the carvel global namespace) fixes this issue,

![image](https://user-images.githubusercontent.com/11535726/185406107-fc0fa70c-b610-4ab5-bb04-009e35808126.png)

Closing for now, but reopen it if necessary.
