### ISSUE TITLE
OCI based GCP's Artifact Registry - Package versions not sorted correctly

### ISSUE THREAD

**Issue by Jonito** [vmware-tanzu/kubeapps#5211]
**Summary**

Chart package versions not sorted properly when using GCP's Artifact Registry Package Repository

**Background and rationale**

It's becomes difficult to identify the latest package and hence difficult to deploy the packages because the versions are not sorted in order.
**Description**

Our repos consist of helm charts with kustomize and we deploy using kubeapps.

 When using **GCP Artifact Registry Package repository**, the package versions  are not sorted properly.

Screenshot of the issue.

![gcp-artifact](https://user-images.githubusercontent.com/360857/184332108-0a0f7923-58da-45b6-8970-62bc60eda4ff.png)

But with **Chartmusuem** Package Repository, the sorting is proper on the **same deployment**.
Screenshot showing working.

![chartmusuem](https://user-images.githubusercontent.com/360857/184332281-e02957ea-e74d-4d22-b38d-2ff56e21a6ca.png)

**Acceptance criteria**
We would like to have the package versions to be sorted in descending order with latest on top using GCP's Artifact Registry Package Repository just like Chartmusuem.

**Additional context**
Functionality:  I could deploy the helm chart app using chart from GCP's Artifact Registry Package Repository.

**Comment by antgamdia** [comment]
I'd say it has something to do with the fact that GCP Artifact Registry is storing OCI artifacts rather than plain helm charts like chartmuseum is doing.
That said, I've just tried to reproduce the issue against another OCI-compliant storage (Harbor), and the sorting works like a charm with the default chart configuration.

Before setting up a GCP artifact and trying to replicate the issue there, I'd like to know which is the number of package version that you are displaying. I mean, the values of this config params:

```
kubeappsapis.pluginConfig.core.packages.v1alpha1.versionsInSummary.major
kubeappsapis.pluginConfig.core.packages.v1alpha1.versionsInSummary.minor
kubeappsapis.pluginConfig.core.packages.v1alpha1.versionsInSummary.patch
```

Perhaps there is something wrong there? Anyway, seems like an issue.

**Comment by Jonito** [comment]
The configurations are
kubeappsapis.pluginConfig.core.packages.v1alpha1.versionsInSummary.major 3
kubeappsapis.pluginConfig.core.packages.v1alpha1.versionsInSummary.minor 3
kubeappsapis.pluginConfig.core.packages.v1alpha1.versionsInSummary.patch 3

**Comment by antgamdia** [comment]
I'll give it a try to see if I can reproduce the problem. Thanks.

**Comment by antgamdia** [comment]
Maybe this issue gets fixed in the upcoming v2.5.0 release, we did merge this PR https://github.com/vmware-tanzu/kubeapps/pull/4952 aimed at fixing the sorting.

**Comment by antgamdia** [comment]
The new release is out (see https://github.com/vmware-tanzu/kubeapps/releases/tag/v2.5.0). I'd say this version will solve your issue; please upgrade to this new version and let us know if it really does.
If not, please feel free to re-open the issue and we'll take a closer look at it. Thanks!

**Comment by Jonito** [comment]
Thanks, will check and let you know
