### ISSUE TITLE
Remove yaml-based config option for Cobra binaries

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5250]
**Summary**
In some Cobra commands, if no specific config file is provided, a fixed file name is looked up in the home folder.
This is something inherited from old code and not used. Remove it consistently across all binaries.

Some examples:

- [Apprepository controller](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/apprepository-controller/cmd/root.go#L111)
- [Asset syncer](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/asset-syncer/cmd/root.go#L152)

**Acceptance criteria**
All unused looked-up config files in Cobra commands are deleted

**Additional context**
This is something that was found while removing Kubeops. For example, looked up filenames in the examples above are still `.kubeops`.

**Comment by Hirdey-1999** [comment]
I  Can Solve This Issue Can You Just Elaborate The Code To Be Removed

**Comment by castelblanque** [comment]
That would be awesome @Hirdey-1999, many thanks!

The goal is to completely remove branches like [this one from kubeapps-apis root cmd](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/cmd/root.go#L85-L91).
Similar ones appear in `asset-syncer` and `apprepository-controller`.

With this, we are removing the use default config file looked up in the user's home folder, so references like [this one](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/cmd/root.go#L66) must be removed too.

**Comment by Hirdey-1999** [comment]
I Have To Remove These Types Of Files
![image](https://user-images.githubusercontent.com/71271612/188672332-e802379a-cd25-4582-86d9-af2bb6cdefbe.png)

**Comment by castelblanque** [comment]
The idea is to stop supporting this fixed name config files.
So e.g. this whole part can be removed:
```go
else {
  // Find home directory.
  home, err := homedir.Dir()
  cobra.CheckErr(err)
  
  // Search config in home directory with name ".kubeapps-apis" (without extension).
  viper.AddConfigPath(home)
  viper.SetConfigName(".kubeapps-apis")
}
```

**Comment by Hirdey-1999** [comment]
Started Working On This Issue

**Comment by Hirdey-1999** [comment]
I Have Did With The Changes Please Check With The PR If Something Is Missing Kindly Reply Back 
Thanks @castelblanque For Giving Me This Opportunity
https://github.com/vmware-tanzu/kubeapps/pull/5335

**Comment by castelblanque** [comment]
Done in #5420
