### ISSUE TITLE
Remove Kubeops

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5253]
**Summary**
After #5239 and #5249, Kubeops is effectively disabled.
No endpoints are served from it, or resources used.
It can be safely removed without affecting anybody.

**Description**
Given that Kubeops is now useless and a burden, let's completely remove it.

**Acceptance criteria**
Kubeops is completely removed from Kubeapps

**Additional context**
Strongly related to #4785

There might be additional work to be done on the Bitnami side to remove the generation of Kubeops assets, tests, etc.

**Comment by antgamdia** [comment]
Also, we have to remove the old API endpoints from the `openapi.yaml` file. This is still a manual task because we needed to add th kubeops, assetsvc endpoints to the automatically generated swagger doc from the grpc. Now, it should be way easier to do it once we remove all the legacy stuff!
