### ISSUE TITLE
Reorganize and clean up code after Kubeops removal

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5284]
**Summary**
Remove old dead code related mainly to `kubeops` and pre-plugins architecture.
Migrate code under `/pkg` that is directly related to `helm` plugin only.

**Description**
After removing `kubeops` (#5253) there is associated source code placed in the `/pkg` folder.
It needs reviewing and cleaning up the parts not needed. 

**Acceptance criteria**
Source code under `/pkg` that is no longer used has been removed.
Source code that is only related and used to e.g. `helm` plugin must be moved to that plugin.

**Comment by antgamdia** [comment]
According to the analysis, we performed some time ago at https://github.com/vmware-tanzu/kubeapps/issues/4847#issuecomment-1150520731, it seems we can get rid of: `pkg/kube`,  `pkg/agent` and  `pkg/handlerutil`, see:

![image](https://user-images.githubusercontent.com/11535726/188114190-9d85a3be-dffb-47d0-817d-77c40d17ce27.png)
