### ISSUE TITLE
Invesitgate transient errors in pinniped-proxy hash-related tests

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5296]
**Describe the bug**
After some time consistently working, the hashing-related tests in the pinniped-proxy component started failing.
For the sake of the CI health, we landed https://github.com/vmware-tanzu/kubeapps/pull/4900 and ignored the offending tests, but we may want to dig into the root cause of the error.

**To Reproduce**
N/A

**Expected behavior**
Tests consistently passing

**Screenshots**
N/A

**Desktop (please complete the following information):**
DEVEL

**Additional context**
N/A

**Comment by absoludity** [comment]
I'm not sure what more I can do here, but I've removed the `ignore` macros so the tests run and:
1. Run the test 500 times on HEAD and cannot reproduce
2. Run the test 500 times on the commit before they were switched off (ie. when they were failing in CI?)
3. Run the test 500 times on the commit 514bd5c9138ba6dd3d4929dfc3010a37a7a23406 where the test was added
4. Run the test 500 times on the last commit e2041ea265f006b2db46f7998d6bd8be7b4251e7 on the same day (Jun 10) where I'd created the issue originally

I've additionally run the test 50 times recompiling between each test to no avail.

So I don't know how we might reproduce this. All I can suggest is that we re-enable the tests until they fail again - which is pretty sucky. Happy for any suggestions of other things I could try.

**Comment by absoludity** [comment]
Just got back to this - and with a fresh mind, the problem is obvious:

```
DEFAULT_PINNIPED_API_SUFFIX="foo.bar" cargo test test_token_credential
    Finished test [unoptimized + debuginfo] target(s) in 0.12s
     Running unittests src/main.rs (target/debug/deps/pinniped_proxy-377bbebe777ff780)

running 8 tests
test pinniped::tests::test_token_credential_request_hash_differs_with_authenticator ... ok
test pinniped::tests::test_token_credential_request_hash_differs_with_token ... ok
test pinniped::tests::test_token_credential_request_with_future_expiry_is_not_expired ... ok
test pinniped::tests::test_token_credential_request_with_old_expiry_is_expired ... ok
test pinniped::tests::test_token_credential_request_without_credential_is_expired ... ok
test pinniped::tests::test_token_credential_request_hash_default ... FAILED
test pinniped::tests::test_token_credential_request_hash_identical_with_status_change ... FAILED
test pinniped::tests::test_token_credential_request_without_status_is_expired ... ok

failures:

---- pinniped::tests::test_token_credential_request_hash_default stdout ----
thread 'pinniped::tests::test_token_credential_request_hash_default' panicked at 'assertion failed: `(left == right)`
  left: `2671791248625081931`,
 right: `2363471629413450951`', src/pinniped.rs:549:9

---- pinniped::tests::test_token_credential_request_hash_identical_with_status_change stdout ----
thread 'pinniped::tests::test_token_credential_request_hash_identical_with_status_change' panicked at 'assertion failed: `(left == right)`
  left: `2671791248625081931`,
 right: `2363471629413450951`', src/pinniped.rs:593:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    pinniped::tests::test_token_credential_request_hash_default
    pinniped::tests::test_token_credential_request_hash_identical_with_status_change

test result: FAILED. 6 passed; 2 failed; 0 ignored; 0 measured; 22 filtered out; finished in 0.00s
```

Tests are run concurrently by default, so if the test that temporarily sets the env runs at the same time as the hash check, a different hash is generated.

The test environment should be isolated. Fixing.
