### ISSUE TITLE
Replace `ansi_term` dependency in Pinniped-proxy

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5357]
**Summary**
Replace `ansi_term` dependency in the Pinniped-proxy service.

**Background and rationale**
Dependabot is warning that Rust's dependency `ansi_term` is unmaintained. Project hasn't been updated for at least three years.
It is not a direct dependency in `pinniped-proxy`, but a dependency of `clap` v2, which in turn is a dependency of `structopt`.
[Structopt](https://github.com/TeXitoi/structopt) is not maintained either (see their [pinned issue](https://github.com/TeXitoi/structopt/issues/525)).

Dependabot is warning that it is a critical issue.
![image](https://user-images.githubusercontent.com/67455978/190963332-eb9f8936-e196-4495-8cb9-ddebd021aad3.png)

**Description**
A feasible solution is to migrate `structopt` to [`clap` v3](https://github.com/clap-rs/clap). There is a [migration guide here](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating).

**Acceptance criteria**
`ansi_term` is not used anymore.

**Comment by absoludity** [comment]
Yep, with the work I've been doing with https://github.com/vmware/database-stream-processor/ I've been using clap v3 directly after seeing `structopt`'s functionality was now included there, and had noted to come back and do the same here. Thanks!
