### ISSUE TITLE
Readiness probe failed: Get "http://10.244.83.115:8080/": dial tcp 10.244.83.115:8080: connect: connection refused

### ISSUE THREAD

**Issue by Dyuzz** [vmware-tanzu/kubeapps#5360]
**Summary**
Installation failed

**Background and rationale**
K8S Version: 1.25.0
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ kubectl create namespace kubeapps
$ helm install kubeapps --namespace kubeapps bitnami/kubeapps

**Description**
$ kubectl get pod -n kubeapps

apprepo-default-sync-bitnami-8fbkv-jwt9w                      0/1     CrashLoopBackOff   4 (36s ago)   3m33s
kubeapps-699b9d96df-k9wmq                                     0/1     CrashLoopBackOff   5 (59s ago)   4m5s
kubeapps-699b9d96df-klz54                                     0/1     CrashLoopBackOff   5 (38s ago)   4m5s
kubeapps-internal-apprepository-controller-54bb7fcd4b-lkxhc   1/1     Running            0             4m5s
kubeapps-internal-dashboard-8fb9cd85b-7lgq5                   1/1     Running            0             4m5s
kubeapps-internal-dashboard-8fb9cd85b-dqbqr                   1/1     Running            0             4m5s
kubeapps-internal-kubeappsapis-6b9cfbdf8b-hs6tx               1/1     Running            0             4m5s
kubeapps-internal-kubeappsapis-6b9cfbdf8b-x4g6g               1/1     Running            0             4m5s
kubeapps-internal-kubeops-7759778f45-77hlx                    1/1     Running            0             4m5s
kubeapps-internal-kubeops-7759778f45-h69tq                    1/1     Running            0             4m5s
kubeapps-postgresql-0                                         1/1     Running            0             4m5s

$ kubectl describe pod  -n kubeapps kubeapps-65454c8cc4-k9wmq

Name:             kubeapps-699b9d96df-k9wmq
Namespace:        default
Priority:         0
Service Account:  default
Node:             gisweb4/125.220.153.23
Start Time:       Tue, 20 Sep 2022 22:41:58 +0800
Labels:           app.kubernetes.io/component=frontend
                  app.kubernetes.io/instance=kubeapps
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubeapps
                  helm.sh/chart=kubeapps-10.3.3
                  pod-template-hash=699b9d96df
Annotations:      checksum/config: f6b71796743a84a10a7169e9a00e4663335554dfa43ff2e00ba77640725d3755
                  cni.projectcalico.org/containerID: d6cc94deb119f5e373aebcb4c8d3fce63c744033256b4e921f3cc12d3e45008e
                  cni.projectcalico.org/podIP: 10.244.160.97/32
                  cni.projectcalico.org/podIPs: 10.244.160.97/32
Status:           Running
IP:               10.244.160.97
IPs:
  IP:           10.244.160.97
Controlled By:  ReplicaSet/kubeapps-699b9d96df
Containers:
  nginx:
    Container ID:   containerd://2df666d38fc55d999b3a84ab40efeae6028378ea7c00f69308e0d49780b10828
    Image:          docker.io/bitnami/nginx:1.23.1-debian-11-r15
    Image ID:       docker.io/bitnami/nginx@sha256:caef3681b02a563c3b5e7fb12e75c4e5a569eee39b058518d96dd24f21e6d21a
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 20 Sep 2022 22:45:03 +0800
      Finished:     Tue, 20 Sep 2022 22:45:04 +0800
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     250m
      memory:  128Mi
    Requests:
      cpu:      25m
      memory:   32Mi
    Liveness:   http-get http://:http/healthz delay=60s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/ delay=0s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:  false
    Mounts:
      /opt/bitnami/nginx/conf/server_blocks from vhost (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mgxxv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  vhost:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubeapps-frontend-config
    Optional:  false
  kube-api-access-mgxxv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  4m51s                   default-scheduler  Successfully assigned default/kubeapps-699b9d96df-k9wmq to gisweb4
  Warning  Unhealthy  4m23s                   kubelet            Readiness probe failed: Get "http://10.244.160.97:8080/": dial tcp 10.244.160.97:8080: connect: connection refused
  Normal   Pulled     3m53s (x4 over 4m49s)   kubelet            Container image "docker.io/bitnami/nginx:1.23.1-debian-11-r15" already present on machine
  Normal   Created    3m53s (x4 over 4m49s)   kubelet            Created container nginx
  Normal   Started    3m53s (x4 over 4m49s)   kubelet            Started container nginx
  Warning  BackOff    3m35s (x12 over 4m47s)  kubelet            Back-off restarting failed container

**Comment by Dyuzz** [comment]
I have tried to reinstall several times, but the installation failed. 
There is no problem installing other software on my K8S.
Any helps will be appriciated.

**Comment by antgamdia** [comment]
Sorry to hear you're facing problems with the installation. I'm assuming you are not passing any values to the helm chart.
Unfortunately, I've just tried to replicate the aforementioned commands in k8s `v1.25.0`, but it worked like a charm locally.

What's your Kubernetes platform (using a cloud provider, etc) ?  I notice you're using calico as the CNI, perhaps it has something to do (not sure)?

Do you have the logs of the failing pods  `kubeapps-65454c8cc4-wjrwl`  and `apprepo-kubeapps-sync-bitnami-27727360`?

What happens if you run Kubeapps without the helm plugin enabled? `--set packaging.helm.enabled=false --set packaging.flux.enabled=false`
> You'll need to have flux controller in you cluster, `kubectl apply -f https://github.com/fluxcd/flux2/releases/download/v0.34.0/install.yaml`, [see also this guide](https://kubeapps.dev/docs/latest/tutorials/managing-carvel-packages/).

I think there's a problem connecting to the bitnami repo (the one installed by default) from Kubeapps. Maybe a network reachability issue? Not sure.

**Comment by Dyuzz** [comment]
I have executed this command and re installed kubeapps with help, but the error is still similar to the above

**kubectl logs apprepo-default-sync-bitnami-27728120-szcm2**

I0920 15:23:05.749586       1 root.go:34] asset-syncer has been configured with: server.Config{DatabaseURL:"kubeapps-postgresql:5432", DatabaseName:"assets", DatabaseUser:"postgres", DatabasePassword:"REDACTED", Debug:false, Namespace:"default", OciRepositories:[]string{}, TlsInsecureSkipVerify:false, FilterRules:"", PassCredentials:false, UserAgent:"asset-syncer/2.5.1 (kubeapps/2.5.1)", UserAgentComment:"kubeapps/2.5.1", GlobalReposNamespace:"default", KubeappsNamespace:"", AuthorizationHeader:"", DockerConfigJson:""}
Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp 13.35.125.126:443: connect: no route to host
Usage:
  asset-syncer sync [REPO NAME] [REPO URL] [REPO TYPE] [flags]
.........
Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp 13.35.125.126:443: connect: no route to host

**Comment by Dyuzz** [comment]
I had

**Comment by MaleicAcid** [comment]
I also seem to have the same problem, is there anyone who can help me.

user00@node01:~/apps$ kubectl describe pod kubeapps-5454d8db65-2l4hf -n kubeapps
Name:             kubeapps-5454d8db65-2l4hf
Namespace:        kubeapps
Priority:         0
Service Account:  default
Node:             node01-racknerd-3c3g-la/74.48.58.232
Start Time:       Sat, 20 Jan 2024 21:44:57 -0500
Labels:           app.kubernetes.io/component=frontend
                  app.kubernetes.io/instance=kubeapps
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubeapps
                  app.kubernetes.io/version=1.25.3
                  helm.sh/chart=kubeapps-14.2.1
                  pod-template-hash=5454d8db65
Annotations:      checksum/config: f8e20336b81b4a305168520160ffe1b9446e5febed544c26cd165065fa2f5980
Status:           Running
IP:               10.42.0.57
IPs:
  IP:           10.42.0.57
Controlled By:  ReplicaSet/kubeapps-5454d8db65
Containers:
  nginx:
    Container ID:    containerd://c3e4c9483ee8b66aee7dea7013b5c58dbe360ea48f3ce0e38dbfc10d4421a5f3
    Image:           docker.io/bitnami/nginx:1.25.3-debian-11-r4
    Image ID:        docker.io/bitnami/nginx@sha256:1a76309f5278a0a88e4aa2c996f99186b0c56f1c0ed07abdfcbccfe4bae1b1e0
    Port:            8080/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    State:           Running
      Started:       Sat, 20 Jan 2024 21:45:12 -0500
    Ready:           True
    Restart Count:   0
    Limits:
      cpu:     250m
      memory:  128Mi
    Requests:
      cpu:      25m
      memory:   32Mi
    Liveness:   http-get http://:http/healthz delay=60s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/ delay=0s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:  false
    Mounts:
      /opt/bitnami/nginx/conf/server_blocks from vhost (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-569br (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  vhost:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubeapps-frontend-config
    Optional:  false
  kube-api-access-569br:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  22s (x1310 over 7h19m)  kubelet  Readiness probe failed: Get "http://10.42.0.57:8080/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
