### ISSUE TITLE
Accessibility compliance for kubeapps.dev

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#5397]
**Summary**
The goal is to ensure [kubeapps.dev](https://kubeapps.dev/) website is accessible

**Background and rationale**
All VMware’s OSS products must meet Web Content Accessibility Guidelines (WCAG) 2.1 Level AA standards.
Devices, Assistive Technology combinations used: Chrome + NVDA on Windows, Safari + Voiceover on Mac

**Description**
Review the results of the accessibility audit for [kubeapps.dev](https://kubeapps.dev/) and fix all [issues reported](https://jira.eng.vmware.com/issues/?jql=labels%20%3D%20A11y-kubeapps-Sept22) (JIRA - internal tool)

**Acceptance criteria**

- [x] All issues identified in the accessibility audit are fixed
- [ ] For every major UI/ Feature update fixed, a request for Accessibility Testing has been performed and succeeded.

**Additional context**
An Accessibility Testing has been completed for [kubeapps.dev](https://kubeapps.dev/) with several issues identified to comply with Web Content Accessibility Guidelines (WCAG) 2.1 Level AA standards (issues: 7 critical, 20 High, 2 Medium, 5 Low)

**Comment by antgamdia** [comment]
#### Current status: 
- 4 out of 34 a11y issues are pending (awaiting an official response)
- Still pending: submit this evidence in JIRA and close the tickets.

#### Summary:
- [X] [14258](https://jira.eng.vmware.com/browse/VPAT-14258): 🟢 
- [X] [14230](https://jira.eng.vmware.com/browse/VPAT-14230): 🔴  BLOCKED (awaiting a11y team's response)
- [X] [14229](https://jira.eng.vmware.com/browse/VPAT-14229): 🟢
- [X] [14228](https://jira.eng.vmware.com/browse/VPAT-14228): 🟢
- [X] [14227](https://jira.eng.vmware.com/browse/VPAT-14227): 🟢
- [X] [14226](https://jira.eng.vmware.com/browse/VPAT-14226): 🟢
- [X] [14225](https://jira.eng.vmware.com/browse/VPAT-14225): 🟢 
- [ ] [14224](https://jira.eng.vmware.com/browse/VPAT-14224): 🔴 BLOCKED (awaiting a11y team's response)
- [X] [14223](https://jira.eng.vmware.com/browse/VPAT-14223): 🟢 
- [X] [14222](https://jira.eng.vmware.com/browse/VPAT-14222): 🟢 
- [X] [14221](https://jira.eng.vmware.com/browse/VPAT-14221): 🟢 
- [X] [14220](https://jira.eng.vmware.com/browse/VPAT-14220): 🟢 
- [X] [14219](https://jira.eng.vmware.com/browse/VPAT-14219): 🟢 
- [X] [14218](https://jira.eng.vmware.com/browse/VPAT-14218): 🟢 
- [X] [14217](https://jira.eng.vmware.com/browse/VPAT-14217): 🟢 
- [X] [14216](https://jira.eng.vmware.com/browse/VPAT-14216): 🟢 
- [X] [14215](https://jira.eng.vmware.com/browse/VPAT-14215): 🟢 
- [X] [14214](https://jira.eng.vmware.com/browse/VPAT-14214): 🟢 
- [ ] [14213](https://jira.eng.vmware.com/browse/VPAT-14213): 🔴 BLOCKED (awaiting a11y team's response)
- [X] [14212](https://jira.eng.vmware.com/browse/VPAT-14212): 🟢 
- [ ] [14211](https://jira.eng.vmware.com/browse/VPAT-14211): 🔴 BLOCKED (awaiting a11y team's response)
- [X] [14210](https://jira.eng.vmware.com/browse/VPAT-14210): 🟢 
- [X] [14209](https://jira.eng.vmware.com/browse/VPAT-14209): 🟢 
- [X] [14208](https://jira.eng.vmware.com/browse/VPAT-14208): 🟢 
- [X] [14207](https://jira.eng.vmware.com/browse/VPAT-14207): 🟢 
- [X] [14206](https://jira.eng.vmware.com/browse/VPAT-14206): 🟢 
- [X] [14205](https://jira.eng.vmware.com/browse/VPAT-14205): 🟢 
- [X] [14204](https://jira.eng.vmware.com/browse/VPAT-14204): 🟢 
- [X] [14203](https://jira.eng.vmware.com/browse/VPAT-14203): 🟢 
- [X] [14202](https://jira.eng.vmware.com/browse/VPAT-14202): 🟢 
- [X] [14201](https://jira.eng.vmware.com/browse/VPAT-14201): 🟢 
- [X] [14200](https://jira.eng.vmware.com/browse/VPAT-14200): 🟢 
- [X] [14199](https://jira.eng.vmware.com/browse/VPAT-14199): 🟢 
- [X] [14198](https://jira.eng.vmware.com/browse/VPAT-14198): 🟢

**Comment by ppbaena** [comment]
Thanks for the complete revision and detailed comment.

**Comment by antgamdia** [comment]
Reopen as we need to confirm with the a11y team before actually closing this issue.

**Comment by ppbaena** [comment]
Accessibility issues have been assigned to the audit team to review all the evidence and reply to the questions performed by @antgamdia.

**Comment by ppbaena** [comment]
Let's close this issue and reopen it if any issues from the acceptance review.

**Comment by antgamdia** [comment]
Fix for [VPAT-14202](https://jira.eng.vmware.com/browse/VPAT-14202):

![image](https://user-images.githubusercontent.com/11535726/198238698-0ad6b9b6-078f-41bc-993a-e6cc50ad788f.png)


Fix for [VPAT-14207](https://jira.eng.vmware.com/browse/VPAT-14207)

![image](https://user-images.githubusercontent.com/11535726/198254543-3c0e9186-d8d2-4129-b8e5-15ce570daec5.png)


Fix for and [VPAT-14205](https://jira.eng.vmware.com/browse/VPAT-14205)

![image](https://user-images.githubusercontent.com/11535726/198255034-c2be4431-23e1-4e38-973a-fb160dba3df8.png)

**Comment by antgamdia** [comment]
All the pending issues have been moved to "acceptance review". If any of them happen to be reopened, I'll also reopen this issue (hope we don't have to 🤞 )
