### ISSUE TITLE
Remove unused chart value `allowNamespaceDiscovery`

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5422]
**Description**
Chart values and Readme file contain a parameter that is not used in any place: `allowNamespaceDiscovery`.
Please check [this repo search](https://github.com/vmware-tanzu/kubeapps/search?q=allowNamespaceDiscovery).
This could be misleading and frustrating for end users, so let's better remove it.

**Acceptance criteria**
- Chart value `allowNamespaceDiscovery` is removed and not present in values file nor Readme.

**Comment by antgamdia** [comment]
Note that this change can be directly performed at https://github.com/bitnami/charts

**Comment by amoghrajesh** [comment]
@castelblanque @antgamdia I would like to work on this as a part of hacktoberfest 2022. Is this repo a part of it?

**Comment by ppbaena** [comment]
Hi @amoghrajesh , we have labelled the repo and issue so you can participate in hacktoberfest 2022 working on this issue.

**Comment by briancbarrow** [comment]
I'm guessing this can be closed since #5574 was merged?

**Comment by ppbaena** [comment]
Thanks for the heads up @briancbarrow!
