### ISSUE TITLE
Update to enable pinniped to manage web-app authn

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#5448]
**Summary**

Update our `pinniped-proxy` service to support the new web-app authentication of the pinniped supervisor, perhaps removing it altogether (though unlikely from what I understand so far).

**Background and rationale**

A couple of years ago we investigated, designed and implemented `pinniped-proxy` as a way for us to utilise the [VMware pinniped project](https://pinniped.dev/) for authentication with TKG/TMC clusters. Pinniped was initially released with support for authn only via `kubectl` and explicitly did not support web app authentication. Pinniped proxy just proxies requests from our webapp to the kubernetes API server, updating the request with a valid credential for the requesting user (by exchanging an `id_token` for a valid cert via the stand-alone pinniped concierge).

The latest release of pinniped includes support for the [pinniped Supervisor providing authn for webapps](https://pinniped.dev/docs/howto/configure-auth-for-webapps/).

**Description**

Investigate whether the new supervisor support can replace the existing pinniped-proxy authentication, or rather, whether we should keep the existing functionality for `pinniped-conciege` users and add support to `pinniped-supervisor` for those users (in particular, it may help with multicluster authn, without needing to configure each cluster etc.)

**Acceptance criteria**

* An agreed decision about the new functionality to be included (or not), and
* For that functionality, a user should be able to target different clusters that use the pinniped supervisor with authentication working out of the box.

**Comment by absoludity** [comment]
So after reading and playing with the [new Pinniped Supervisor functionality](https://pinniped.dev/docs/howto/configure-auth-for-webapps/), what I understand is that the new functionality in pinniped Supervisor is an **extra** `id_token` exchange, which I *think* is only necessary if you've configured the `JWTAuthnticator`s of your `pinniped-concierge` instances on each cluster to use a different audience per cluster (the recommendation from Pinniped, for good reason, but perhaps not urgent for our multicluster use-case).

Importantly, **it does not remove the need for our `pinniped-proxy` service at all** - in that even if we supported this new functionality, we (the client) still need to then exchange the `id_token` for an `mTLS` cert for user requests to the Kubernetes API - that part is no different. I'll wait to hear confirmation from @cfryanr or @benjaminapetersen before moving further, but details below.

## Current authentication for user requests to cluster

Currently we use oauth2-proxy for users to authenticate with an upstream OIDC identity provider and use concierge on each cluster, configured with a JWTAuthenticator with  *the same "kubeapps" audience* on each cluster, the audience matching the client id with which oauth2-proxy is configured to talk the provider. That is, when a user successfully logs in, the "kubeapps" client creds are used to talk to the provider, which issues an `id_token` for use by the "kubeapps" audience. When such an `id_token` is presented to concierge running on a cluster, it verifies that it is correctly signed to trust our OIDC identity provider and that the audience matches that specified in the JWTAuthenticator. If so, then the `id_token` can be exchanged for an `mTLS` cert which is used to talk with the kubernetes API server.

So when a Kubeapps user views the installed apps,
	- the request goes through oauth2-proxy to kubeapps-apis and so has the id_token in the request headers,
	- the id_token is then sent with any request to a cluster API server, via `pinniped-proxy`. 
	- When the request goes through  `pinniped-proxy` , the `id_token` is exchanged using the concierge endpoint on that cluster for an `mTLS` cert accepted by the cluster. This works for multiple clusters because the id_token issued by the provider specifies an audience for Kubeapps, and that audience is the same as that required by the JWTAuthenticator configuration of pinniped concierge on each cluster.

## When using with Pinniped Supervisor

I have not verified (using supervisor requires substantial setup - I can do so if required), but as I understand the documentation, this same setup would work just fine if we used Pinniped Supervisor as the OIDC identity provider (which would be configured to talk to the upstream Dex or other IdP). The `JWTAuthenticator` resources would point to the supervisor's endpoints, but as long as the audience of each was still for our Kubeapps audience, the `id_tokens` produced by supervisor for our kubeapps client would be considered valid by concierge. Verify this with the pinniped team.

That said, the Pinniped recommendation would be to... 

## Use Pinniped Supervisor with different audiences for each cluster

In a general scenario, you would not want someone who has admin on one cluster to be able to inspect the incoming `id_token` and use it to exchange for an `mTLS` cert against concierge running on another cluster. I don't believe this is particularly relevant to our Kubeapps' multicluster scenarios (admins are the same across the clusters), but nonetheless, it's worth considering if we want to invest to support this configuration where each concierge's `JWTAuthenticator` has a different audience. 

The key difference in this case is that the `id_token` issued by superviser has a client-id, say of "kubeapps", this explicitly **does not** match the audience known to concierge on each cluster (a unique string used in each `JWTAuthenticator`. So although the interaction begins the same:
	- the request goes through oauth2-proxy to kubeapps-apis and so has the id_token in the request headers,
	- the id_token is then sent with any request to a cluster API server, via `pinniped-proxy`. 
At this point, an extra step is required, where:
	- The id_token provided by the supervisor, is exchanged for a second `id_token` that is specific to the cluster (ie. has the same audience as the JWTAuthenticator on that cluster).
Once the `id_token` with the correct audience is obtained via the new functionality, the last part is then the same, where the new id_token is then exchanged for an `mTLS` cert using concierge on that cluster.

If the above is all correct, then we simply need to decide whether we want to support the ability to use unique audiences for each cluster. Either way, the current use-case of `pinniped-proxy` will still be required (`id_token` to `mTLS` exchange).

**Comment by cfryanr** [comment]
Hi @absoludity, your notes and your conclusions above seem correct to me. Let me know if you have any specific questions.

**Comment by absoludity** [comment]
Thanks for verifying @cfryanr . If we switch to use a different audience per cluster, I'll hit you up with questions then.. for now, the aim was to potentially remove our pinniped-proxy (which exchanges the id_token for an mTLS cert via pinniped) if possible, but that's not possible right now. Cheers.
