### ISSUE TITLE
Update links from master to main branch in bitnami/charts

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/kubeapps#5467]
**Summary**
Update links to bitnami/charts from `master` to `main`.

**Background and rationale**
bitnami/charts has recently swithced from `master` branch to `main` to comply with inclusive terminology guidelines.

**Description**
Update all links available in Kubeapps pointing to the master branch in bitnami/charts and replace the path for the new `main` branch

**Acceptance criteria**
No more links to bitnami/charts `master` branch in Kubeapps.

**Comment by antgamdia** [comment]
When working on this issue, we should also rename the @kubeapps-bot's bitnami/charts fork

**Comment by ppbaena** [comment]
Thanks for the heads-up @antgamdia
