### ISSUE TITLE
Validation issues in the basic forms

### ISSUE THREAD

**Issue by antgamdia** [vmware-tanzu/kubeapps#5520]
**Describe the bug**
As reported offline (Slack), there are some issues when applying validations in the table. Namely:

> I've just spotted a minor UI mishap: when clicking on No the bullet selector vanishes

![image](https://user-images.githubusercontent.com/11535726/196887410-9254581f-023b-4a87-8ba0-5f33ee5fce79.png)
![image](https://user-images.githubusercontent.com/11535726/196887437-7b4a57c4-fd7a-4ff0-b36b-79690e9eea28.png)

> in any case the user won't be able to make a successful deployment if the value is > max (...) tbh I don't have much opinion, I just think that all the controls shall be consistent

![image](https://user-images.githubusercontent.com/11535726/196887925-c799141f-2786-4843-8618-7cbe7d7dec37.png)

**To Reproduce**
1. Use the basic form features with some validation rules.
2. Notice the inconsistencies with the validation enforcing

**Expected behavior**

No inconsistencies in the validation

**Screenshots**
above

**Desktop (please complete the following information):**

- Version: 2.6.0

**Additional context**
N/A

**Comment by antgamdia** [comment]
Additionally, we weren't validating all the fields (eg. arrays). I'll send a PR fixing that problem as well

![image](https://user-images.githubusercontent.com/11535726/196892458-638c1a55-f62c-4d84-84be-9a9658736e59.png)

**Comment by ppbaena** [comment]
Thanks for the checks and fixes.

**Comment by antgamdia** [comment]
Closed by #5533 (merged in main by #5530)
