### ISSUE TITLE
[Multicluster] Add management for clusters in runtime

### ISSUE THREAD

**Issue by castelblanque** [vmware-tanzu/kubeapps#5544]
**Summary**
Add the basics to introduce multiclustering logic in Kubeapps.
It might need to be added into KubeappsAPIs through a separate plugin.

**Background and rationale**
After the multicluster discussion, and having done the proxying of requests (#5468), the next step in the roadmap ([see here](https://docs.google.com/document/d/1qYHIa5dd9qwxTdzyNUn7yXacwmYjH7R-KnnWxXkPItE/edit?pli=1#bookmark=id.o3d1xo2kqvdn)) is to enable the management of clusters through an API.

**Description**
This feature will only be available through a feature flag (e.g. `multicluster.mode=manager`).
The data structure that will hold the cluster information might be a CRD or a ConfigMap.
The API will work with that CRD/CM.
Logic will implement the [defined API operations](https://docs.google.com/document/d/1qYHIa5dd9qwxTdzyNUn7yXacwmYjH7R-KnnWxXkPItE/edit?pli=1#bookmark=id.40ty2yvtjdo4)

**Acceptance criteria**
- Modified Kubeapps chart to enable the multicluster feature according to the feature flag. This will enable only the cluster management by now.
- Added the KubeappsCluster CRD/CM handling to the chart templates
- Created protobuf definition of the clusters management API
- Implementation of the API

**Comment by ppbaena** [comment]
To be revisited if requested when resources available for multi-cluster.
