### ISSUE TITLE
Cannot be added ChartMuseum repo

### ISSUE THREAD

**Issue by xuping962** [vmware-tanzu/kubeapps#5572]
Helm 3.0+ 
Helm Chart 
kubeapps v2.6.0
ChartMuseum 0.15.0

Using a cluster-admin user 
kubectl create serviceaccount kubeapps-operator
kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator

The error is as follows:
An error occurred while creating the repository: AppRepository.kubeapps.com "test" is invalid: status.status: Invalid value: "null": status.status in body must be of type string: "null"

**Comment by antgamdia** [comment]
Thanks for using Kubeapps and reporting the issue.

We are adding a chartmuseum repo as part of our e2e test suite on every pull request/push to `main` and we haven't detected anything wrong.
Could you elaborate a little bit more on how you're adding the repo? Which options are you passing? Do you have a screenshot? Does it happen when `creating` the repo or when `editing` it? 

We're gonna work on https://github.com/vmware-tanzu/kubeapps/issues/5128 soon, so we can take a look at this issue as well once we have more info.
