### ISSUE TITLE
Incorrect swagger spec - reconciliationOptions.interval - invalid value for string type

### ISSUE THREAD

**Issue by ChrisTomAlx** [vmware-tanzu/kubeapps#5609]
**Describe the bug**
The `POST` request for `/apis/core/packages/v1alpha1/installedpackages` throws the following error because the `reconciliationOptions.interval` property in the request body is an integer and not a string, but in the swagger spec, this property is specified to be an integer and this was the case in older chart versions.
 
```js
{"code":3,"message":"proto: (line 1:322): invalid value for string type: 0"}
```

**To Reproduce**

1. Install latest chart
2. Install a helm package using `/apis/core/packages/v1alpha1/installedpackages` and the following body
```js
let body = {
  "param": {
    "availablePackageRef": {
      "context": {
        "cluster": "default",
        "namespace": "kubeapps"
      },
      "identifier": "bitnami/argo-cd",
      "plugin": {
        "name": "helm.packages",
        "version": "v1alpha1"
      }
    },
    "targetContext": {
      "cluster": "default",
      "namespace": "default"
    },
    "name": "argo-cd",
    "pkgVersionReference": {
      "version": "4.3.1"
    },
    "reconciliationOptions": {
      "interval": 0,
      "suspend": true,
      "serviceAccountName": "kubeapps-admin"
    }
  },
  "url": "<base_path>/apis/core/packages/v1alpha1/installedpackages",
  "token": "",
  "kubeAppToken": ""
}
```
4. See the error 
```js
{"code":3,"message":"proto: (line 1:322): invalid value for string type: 0"}
```

**Expected behavior**
This error shouldn't appear as the swagger spec was followed and in the swagger spec `reconciliationOptions.interval` is of value int32 and not string.

**Resolution**
Instead of integer pass string value in `reconciliationOptions.interval`. So in the above body `0` changes to `"0"`.

**Version Info**
- Version latest [2.6.0] from a week back
- Kubernetes version [1.22]

Let me know if I am misunderstanding something or there is anymore context I can provide. For now I will keep it as string and pass but I believe somewhere the code broke that is why it now only accepts string when in the swagger spec it is specified as int32.

**Comment by antgamdia** [comment]
Thanks, @ChrisTomAlx, for the report. Happy to see you are using the Kubeapps API to manage your packages, we can chat in Slack if you wanna share what you're building :) 

The intervals we are using, for both the reconciliation interval (when installing a package) or for the repo sync interval (when adding a new package repository), are strings representing a [Go duration](https://pkg.go.dev/time#ParseDuration). For instance, the valid inputs include: `"0s"`, `"1h"`, `"43m"`, etc

However, as you pointed out, there is an error in our API docs. Thanks for reporting it!

Whereas the autogenetared docs are OK,

https://github.com/vmware-tanzu/kubeapps/blob/05aa30c8d2c8abffab18dc335d805d868bd7c8c6/cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json#L5063-L5070

the file we bundle in the dashboard for providing the interactive API editor is out of sync:

https://github.com/vmware-tanzu/kubeapps/blob/05aa30c8d2c8abffab18dc335d805d868bd7c8c6/dashboard/public/openapi.yaml#L6919-L6927

I will send a PR soon to get both files in sync.

**Comment by ChrisTomAlx** [comment]
Thanks a lot for the quick clarification @antgamdia. I truly appreciate all the work this team is doing. Regarding what we are building, I am not sure if I am allowed to do that so let me take a rain check for now and get back to you at a later time. Hopefully sooner than later.  😄
