### ISSUE TITLE
When I add a private repo, the pod “apprepo-..." reports an error “Error: Error: error converting YAML to JSON: yaml: line 74: mapping values are not allowed in this context”

### ISSUE THREAD

**Issue by xingyunyang01** [vmware-tanzu/kubeapps#5750]
When I add a private repo by "ADD PACKAGE REPOSITORY",  the pod apprepo-default-sync-139793-spark-tqd72--1-qk8z6 CrashLoopBackOff.

log:

root@master:~/go/src/helm# kubectl logs apprepo-default-sync-139793-spark-tqd72--1-qk8z6 -n kubeapps
I1129 02:03:16.587130       1 root.go:32] asset-syncer has been configured with: server.Config{DatabaseURL:"kubeapps-postgresql:5432", DatabaseName:"assets", DatabaseUser:"postgres", DatabasePassword:"REDACTED", Debug:false, Namespace:"default", OciRepositories:[]string{}, TlsInsecureSkipVerify:false, FilterRules:"", PassCredentials:false, UserAgent:"asset-syncer/2.6.1 (kubeapps/2.6.1)", UserAgentComment:"kubeapps/2.6.1", GlobalPackagingNamespace:"kubeapps", KubeappsNamespace:"", AuthorizationHeader:"Basic Y2N6UDFEOlFZRzVtOFhyQ0s=", DockerConfigJson:""}
I1129 02:03:16.777618       1 sync.go:77] Last checksum: 
Error: Error: error converting YAML to JSON: yaml: line 74: mapping values are not allowed in this context

**Comment by absoludity** [comment]
Hi @xingyunyang01 . Sorry for not seeing this earlier. The most likely source of the invalid yaml would be either:
- the index.yaml of your private repo... if you can verify that it is correct, and even if so, check around line 74 in case something unexpected is there, or
- Any extra yaml you added when creating your private repository in Kubeapps?

If you can paste either or both (redacted) that might help us to be able to reproduce the issue too.

Thanks!
