### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by sfxworks** [vmware-tanzu/kubeapps#5821]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5921035/208927141-90c90126-2232-4322-9704-aca97abc1f7a.png)
The display of a slider past 100 units is off. 

**To Reproduce**

1. Create a helm schema with a slider. Example:
```json
                "memory": {
                    "title": "Server Memory",
                    "form": true,
                    "type": "object",
                    "properties": {
                        "initial": {
                            "title": "Initial Memory",
                            "description": "The inital amount of memory in megabytes.",
                            "form": true,
                            "type": "integer",
                            "render": "slider",
                            "sliderMin": 500,
                            "sliderMax": 2400,
                            "sliderStep": 100,
                            "sliderUnit": "M"
                        },
                        "max": {
                            "title": "Max memory",
                            "description": "The MAXIMUM amount of memory in megabytes.",
                            "form": true,
                            "type": "integer",
                            "render": "slider",
                            "sliderMin": 500,
                            "sliderMax": 2400,
                            "sliderStep": 100,
                            "sliderUnit": "M"
                        },
                        "buffer": {
                            "title": "buffer",
                            "form": true,
                            "type": "integer",
                            "render": "slider",
                            "sliderMin": 500,
                            "sliderMax": 2400,
                            "sliderStep": 100,
                            "sliderUnit": "M",
                            "description": "Gives a buffer between java and your absolute max memory. Prevents OutOfMemory issues for your server when it hits a quota."
                        }
                    }
                },
```
2. Deploy the helm chart. (Deployed to our harbor registry in this case)
3. Scroll to the app and deploy it
4. See the slider off the charts

**Expected behavior**
Slider obays step and uses sliderMax to set proper max in display.

**Desktop (please complete the following information):**

- Version 2.6.2
- Kubernetes version v1.25.3
- flux: v0.37.0 helm-controller: v0.27.0

**Additional context**
Also occurred in old display before collapsible menus

**Comment by antgamdia** [comment]
Thanks for reporting the issue. Whereas the slider overflow is indeed a known problem (it is a drawback of https://github.com/vmware-tanzu/kubeapps/pull/5533, in which, once the upper bound is removed, the slider component overflows), I think your problem is different:

We have updated our "basic form" view to fully (or, at least, almost) support JSON Schema instead of coming up with our custom model. This way, custom properties (eg. `sliderMin`) have been replaced with their corresponding ones in JSONSchema (eg.  `minimum`).
I'd say once you update the schema to comply with these changes, the issue should be gone, hopefully. However, there could be still some scenarios where the slider overflows.

> If you cannot edit the schema from its source, you can always install Kubeapps with a special flag to enable a schema editor (`featureFlags.schemaEditor.enabled=true`).

Example of the required changes:

````json

{
    "title": "buffer", // ok
    "form": true, // remove it, not belonging to jsonschema
    "type": "integer", // ok
    "render": "slider", // remove it, not belonging to jsonschema
    "sliderMin": 500, // replace with "minimum" (or "exclusiveMinimum")
    "sliderMax": 2400, // replace with "maximum" (or "exclusiveMaximum")
    "sliderStep": 100, // replace with "multipleOf"
    "sliderUnit": "M", // remove it, not belonging to jsonschema
    "description": "..." // ok
}
````

Let us know if this works for you!

**Comment by ppbaena** [comment]
Hi @sfxworks, this is Pepe Baena engineering manager on Kubeapps. Thank you for your feedback!

We are trying to know more about the usage of Kubeapps by our community members and their organizations. We are moving forward to give better support to our community users, so we would like to know more about them.

I’d like to feature you and Red Hat in the [ADOPTERS.md](https://github.com/kubeapps/kubeapps/blob/main/ADOPTERS.md) file. Would you like to be included? We only need the Red Hat logo (prefer to ask for it to avoid any non-official one) and 1-2 sentences describing how your organization is using Kubeapps. I really appreciate it to promote Kubeapps use cases throughout our amazing open-source community.

Thanks in advance!
