### ISSUE TITLE
[Bug] Installation values formatted incorrectly

### ISSUE THREAD

**Issue by mittalvaibhav1** [vmware-tanzu/kubeapps#5894]
**Describe the bug**
The installation values  are not properly formatted in the yaml format in the installation values section

**To Reproduce**

1. Go to Kubeapps UI and open the details page of any release
3. Scroll down to Installation Values

**Expected behavior**
The installation values should be properly formatted in yaml format

**Screenshots**
Before
<img width="1439" alt="Before" src="https://user-images.githubusercontent.com/53215737/213435128-16aecf15-f7f5-4fba-adee-7e2a3a85b3e1.png">

Created a PR for resolution #5893 

After
<img width="1440" alt="After" src="https://user-images.githubusercontent.com/53215737/213435177-49f9e8f9-240f-4515-bf9a-9a2044ece015.png">

**Desktop (please complete the following information):**

- Version 2.6.2
- Kubernetes version 1.24.3
- Package version default in kubeapps helm chart

**Additional context**

**Comment by absoludity** [comment]
Thanks for the report and fix @mittalvaibhav1 :) I've just re-run the failing e2e tests... I'll investigate them if it's a persistent issue.

**Comment by antgamdia** [comment]
> (...) 'll investigate them if it's a persistent issue.

Yep, yesterday GitHub reported an incident in the actions and other components: https://www.githubstatus.com/incidents/n18j5g7wpg0s
