### ISSUE TITLE
Successful deployment on TKG is inaccessible due to a 404?

### ISSUE THREAD

**Issue by DanPhonovation** [vmware-tanzu/kubeapps#5989]
**Summary**
I'm trying to deploy kubeapps latest helm chart to a Tanzu TKG 1.6 cluster. Supervisor cluster is vsphere with Tanzu.

The release succeeds and all containers are in a running state.  However, when I browse to it I get:

`"Unable to load Kubeapps configuration: {"code":5, "message":"Not Found"}"`

Browser inspection also shows I'm getting a 404 for a POST to `http://my-ingress.com/apis/kubeappsapis.core.plugins.v1alpha1.PluginsService/GetConfiguredPlugins`

And looking at pod logs, I'm not seeing anything that stands out. 

```
NAME: kube-apps
LAST DEPLOYED: Mon Feb 13 12:53:48 2023
NAMESPACE: kubeapps
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: kubeapps
CHART VERSION: 12.2.5-dev0
APP VERSION: DEVEL
```

**Comment by DanPhonovation** [comment]
So I deployed this as a service: LoadBalancer instead of ClusterIP and threw out the ingress. Kubeapps loads now.

I'm using Contour/Envoy as my ingress. I notice its a grpc library making the call to that URL. I'm guessing it has something to do with Contour.

**Comment by absoludity** [comment]
See https://github.com/vmware-tanzu/kubeapps/issues/3716#issuecomment-1067532124 for details of issues running Kubeapps with Envoy (last time I setup and checked).
