### ISSUE TITLE
[regression] Cannot control which chart versions are displayed

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/kubeapps#6020]
In the past we had solved the problem of how to display a useful set of versions to users in #3588, but the issue appears to have regressed and needs investigation:

From @linhvuntu https://github.com/vmware-tanzu/kubeapps/issues/3588#issuecomment-1441225452

So I tried to create a brand new kubeapps with Helm `Package version 12.2.4 / App Version 2.6.3`, and with the config of `{10 10 10}` and the logs are as below

```
I0223 04:40:53.660198       1 root.go:36] "kubeapps-apis has been configured with serverOptions" serverOptions={Port:50051 PluginDirs:[/plugins/helm-packages /plugins/resources] ClustersConfigPath:/config/clusters.conf PluginConfigPath:/config/kubeapps-apis/plugi │ns.conf PinnipedProxyURL:http://kubeapps-internal-pinniped-proxy.kubeapps:3333 PinnipedProxyCACert: GlobalHelmReposNamespace:kubeapps-v3 UnsafeLocalDevKubeconfig:false QPS:50 Burst:100}                                                                               │
I0223 04:40:53.941472       1 server.go:101] +helm NewServer(globalPackagingCluster: [default], globalPackagingNamespace: [kubeapps-v3], pluginConfigPath: [/config/kubeapps-apis/plugins.conf]                                                                         
I0223 04:40:53.941671       1 server.go:112] +helm using custom config: [{{10 10 10} 300 }]                                                                                                                                                                             
I0223 04:40:54.029400       1 server.go:124] +helm NewServer effective globalPackagingNamespace: [kubeapps-v3]                                                                                                                                                          
I0223 04:40:54.030557       1 plugins.go:152] "Successfully registered plugin" pluginPath="/plugins/helm-packages/helm-packages-v1alpha1-plugin.so"                                                                                                                     │
I0223 04:40:54.332092       1 server.go:119] +resources using custom config: [{{ }}]
```

So it seems updated successfully, but when checking the Package Version dropdown list, it still display in with the setting of `{3 3 3}`

The Helm package I'm checking is the public ingress-nginx chart from Kubernetes here: https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

When I check the this chart versions from terminal, it shows full list of versions as below
```
helm search repo ingress-nginx/ingress-nginx -l

NAME                       	CHART VERSION	APP VERSION	DESCRIPTION
ingress-nginx/ingress-nginx	4.5.2        	1.6.4      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.5.0        	1.6.3      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.4.2        	1.5.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.4.1         	1.5.2      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.4.0        	1.5.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.3.0        	1.4.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.5        	1.3.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.4        	1.3.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.3        	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.2        	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.1         	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.2.0        	1.3.0      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.1.4         	1.2.1      	Ingress controller for Kubernetes using NGINX a...
ingress-nginx/ingress-nginx	4.1.3         	1.2.1      	Ingress controller for Kubernetes using NGINX a...

... and more ..
```

But from the Package Version dropdown list in the Kubeapps Dashboards, it show only
```
4.5.2 
4.5.0
4.4.2
4.4.1
4.4.0
4.3.0
3.41.0
3.40.0
3.39.0
.. and more ..
```

For some specific reason, we need to use the Chart version 4.2.5 but it is not displayed.

Do I need to config anything else at the kubeappsController or elsewhere? I have cleared cache, use another laptop to check but it's still the same

**Comment by linhvuntu** [comment]
thanks in advance :)

**Comment by absoludity** [comment]
> thanks in advance :)

Thank you for demoing the issue. So I've reproduced this, and fixed it locally but want to write a test to ensure it's covered (so it can't regress again).

For those interested, the issue was a change that unintentionally loads the config in an inner scope:

https://github.com/vmware-tanzu/kubeapps/blob/969a91c55a6bf751dcc456b7867594ec8fb095ef/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go#L104-L115

So
- on line 106 a variable `pluginConfig` is created 
- on line 108 *two new variables*, `pluginConfig` and `err` are created (`:=`) in the inner scope
- on line 112 we helpfully print out the parsed config
- at line 115 the variables from the inner scope are no longer used, and the variable from line 106 remains empty.

Case of an extra colon :/ and our issue for not testing that properly (I'll do that tomorrow and submit the fix).
