### ISSUE TITLE
Not able to choose/upgrade to old major version from Kubeapps UI.

### ISSUE THREAD

**Issue by ssshreyans26** [vmware-tanzu/kubeapps#6099]
**Describe the bug**
On changing the version, the page is reloading and the version in the UI is not changing to older one.

Unable to fetch package: Unable to get the available package detail for the package "helm-propelld%252Fframework" using the plugin "helm.packages": rpc error: code = Internal desc = Unable to retrieve chart: chart version not found

**To Reproduce**

1. Go to kubeapps 
2. choose the chart you want to deploy
3. choose the older major version (not the latest one)

**Screenshots**
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/37295393/225581408-8e9b9a2a-7a6e-45c3-815c-e0d4fa619388.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/37295393/225582075-337d5bf9-c359-4b23-9155-e419e30f5816.png">

**Desktop :**

- Version 2.6.4
- Kubernetes version 1.24
- Package version 12.2.7

**Comment by absoludity** [comment]
Thanks @ssshreyans26 . Can you please confirm whether you see this bug if you use the standard bitnami repository, and install different versions of, say, the apache chart? I don't see the issue when I choose a chart from the bitnami repo, so I'm interested to know if you do. If you don't, then we can narrow the bug down to something different with your package.

If you're able to reproduce it with a chart, can you add the chart to the bug? Or if you are unable, perhaps create a similarly-named chart with no content which shows the issue and provide that. Or if you're not in a position to do so, we'll try to create a similar chart and see if we can reproduce that way but we don't have a lot of resources right now.

**Comment by absoludity** [comment]
Great, that's helpful info, thanks. Also worth noting that we use chart-museum in our CI/CD integration tests without issue too. So if you can take one of your charts, reduce it and anonymize it (rie. removing templates and other things, anonymizing any info in the Chart.yaml), until you've a small example chart you can share that causes this issue, we can then reproduce it with your example chart, find the issue and fix it.

**Comment by absoludity** [comment]
Hi @Shreyans Sonthalia. The issue closed automatically because it was waiting for info... in particular, the last comment from me was asking for a sample chart that we could reproduce the issue with. But I think the new info which you've said above is that you're not using semantic versioning for the charts? This came up with another project recently too. So Helm requires a semantic version for charts for a reason (see https://helm.sh/docs/topics/charts/#the-chartyaml-file ), and currently Kubeapps depends on that requirement to be able to suggest when a new version of the chart is available. Is there a reason you're not using semantic versions when Helm requires it? (If you and others have a decent reason, we can look at what we could do to support that use-case).

**Comment by ssshreyans26** [comment]
> From [slack](https://kubernetes.slack.com/archives/C9D3TSUG4/p1683275967631179):
> 
> Hi @ssshreyans26 . The issue closed automatically because it was waiting for info... in particular, the last comment from me was asking for a sample chart that we could reproduce the issue with. But I think the new info which you've said above is that you're not using semantic versioning for the charts? This came up with another project recently too. So Helm requires a semantic version for charts for a reason (see https://helm.sh/docs/topics/charts/#the-chartyaml-file ), and currently Kubeapps depends on that requirement to be able to suggest when a new version of the chart is available. Is there a reason you're not using semantic versions when Helm requires it? (If you and others have a decent reason, we can look at what we could do to support that use-case).

Hi @absoludity,  All our applications are used internally and there is no external dependency, that is why we are using simple versioning. Semantic Versioning would increase the complexity in our use case.  

Can you provide us with a workaround for this?

**Comment by absoludity** [comment]
Hi @ssshreyans26 . I have tried to reproduce the problem locally, uploading two charts to chartmuseum as follows:

- simplechart v0.1.0 (app version v1.0.0)
- simplechart v0.1.1 (app version v1.1.0)

and can't reproduce the issue. As [requested above](https://github.com/vmware-tanzu/kubeapps/issues/6099#issuecomment-1487426811), if you can provide two example charts (just anonymize and strip down the internal charts that demonstrate this issue, then verify you can reproduce the issue with your stripped down charts, then upload them here for me to try), then I'd be happy to dig further and see why you are experiencing the "Unable to fetch package" error with your charts.

**Comment by ssshreyans26** [comment]
> Hi @ssshreyans26 . I have tried to reproduce the problem locally, uploading two charts to chartmuseum as follows:
> 
> * simplechart v0.1.0 (app version v1.0.0)
> * simplechart v0.1.1 (app version v1.1.0)
> 
> and can't reproduce the issue. As [requested above](https://github.com/vmware-tanzu/kubeapps/issues/6099#issuecomment-1487426811), if you can provide two example charts (just anonymize and strip down the internal charts that demonstrate this issue, then verify you can reproduce the issue with your stripped down charts, then upload them here for me to try), then I'd be happy to dig further and see why you are experiencing the "Unable to fetch package" error with your charts.

@absoludity As per your request attaching two example charts here.
`apiVersion: v2
appVersion: v11-master-8204c85
description: A Helm chart for Propelld Service
name: communication-infra-service
type: application
version: v11-master`

`apiVersion: v2
appVersion: v12-master-eeb151e
description: A Helm chart for Propelld Service
name: communication-infra-service
type: application
version: v12-master`

**Comment by absoludity** [comment]
Thanks @ssshreyans26 , that info enabled me to reproduce the issue, track down the actual problem and fix it. Done in #6249

**Comment by ssshreyans26** [comment]
@absoludity Thanks for the fix! When can we expect a release for this?

**Comment by absoludity** [comment]
Possibly next week, but more likely later. But I'll let you know as soon as the dev image is built with the fix (just having a few issues with CI) and give you instructions so you can test that image to ensure it fixes your issue, until the next release.

**Comment by absoludity** [comment]
You can try [this image](https://hub.docker.com/layers/kubeapps/kubeapps-apis/latest/images/sha256-fcfd9948343234f8fcd2a85525b204c06c0e1ad326f2e4c31a4ac55a275b72d5?context=explore) to verify that it fixes your problem (and perhaps use that until the next release), which should mean something like the following in your values.yaml:
```yaml
kubeappsapis:
  image:
    repository: kubeapps/kubeapps-apis
    digest: sha256:fcfd9948343234f8fcd2a85525b204c06c0e1ad326f2e4c31a4ac55a275b72d5
```

Let us know if that fixes your issue.

**Comment by ssshreyans26** [comment]
***@***.*** ***@***.***> ***@***.***
***@***.***> ***@***.*** ***@***.***>
***@***.*** ***@***.***>

**Comment by ssshreyans26** [comment]
> You can try [this image](https://hub.docker.com/layers/kubeapps/kubeapps-apis/latest/images/sha256-fcfd9948343234f8fcd2a85525b204c06c0e1ad326f2e4c31a4ac55a275b72d5?context=explore) to verify that it fixes your problem (and perhaps use that until the next release), which should mean something like the following in your values.yaml:
> 
> ```yaml
> kubeappsapis:
>   image:
>     repository: kubeapps/kubeapps-apis
>     digest: sha256:fcfd9948343234f8fcd2a85525b204c06c0e1ad326f2e4c31a4ac55a275b72d5
> ```
> 
> Let us know if that fixes your issue.

@absoludity Thanks for the fix, it's solving our problem.
