### ISSUE TITLE
Path hosted kubeapps behind Ingress provided by nginx on AKS

### ISSUE THREAD

**Issue by TWBrown42** [vmware-tanzu/kubeapps#6314]
**Summary**
My aim is to set up a demonstrator taking Kubeapps, deploying behind an nginx ingress controller on AKS with OIDC provided by Keycloak which is running on the same cluster in its own Namespace.  The intention will be to show authentication and authorisation based on Keycloak.  However, after Authentication in Keycloak and redirection back to kubeapps I am faced with:-
"Unable to load kubeapps configuration".

**Background and rationale**
I am providing a single Ingress Proxy for the cluster and given kubeapps Chart and the Keycloak charts I have two paths the route to the backend services:-
https://MyDomainName/Apps/  this routes to cubes
https://MyDomainName/Auth/ this routes to the Keycloak instance

**Description**
I have created a TLS end point and have used your chart (v 12.4.*) to define a path.  When I launch KubeApps at this defined path I am correctly directed to the OAuth2-Proxy which in turn correctly sends me to my KeyCloak authorisation end point.  On return I get "Unable to load Kubeapps configuration:" .  When I look at the network trace in Chrome I see the last call with a non-200 response is a 404.  The client is attempting to POST to https://MydomainName/apis/kubeappsapis.core.plugins.v1alpha1.PluginsService/GetConfiguredPlugins.

Given the Path I have set in the chart it is no surprise that this URL is returning a 404,  I would have thought I would be expecting the API call made to be:-
https://MyDomainName**/apps/**apis/kubeappsapis.core.plugins.v1alpha1.PluginsService/GetConfiguredPlugins 

This feels like I am missing something fundamental, or perhaps this 404 is not related to the Error.

**Additional context**
I have spent quite a few days looking at this and have of course searched through your documentation but have failed to come up with a match.  Any suggestions would be appreciated and of course I can provide more information at your request.

**Comment by absoludity** [comment]
Hi @TWBrown42 . Normally the "Unable to load kubeapps configuration" would be associated with the request to load the `config.js` file from the server, but it could be for the same reason (ie. a 404) (and yes, you'd see similar 404s for other endpoints if so).

Can you please share a scrubbed version of your values.yaml? We can then try to reproduce. I'm assuming you've seen the FAQ for [serving Kubeapps under a subpath](https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/README.md#serving-kubeapps-in-a-subpath), but it could also be that an issue has been re-introduced, so I'd like to try to reproduce if I can (we did have an issue re-introduced once before with #3369 , but that was different from what you're experiencing).

**Comment by absoludity** [comment]
Note to self: We may have accidentally broken the support for serving Kubeapps from a subpath when switching to the new gRPC client (#6044), where we set an absolute URL:

https://github.com/vmware-tanzu/kubeapps/blob/3669dd4ce16e99ee32abe72569ae25e668a2ef1f/dashboard/src/shared/KubeappsGrpcClient.ts#L39

Unfortunately we don't have a CI integration test using a subpath.

@TWBrown42 One work-around for now would be to avoid serving Kubeapps from a subpath for now, if that's possible.

**Comment by deloitte-jcatana** [comment]
Any updates on this? Running into same issue.

**Comment by absoludity** [comment]
No updates (low on resources at the moment) but re-opening, since I do want to verify what I said above which may show an easy fix. For now, I can only suggest either serving Kubeapps without a subpath, or if you have developers on your team, seeing if they can take a look. We should be able to take a look at a few issues like this next iteration.

**Comment by jcatana** [comment]
Fixed it. One character change to make it use relative pathing instead of static and allow URL subpath to function.
https://github.com/jcatana/kubeapps/tree/url_subpath_issue_6314 
I'll open a PR once I figure out how to set up all the hoops this project has to contributing.

**Comment by absoludity** [comment]
Thanks @jcatana for giving it a go! If all the CI tests pass we can go ahead and land it. I'll comment with more on the PR.
