### ISSUE TITLE
Installed Value without comment 

### ISSUE THREAD

**Issue by mussa572** [vmware-tanzu/kubeapps#6508]
**Summary**

Currently, when we use the `GetAvailablePackageDetail` API, it returns the values of the installed Helm chart in JSON format. JSON does not support comments, making it difficult for users to follow without comments as they can do with the values.yml file. Additionally, due to the JSON format, the line numbers change when comparing with values.yml files, which becomes very difficult to handle.

**Background and rationale**
The reason behind this change is that it becomes very difficult to display and compare the installed values with the values.yml file

**Description**
Please consider updating the `GetAvailablePackageDetail` API to return the installed values in YAML format instead of JSON, including the comments that are normally available in the values.yml file. Additionally, ensure that the line numbers of the key/values are on the same level as the original values.yml file. This will make it much easier to compare the installed and package values.

**Comment by absoludity** [comment]
Hi @mussa572 . The `GetAvailablePackageDetail` doesn't return the installed values, so I'm guessing you mean the `GetInstalledPackageDetail`, which does indeed return the installed values (without comments). Note that the API returns the helm release data (the installed values) from the secret that Helm creates, which is JSON, so there are no comments there for Kubeapps to get. I agree it would be nice if the backend merged those installed values into the (commented) yaml for users of the API. At the moment, the Kubeapps dashboard does this on the frontend to present the merged values to the user. There was an issue in the past where this was discussed, but I can't find it right now.
