### ISSUE TITLE
Google Artifact Registry-based helm chart is not defaulting to latest version

### ISSUE THREAD

**Issue by RGPosadas** [vmware-tanzu/kubeapps#6584]
**Describe the bug**
GAR repo is not showing the latest release as default.

**To Reproduce**

1. Have kubeapps configured to use Artifact Registry as an initial repo
```yaml
    initialRepos:
      - name: gar
        url: <redacted>
        basicAuth:
          user: <redacted>
          password: <redacted>
        namespace: my-ns
        type: oci
        ociRepositories:
          - k8s-repo/my-chart
```
2. On `Catalog` view, it is not showing the latest release
![image](https://github.com/vmware-tanzu/kubeapps/assets/33991121/239c3a97-cba8-4763-a7c2-8f9631d909a0)

3. On `Deploy` view, it is also not showing the latest release
   - Note that all releases are uploaded to GAR in the correct order for the non-dev official release versions
   - From what we've noticed, the chosen version is random
   - When new releases are uploaded to GAR, it _could_ choose a new "default" version, and it may or may not be the correct latest release
![image](https://github.com/vmware-tanzu/kubeapps/assets/33991121/ec0ca79b-4fd4-4b21-be3d-c695af3c3e61)

4. View `kubeappsapis` logs:
   - On `Catalog` view
   ```sh
   I0807 19:38:23.367869       1 packages.go:60] "+core GetAvailablePackageSummaries" cluster="default" namespace="my-ns"
   I0807 19:38:23.367979       1 server.go:201] "+helm GetAvailablePackageSummaries" cluster="default" namespace="my-ns"
   I0807 19:38:23.592364       1 repositories.go:117] "+core GetPackageRepositorySummaries" cluster="default" namespace=""
   I0807 19:38:23.592438       1 server.go:1143] +helm GetPackageRepositorySummaries [cluster:"default"]
   I0807 19:38:23.592552       1 repositories_resources.go:31] +helm getPkgRepositoryResource [&{0xc00038e6a0  {kubeapps.com v1alpha1 apprepositories}}]
   ```
   - On `Deploy` view, note that while it is logging `(latest version)`, it is actually not the correct latest version
   ```sh
   I0807 19:39:24.829848       1 packages.go:109] "+core GetAvailablePackageDetail" cluster="default" namespace="my-ns"
   I0807 19:39:24.829919       1 server.go:287] "+helm GetAvailablePackageDetail" cluster="default" namespace="my-ns"
   I0807 19:39:24.877494       1 server.go:317] Requesting chart 'gar/k8s-repo%2Fmy-chart' (latest version) in ns 'my-ns'
   ```
   - When selecting the correct latest version:
   ```sh
   I0807 19:41:48.651615       1 packages.go:109] "+core GetAvailablePackageDetail" cluster="default" namespace="my-ns"
   I0807 19:41:48.651672       1 server.go:287] "+helm GetAvailablePackageDetail" cluster="default" namespace="my-ns"
   I0807 19:41:48.708732       1 server.go:320] Requesting chart 'gar/k8s-repo%2/Fmy-chart' (version 4.0.0-cct-1200) in ns 'my-ns'
   ```

**Expected behavior**
We expect the latest semver version of a chart to be the default version when deploying a release.

**Desktop (please complete the following information):**

- Version: 2.8.0
- Kubernetes version: v1.24.12-gke.1000
- Config:
   <details>
   <summary>config.json</summary>

   ```json
   {
     "kubeappsCluster": "default",
     "kubeappsNamespace": "apps",
     "helmGlobalNamespace": "apps",
     "carvelGlobalNamespace": "kapp-controller-packaging-global",
     "appVersion": "v2.8.0",
     "authProxyEnabled": true,
     "oauthLoginURI": "/oauth2/start",
     "oauthLogoutURI": "/oauth2/sign_out",
     "authProxySkipLoginPage": false,
     "featureFlags": {"apiOnly":{"enabled":false,"grpc":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"GRPC"}}},"operators":false,"schemaEditor":{"enabled":false}},
     "clusters": ["default"],
     "theme": "",
     "remoteComponentsUrl": "",
     "customAppViews": [],
     "skipAvailablePackageDetails": false,
     "createNamespaceLabels": {}
   }
   ```
   
   </details>

- Plugins:
   <details>
   <summary>plugins.conf</summary>

   ```json
    {
      "core": {
        "packages": {
          "v1alpha1": {
            "timeoutSeconds": 300,
            "versionsInSummary": {
              "major": 3,
              "minor": 6,
              "patch": 8
            }
          }
        }
      },
      "flux": {
        "packages": {
          "v1alpha1": {
            "defaultUpgradePolicy": "none",
            "noCrossNamespaceRefs": false
          }
        }
      },
      "helm": {
        "packages": {
          "v1alpha1": {
            "globalPackagingNamespace": ""
          }
        }
      },
      "kappController": {
        "packages": {
          "v1alpha1": {
            "defaultAllowDowngrades": false,
            "defaultUpgradePolicy": "none",
            "globalPackagingNamespace": "kapp-controller-packaging-global"
          }
        }
      },
      "resources": {
        "packages": {
          "v1alpha1": {
            "trustedNamespaces": {
              "headerName": "",
              "headerPattern": ""
            }
          }
        }
      }
    }
   ```
   
   </details>

**Comment by absoludity** [comment]
Thanks for the report @RGPosadas . Note that "4.0.0-cct-1200" is a pre-release version (see point 9 at https://semver.org/#semantic-versioning-specification-semver ) not a latest version, but I do also see you've got a version "3.1.4" which *should* be the latest version, rather than "3.1.3".

Notes: The log "Requesting chart (latest version)" is printed when a specific version is not requested - the call actually fetches all the versions that it knows about for that repo, then we filter it according to the configurued versions in summary, so what you're seeing in that list is meant to be the latest 3 major versions with the latest 3 minor with the latest 3 patch versions.

It's possible there's an issue in the filtering of that version summary in the frontend dashboard (eg. because there's a pre-release version for both 4.0.0 and 3.1.4, it's incorrectly not considering the non-pre-release 3.1.4 and choosing 3.1.3 - not sure, need to check.

**Comment by antgamdia** [comment]
Besides, I'm noticing there is no `appVersion` in those charts ([example](https://github.com/bitnami/charts/blob/main/bitnami/wordpress/Chart.yaml#L15)). Perhaps (haven't checked it), the faulty UI behavior has something to do with it.

<details><summary>Example of the bitnami/apache chart, with appVersion, working properly</summary>

![image](https://github.com/vmware-tanzu/kubeapps/assets/11535726/783f14c9-6076-4abe-8508-a3c6f52482cc)


</details>

**Comment by RGPosadas** [comment]
@absoludity Ah yes that's my bad as I was not clear, you are correct - I was expecting either the latest pre-release (4.0.0-cct-1200) or the latest release (3.14) to be the default chart version, instead of 3.13.

@antgamdia Thank you for finding the root cause! Let me know if you need further info 🚀

**Comment by antgamdia** [comment]
@RGPosadas I have just sent a PR aimed at fixing it: https://github.com/vmware-tanzu/kubeapps/pull/6588
Thanks for your detailed report of the issue :) 

![image](https://github.com/vmware-tanzu/kubeapps/assets/11535726/b1b94c9f-6a1a-459c-afb7-3da11d983005)

**Comment by absoludity** [comment]
Thanks Antonio. In the screenshot, it's displaying the pre-release version, does that mean that it'll also prompt people to upgrade to the pre-release version by default? I'm not convinced we should be doing that. We should see 3.1.4 IMO, but  I'll comment with more context on the PR.

**Comment by RGPosadas** [comment]
Thanks for the speedy work @antgamdia 🚀 
Would you know when this change will be released?
Also, is there an image tag I could use to test the changes?

**Comment by antgamdia** [comment]
@RGPosadas, anytime; happy to get rid of those bugs :)

We don't have a release date in mind (we are finishing some work on the new `oci-catalog` component and we'd like to get it done before releasing).
However, you can always get the latest version of any Kubeapps component by switching to the images built by our CI (albeit totally discouraged in production environments). For instance, using [`kubeapps/dashboard:latest` image](https://hub.docker.com/r/kubeapps/dashboard/tags) you'll already get this fix.

**Comment by RGPosadas** [comment]
Thanks, will play around with the latest release on our test env.
