### ISSUE TITLE
Empty catalog using fluxcd

### ISSUE THREAD

**Issue by alvistar** [vmware-tanzu/kubeapps#6863]
**Describe the bug**
I am using a k3s cluster with fluxcd installed. I have installed kubeapps with helm.

I can manage to see installed helm charts, but I cannot see any app in catalog

**To Reproduce**

1. Go to catalog on top bar
2. "The current catalog is empty."

**Expected behavior**
See catalog from helmrepositories resources

**Screenshots**

**Desktop :**

- Version [e.g. 2.8.0]
- Kubernetes version [e.g. 1.27.5]

**Additional context**
I see some activities on log pod:

...
      {
        "manager": "source-controller",
        "operation": "Update",
        "apiVersion": "source.toolkit.fluxcd.io/v1beta2",
        "time": "2023-09-17T06:09:12Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:finalizers": {
              ".": {},
              "v:\"finalizers.fluxcd.io\"": {}
            }
          }
        }
      },
      {
        "manager": "source-controller",
        "operation": "Update",
        "apiVersion": "source.toolkit.fluxcd.io/v1beta2",
        "time": "2023-09-21T14:49:51Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:status": {
            "f:artifact": {
              ".": {},
              "f:digest": {},
              "f:lastUpdateTime": {},
              "f:path": {},
              "f:revision": {},
              "f:size": {},
              "f:url": {}
            },
            "f:conditions": {},
            "f:observedGeneration": {},
            "f:url": {}
          }
        },
        "subresource": "status"
      }
    ]
  },
  "spec": {
    "url": "https://immich-app.github.io/immich-charts",
    "interval": "5m0s",
    "timeout": "1m0s",
    "provider": "generic"
  },
  "status": {
    "observedGeneration": 1,
    "conditions": [
      {
        "type": "Ready",
        "status": "True",
        "observedGeneration": 1,
        "lastTransitionTime": "2023-09-21T14:49:51Z",
        "reason": "Succeeded",
        "message": "stored artifact: revision 'sha256:d3980ddd4e3d2ee6c0b898a94c0040d937e8083dfc8024635185010da329276a'"
      },
      {
        "type": "ArtifactInStorage",
        "status": "True",
        "observedGeneration": 1,
        "lastTransitionTime": "2023-09-18T11:20:05Z",
        "reason": "Succeeded",
        "message": "stored artifact: revision 'sha256:d3980ddd4e3d2ee6c0b898a94c0040d937e8083dfc8024635185010da329276a'"
      }
    ],
    "url": "http://source-controller.flux-system.svc.cluster.local./helmrepository/apps/immich/index.yaml",
    "artifact": {
      "path": "helmrepository/apps/immich/index-d3980ddd4e3d2ee6c0b898a94c0040d937e8083dfc8024635185010da329276a.yaml",
      "url": "http://source-controller.flux-system.svc.cluster.local./helmrepository/apps/immich/index-d3980ddd4e3d2ee6c0b898a94c0040d937e8083dfc8024635185010da329276a.yaml",
      "revision": "sha256:d3980ddd4e3d2ee6c0b898a94c0040d937e8083dfc8024635185010da329276a",
      "digest": "sha256:e51d5764f104cda8e7c471e5ee424f72d72d6b242b0907dd3abb0dad7d273fcb",
      "lastUpdateTime": "2023-09-18T11:20:05Z",
      "size": 6542
    }
  }
}]
I0922 07:19:39.352919       1 watcher_cache.go:613] Redis [DEL helmrepositories:apps:immich]: 0
I0922 07:19:39.352952       1 watcher_cache.go:574] -syncHandler(helmrepositories:apps:immich)
I0922 07:19:39.352991       1 watcher_cache.go:299] -processNextWorkItem()
I0922 07:19:39.353010       1 watcher_cache.go:254] +processNextWorkItem()
I0922 07:19:39.363911       1 watcher_cache.go:660] "+fetch" key="helmrepositories:apps:immich"
I0922 07:19:39.364495       1 server.go:224] -fluxv2 GetAvailablePackageSummaries

but it looks like that redis is never populated. 

Other things I could look at?

**Comment by kvaps** [comment]
Hi, I have the same issue

**Comment by absoludity** [comment]
Sorry @alvistar , we missed triaging this issue at the time. Thanks @kvaps for not only updating the issue, but identifying the problem and having a go at fixing it! For the record, [I've left a detailed analysis built on @kvaps's findings on the PR](https://github.com/vmware-tanzu/kubeapps/pull/7132#issuecomment-1826970455).
