### ISSUE TITLE
Open links of "installation notes" in new tab

### ISSUE THREAD

**Issue by Palollo** [vmware-tanzu/kubeapps#6891]
**Background and rationale**
The developer of a helm chart, usually puts the link to access to the deployed application in the `Notes.txt`, which is read as markdown and rendered in the "Installation notes" panel of the application details web page of kubeapps. That link or any other in this notes usually goes to another web page and, in my opinion, should be openned in a new browser tab or window.

**Description**
Open links of "Installation notes" as external, usually in a new tab, but it is up to the browser configuration, just adding the property `target="_blank"` to the <a> tag is enough.

**Acceptance criteria**
If you think this is not the desirable default behaviour, I suggest to add some option to enable this mode.

**Additional context**
I tried directly writing the html code like:
```
<a href="" target="_blank">link</a>
```
And is well rendered as a link, but the property `target` disappears.

**Comment by antgamdia** [comment]
Hi, thanks for the proposal! 
From memory, I'd say it can be tweaked at
https://github.com/vmware-tanzu/kubeapps/blob/2cb6c8a7f1e824a8ba851d48a316417cf6d49c8f/dashboard/src/components/MarkdownRenderer/LinkRenderer.tsx#L8
Feel free to give it a try and send a PR :P

**Comment by vash-knives** [comment]
@antgamdia , i can take this issue if nobody has.

**Comment by antgamdia** [comment]
Sure, go ahead. Thanks!

**Comment by vash-knives** [comment]
@antgamdia , sent a PR
