### ISSUE TITLE
Support for activeDeadlineSeconds extraFlag for AppRepository CronJobs

### ISSUE THREAD

**Issue by rophy** [vmware-tanzu/kubeapps#6966]
**Summary**

I see [ttlSecondsAfterFinished](https://github.com/vmware-tanzu/kubeapps/blob/a6843f48f8e43224e4b9a4f068447d05217310cb/cmd/apprepository-controller/cmd/root.go#L92) is supported as an extraFlags. Can we add the same for [activeDeadlineSeconds](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup)?

**Background and rationale**

Some kubernetes clusters may require CronJob to define [activeDeadlineSeconds](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup).

**Acceptance criteria**

Able to define `activeDeadlineSeconds` in .Values.apprepository.extraFlags, which gets added to result CronJob of AppRepository.

**Comment by absoludity** [comment]
Thanks @rophy - makes sense. Assigning to you since you've already done a PR ... I'll add more feedback there.
