### ISSUE TITLE
Diff Editor no longer works with version 2.10.0

### ISSUE THREAD

**Issue by ILZ1105** [vmware-tanzu/kubeapps#7704]
**Describe the bug**
The Diff Editor to compare modified values with the package values no longer works. It doesn't compare the values anymore, it only shows the already modified values with the potential new values of the Helm but there is no comparison (red/green) anymore.

**To Reproduce**

1. Upgrade from 2.8.0 to 2.10.0
2. Try upgrading any deployed application within kubeapps and the check the diff editor (you can even use kubeapps itself)
3. No green/red lines will show up anymore

**Expected behavior**
Diff editor still shows the red/green lines for comparison.

**Screenshots**
None

**Desktop (please complete the following information):**

- Kubeapps Version 2.10.0
- Kubernetes version 1.26.5
- Package version Helm Chart 15.0.2

**Additional context**
None

**Comment by antgamdia** [comment]
Thanks for reporting it; it is odd since we have some automatic e2e tests checking the diff view, but we will look into it soon.

**Comment by ILZ1105** [comment]
It's odd indeed, I was checking through the logs to find any kind of error but it's a bit tricky as I have numerous issues at once with 2.10.0 that I'm still looking into. One of the bigger issues seems to relate to postgresql https://github.com/vmware-tanzu/kubeapps/issues/7702 which caused quite a bunch of problems with synching the repos. I even had to manually delete the entry in the DB of the synched chart (the hash value) to be able to sync bitnami again. I rolled back to 2.8.0 and upgraded to 2.10.0 again and it was fine this time, though the DB was still overloaded because I couldn't increase the CPU for it as described in the bug.

There might be a chance it's related to that?

**Comment by ILZ1105** [comment]
More info to this case, it's a Google Chrome only issue. Tested with the current most recent version:
127.0.6533.73

Both Firefox and Edge are fine (haven't tested other browsers).

**Comment by ILZ1105** [comment]
Good old Cookie Issue... case closed.
