### ISSUE TITLE
kubeapps Pacakage repository Not working with OCI based harbor artifacts

### ISSUE THREAD

**Issue by vijimgowda** [vmware-tanzu/kubeapps#7862]
**Summary**
kubeapps not able to sync charts from package repository for OCI based charts
steps followed
> pushed helm chart to harbor  ( stored as OCI ) 
        > Goto add Package Repository
        > Add OCI harbor "URL" 
        > select "Packaging Format" as "Helm Charts"
        > selected "Scope" as Namespaced repository (using the "$namespace" namespace)
        > Selected "Package Storage Type" "OCI Registry"
        > Selected "Authentication"   "Basic Auth"   ( Username and Password ) 
        > Added "Filtering"  "List of repository"  ( my oci repository name ) 
        > submitted "INSTALL REPOSITORY"
          > Package Repository successfully added and appeared in "Namespaced Repositories:"

Issue :

Not visible in  Catalog option and upgrade option not shown in Application Tile 
<img width="308" alt="upgrade_button_disabled" src="https://github.com/vmware-tanzu/kubeapps/assets/51625569/9ea4627b-70ae-4526-9480-90e66ffe3b04">
<img width="389" alt="catalog_issue" src="https://github.com/vmware-tanzu/kubeapps/assets/51625569/402f1269-68c6-4e87-aa0b-3b8dfea9f93d">

**Comment by vijimgowda** [comment]
Any update on this issue

**Comment by vijimgowda** [comment]
#4670 Team help us to resolve above issue

**Comment by beltran-rubo** [comment]
This is not supported in Kubeapps right now. This was implemented for Bitnami Helm charts in DockerHub in a previous version:

> Kubeapps v2.9.0 (chart version 14.0.1) is a minor release that fixes some bugs and introduces working support for listing a catalog of apps when your charts are stored in an OCI registry (without having to list them manually). Specifically, this release supports registries on dockerhub, such as Bitnami's "oci://registry-1.dockerhub.io/bitnamicharts". This feature is behind a flag ociCatalog.enabled=true until we support more registries.
