### ISSUE TITLE
Failed to update an application

### ISSUE THREAD

**Issue by anjuchaurasiya** [vmware-tanzu/kubeapps#7891]
**Describe the bug**
My goal is to update an application from tractusX repo (https://eclipse-tractusx.github.io/charts/dev), but is failing after selecting the package version 5.0.1

**To Reproduce**
Create a repo in kubeapps for TractusX (https://eclipse-tractusx.github.io/charts/dev), install the bpdm chart version 4.0.2 and try to update it to 5.0.1 package version

**Expected behavior**
It should upgrade the package to 5.0.1

**Screenshots**

**Desktop (please complete the following information):**

- Kubeapps [v2.9.0]
<img width="1506" alt="Screenshot 2024-07-12 at 5 50 59 PM" src="https://github.com/user-attachments/assets/aa6e8b93-3125-49e4-aab6-5888ebb344db">

**Additional context**

**Comment by beltran-rubo** [comment]
That looks an issue in the tractusX Helm chart itself, not related to Kubeapps. Please report at the TractusX GitHub project itself.
