### ISSUE TITLE
Not able to upgrade a app from locally hosted chartmuseum

### ISSUE THREAD

**Issue by martinmlouis** [vmware-tanzu/kubeapps#8056]
**Summary**
I installed apache from a local chartmuseum repo in a namespace "nginx". Then I tried to upgrade it gives error 

**Background and rationale**
Not sure what permission is missing

**Description**
An error occurred: Unable to update the installed package for the package "apache" using the plugin "helm.packages": permission_denied: Missing permissions internal: Unable to fetch the chart apache from the namespace "kubeapps": chart download request failed.

Please help in getting this as this is valuable to our team CI/CD

**Comment by martinmlouis** [comment]
I tested a new chart by making a local chart and uploading to chartmuseum and it works fine. The issue if the I downloaded a bitnami chart and uploaded to local chartmuseum and it gave that error. I will keep posted on what I find. So for now it is fine.Thanks

**Comment by beltran-rubo** [comment]
Thanks for sharing your findings. Please reopen it if you have more info related to this.
