### ISSUE TITLE
Helm values override?

### ISSUE THREAD

**Issue by aceeric** [vmware-tanzu/kubeapps#8128]
**Summary**

Typically when one installs a Helm app, a values override is provided which has a small subset of the full chart values. E.g.: `--values myfile.yaml`.

Has there been discussion of supporting this in Kubeapps?

**Background and rationale**

Simplifies installation for the person deploying the app in the cluster.

**Description**

Conceptually - the _Deploy_ page for a Helm app would offer two modes:
1. Inline editing of the full values in the Chart  (the current mode)
2. Ability to paste or edit a blank values field that Kubeapps handles just like `helm install --values <override>`

Thanks for considering.

**Comment by beltran-rubo** [comment]
Thanks for the suggestion, we will keep in mind for future improvements.
