### ISSUE TITLE
An error occurred while fetching the catalog: Unable to get the available package detail for the package "bitnami/mysql" using the plugin "helm.packages": internal: Unable to retrieve chart files: sql: no rows in result set. 

### ISSUE THREAD

**Issue by fea359** [vmware-tanzu/kubeapps#8153]
### Name and Version

bitnami/mysql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I searched for mysql, tomcat, and redis using kubeapps, I was able to find these applications, but when I deployed them, it prompted: "An error occurred while fetching the catalog: Unable to get the available package detail for the package "bitnami/mysql" using the plugin "helm.packages": internal: Unable to retrieve chart files: sql: no rows in result set."
But helm search was able to search and install them.
I found the mysql record in the database files, and indeed did not find the record of 12.1.0, but I found the record of 12.0.0, and then I changed 12.0.0 to 12.1.0 and it succeeded. There are many similar situations, such as redis-cluster.
The root cause is that the records in the files table in PostgreSQL have not been updated in a timely manner.
This problem is easy to reproduce. For any installed or newly installed kubeapps, the same error will appear when searching for mysql, because after Syncing Package Repositories is completed, there is no latest sql record in postgres.

### Are you using any custom parameters or values?

no

### What do you see instead?

![image](https://github.com/user-attachments/assets/0119cb4b-fe11-4999-927e-bcf694727da2)
![image](https://github.com/user-attachments/assets/137a8cd4-ebef-4e50-9fbe-c922650acc32)
![image](https://github.com/user-attachments/assets/5747a51b-72b0-460c-b997-904ba43d94a8)
![image](https://github.com/user-attachments/assets/68b5a3de-e593-4806-a848-e357ad0ce940)
![image](https://github.com/user-attachments/assets/3956d556-0e5c-4638-b348-e27dbc9aaa48)
![image](https://github.com/user-attachments/assets/bfa3b214-4417-4712-be60-94908aa5ea98)
![image](https://github.com/user-attachments/assets/5f28c137-00b0-4c60-ac77-f49df1c078a9)
![image](https://github.com/user-attachments/assets/a92bd93d-7635-4d93-8869-2f61f0d37973)

The following is the page that can be accessed normally after modification
![image](https://github.com/user-attachments/assets/dbd4ff74-77be-4362-8b67-f5c266f96d62)

Kubeapps accesses lastest by default, but there is no latest record in postgres, so this error is reported. I have confirmed that Syncing Package Repositories is completed
The problem is that the kubeapps scheduled task apprepo-kubeapps-sync cannot pull the latest data when pulling data from https://charts.bitnami.com/bitnami and storing it in postgresql.

The same problem also exists in nginx. The last version 18.2.6 is not recorded in the database, but 18.2.5 is, so it is possible to directly modify the URL to 18.2.5. This is obviously a BUG.

For example: http:kubeapps:80/proxy/#/c/default/ns/test/packages/helm.packages/v1alpha1/default/kubeapps/bitnami%2Fnginx/versions/18.2.6 Modified to: http:kubeapps:80/proxy/#/c/default/ns/test/packages/helm.packages/v1alpha1/default/kubeapps/bitnami%2Fnginx/versions/18.2.5

![image](https://github.com/user-attachments/assets/d6bdc460-ba44-4905-895b-bd5e21d8c891)

![image](https://github.com/user-attachments/assets/e76c60c3-e88c-4b14-b341-424a1da1e232)

**Comment by pmiriyev** [comment]
same here for all repos

Versions
App Version: 2.12.0
Package Version: 17.0.3

**Comment by jlmelladovalle** [comment]
My enterprises are suffering this issue from a month ago on every cluster we own and managed thought Kubeapps. I was searching if there was a bitnami repo change to OCI, but only get they are using it to manually deploy each chart individually using helm command, deprecated helm chart repo (maybe the cause); there is no reference to OCI charts repo to change, neither from Bitnami nor here.

Please team, give us more information or update documentation about that.

**Comment by pmcdonald-metropolis** [comment]
bump: experiencing the same error for every helm chart.

**Comment by pmcdonald-metropolis** [comment]
I'm experiencing the same problem. None of the Bitnami charts are loading, and each one displays the identical error shown in the screenshot.

<img width="1521" alt="Screenshot 2024-12-13 at 10 52 15 AM" src="https://github.com/user-attachments/assets/23cb404b-11cc-429c-9de9-4b2d236d603e" />

**Comment by beltran-rubo** [comment]
We apologize for the delay on fixing this issue, we are actively working on addressing this issue and release a new version.

**Comment by zainulabidin302** [comment]
For the moment i downgraded to:

This did not work for me probably due to schema change from 17 & 16 ?
`helm upgrade kubeapps --namespace kubeapps oci://registry-1.docker.io/bitnamicharts/kubeapps --version 16.0.1`

So i did
```
base ❯ helm uninstall kubeapps --namespace kubeapps
release "kubeapps" uninstalled

and then
base ❯ helm install kubeapps --namespace kubeapps oci://registry-1.docker.io/bitnamicharts/kubeapps --version 16.0.1
```

**Comment by beltran-rubo** [comment]
This issue has been fixed in the latest release Kubeapps Helm chart 17.1.1, the Bitnami Helm index.yaml is supported with {{oci://}} references in Kubeapps.
